table Medidas_AD
	isHidden
	lineageTag: c7badb4a-3661-4961-a120-1576c2314372

	measure 'Plan Actividades Planificadas' = COUNTROWS('Fct_PlanFormacion')
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 13bf49f0-4051-4e59-bc23-7d071075004c

	measure 'Plan Actividades Ejecutadas' = CALCULATE(COUNTROWS('Fct_PlanFormacion'), 'Fct_PlanFormacion'[EstadoFormacion_Key] = "EJECUTADA")
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 9616bacc-cfe9-46d8-a9c4-6718f28557b6

	measure 'Plan Actividades Canceladas' = CALCULATE(COUNTROWS('Fct_PlanFormacion'), 'Fct_PlanFormacion'[EstadoFormacion_Key] = "CANCELADA")
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: e4a58cca-fb3d-46cb-aebe-80b96f1119e2

	measure 'Plan Actividades Reprogramadas' = CALCULATE(COUNTROWS('Fct_PlanFormacion'), 'Fct_PlanFormacion'[EstadoFormacion_Key] = "REPROGRAMADA")
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: da21c0c0-be26-42e8-8110-a1f302dc16fb

	measure 'Plan Actividades Vigentes' = [Plan Actividades Planificadas] - [Plan Actividades Canceladas]
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: ed3fc386-63b2-445b-95f7-451a885e0a14

	measure 'Plan Porcentaje Ejecucion' = DIVIDE([Plan Actividades Ejecutadas], [Plan Actividades Vigentes])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 737a2c66-b4af-454f-bafc-75392baf797f

	measure 'Plan Brecha Actividades' = [Plan Actividades Ejecutadas] - [Plan Actividades Vigentes]
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 750b8677-4138-4a17-b1f5-e376f47c957c

	measure 'Plan Publico Objetivo' = SUM('Fct_PlanFormacion'[PUBLICO OBJETIVO ])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 54afa7d7-e229-4660-bdae-72111fef494e

	measure 'Plan Asistencia Registrada' = SUM('Fct_PlanFormacion'[ASISTENCIA])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: cff3cfec-31b2-4cfa-ab36-a18517303712

	measure '% Cobertura' = DIVIDE(SUM('Fct_PlanFormacion'[ASISTENCIA]), SUM('Fct_PlanFormacion'[PUBLICO OBJETIVO ]), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: ee9905d4-fe15-4bcd-9d9c-4422c880a6e7

	measure '% Brecha Cobertura' = VAR _p = [% Cobertura] RETURN IF(ISBLANK(_p), BLANK(), MAX(0, 1 - _p))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 298b0543-503c-4670-aca5-40aa2ff218b0

	measure 'Plan Cobertura Asistencia' = [% Cobertura]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 2f3af5ac-9620-4a61-a5d4-3fbc94b2db22

	measure 'Plan Horas Formacion' = SUM('Fct_PlanFormacion'[TOTAL DE HORAS DE FORMACIÓN ])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: e053ccaa-25eb-4072-9620-4571a48635ee

	measure 'Plan Total Horas Formacion' = SUM('Fct_PlanFormacion'[TOTAL DE HORAS DE FORMACIÓN ])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: cf9e0ed7-bde3-405d-907d-af0daa4372e8

	measure 'Plan Costo' = SUM('Fct_PlanFormacion'[COSTO])
		formatString: $ #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 49cbeab6-ceb6-4613-987c-a8c3f50ecff5

	measure 'Asistencia Total Registros' = COUNTROWS('Fct_AsistenciaFormacion')
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 3d393594-40cc-41a2-8cd3-a8f9c1e0bb12

	measure 'Asistencia Total Asistentes' = [Asistencia Total Registros]
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 1872009d-5975-4079-a676-f9c0916a9862

	measure 'Asistencia Participantes Unicos' = DISTINCTCOUNT('Fct_AsistenciaFormacion'[Número de documento del participante])
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 2c935cb8-e80e-4265-8a82-945c88b62868

	measure 'Asistencia Formaciones' = DISTINCTCOUNT('Fct_AsistenciaFormacion'[TemaFormacion_Key])
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 2b7fd8ae-1e97-427e-9e8f-338bbcc3a95f

	measure 'Asistencia Total Convocados' = [Plan Publico Objetivo]
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 1d864477-151b-4977-b05a-c828a4d16009

	measure 'Asistencia Porcentaje Asistencia' = DIVIDE([Asistencia Total Asistentes], [Asistencia Total Convocados])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 02 Asistencia
		lineageTag: d8f8cff2-0bc9-4438-8a9a-43b36d82ef04

	measure 'Asistencia Porcentaje Ausentismo' = VAR _p = [Asistencia Porcentaje Asistencia] RETURN IF(ISBLANK(_p), BLANK(), MAX(0, 1 - _p))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 02 Asistencia
		lineageTag: 7e98b418-ad44-44df-953f-833d88f95c91

	measure 'Asistencia Promedio Por Formacion' = DIVIDE([Asistencia Total Asistentes], [Asistencia Formaciones])
		formatString: #,0.0
		displayFolder: 02 Asistencia
		lineageTag: 2b93e2e1-8605-4a8f-badb-120a66ee5f51

	measure 'Encuesta Total Respuestas' = COUNTROWS('Fct_EncuestaFormacion')
		formatString: #,0
		displayFolder: 03 Encuesta Formacion
		lineageTag: 8f3cef95-8fb8-44b3-8e1b-657872806636

	measure 'Encuesta Participantes Estimados' = [Encuesta Total Respuestas]
		formatString: #,0
		displayFolder: 03 Encuesta Formacion
		lineageTag: 8dce703a-0eee-483d-8bf2-2bf8feb77912

	measure 'Encuesta Tasa Respuesta' = DIVIDE([Encuesta Total Respuestas], [Asistencia Total Asistentes])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Encuesta Formacion
		lineageTag: 8c5290a2-677e-40b0-8c40-f693077cfdb5

	measure 'Encuesta Calificacion Promedio' =
			VAR _Suma =
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el dominio del tema por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la habilidad para comunicarse y transmitir ideas por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con las actividades o ejercicios por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el uso de ayudas didácticas por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la resolución de dudas u observaciones del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el cumplimiento del programa propuesto?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el espacio, logística y ambiente de la formación?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan oportuna fue la información respecto a fechas, horarios y lugar?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el logro de los objetivos propuestos?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la contribución del programa para tu desarrollo personal y/o profesional?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el acompañamiento de la Universidad Challenger en tu desarrollo personal y/o profesional?]) +
			    SUM('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
			VAR _Conteo =
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el dominio del tema por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la habilidad para comunicarse y transmitir ideas por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con las actividades o ejercicios por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el uso de ayudas didácticas por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la resolución de dudas u observaciones del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el cumplimiento del programa propuesto?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el espacio, logística y ambiente de la formación?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan oportuna fue la información respecto a fechas, horarios y lugar?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el logro de los objetivos propuestos?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la contribución del programa para tu desarrollo personal y/o profesional?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el acompañamiento de la Universidad Challenger en tu desarrollo personal y/o profesional?]) +
			    COUNT('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
			RETURN
			    DIVIDE(_Suma, _Conteo)
		formatString: 0.00
		displayFolder: 03 Encuesta Formacion
		lineageTag: 66d4c70a-b055-4891-9abe-6d10eda690dc

	measure 'Encuesta Favorabilidad' = DIVIDE(CALCULATE(COUNTROWS('Fct_EncuestaFormacion'), 'Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?] >= 4), [Encuesta Total Respuestas])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Encuesta Formacion
		lineageTag: 4444042a-1946-4ca9-97e1-6be11e260c0e

	measure 'Encuesta NPS Equivalente' =
			VAR _Total = COUNT('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
			VAR _Promotores = CALCULATE(COUNTROWS('Fct_EncuestaFormacion'), 'Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?] >= 5)
			VAR _Detractores = CALCULATE(COUNTROWS('Fct_EncuestaFormacion'), 'Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?] <= 3)
			RETURN
			    DIVIDE(_Promotores - _Detractores, _Total) * 100
		formatString: 0.0
		displayFolder: 03 Encuesta Formacion
		lineageTag: 3124a3a4-d281-4ef4-86de-717a9d7fd907

	measure 'Induccion Total Colaboradores' = COUNTROWS('Fct_Induccion')
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 3b28d7f6-130e-4260-bfe3-d840ffa3bdbb

	measure 'Induccion Colaboradores Unicos' = DISTINCTCOUNT('Fct_Induccion'[Colaborador_Key])
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 24f1148a-539f-4465-b843-3ed95f9b4368

	measure 'Induccion Aprobados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] IN { "APROBO", "APROBADO" })
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 0ac88ffa-7bc3-45b7-909d-a74217a123d4

	measure 'Induccion No Aprobados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] = "NO_APROBO")
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: ccffef5a-a187-4ddb-bd64-5755dbebdf3e

	measure 'Induccion Retiros' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] IN { "RETIRADO", "RENUNCIA" })
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: e4a40db9-198d-4158-9ccc-1cb3261f9fd2

	measure 'Induccion Onboarding' = DIVIDE([Induccion Onboarding Realizados], [Induccion Onboarding Participantes], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 7afb6905-9eeb-4444-8d1b-1dc1550c66ab

	measure 'Induccion Minutos Entrenamiento' = SUM('Fct_Induccion'[Min_Entrenamiento])
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: bf2ee324-989a-491e-a0f2-84923ea310db

	measure 'Induccion Horas Entrenamiento' = DIVIDE([Induccion Minutos Entrenamiento], 60)
		formatString: #,0.0
		displayFolder: 04 Induccion UC
		lineageTag: 5f477709-6bd7-46fb-b89d-9dbb43b5eef0

	measure 'Induccion Porcentaje Cumplimiento' = DIVIDE([Induccion Aprobados], [Induccion Total Colaboradores])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: e5679ca3-7b9c-4927-8d60-1e2a38d37b4f

	measure 'Induccion Tiempo Promedio Finalizacion Dias' = AVERAGE('Fct_Induccion'[Tiempo_Finalizacion_Dias])
		formatString: #,0.0
		displayFolder: 04 Induccion UC
		lineageTag: 4ecf7285-b950-42c1-b6bc-1382bd7a7848

	measure 'Induccion Cumplimiento Antes UC' = CALCULATE([Induccion Porcentaje Cumplimiento], 'Dim_SegmentoUC'[SegmentoUC_Key] = "Antes_UC")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 2ba24b53-d84d-4e15-963a-370651097629

	measure 'Induccion Cumplimiento UC 2025' = CALCULATE([Induccion Porcentaje Cumplimiento], 'Dim_SegmentoUC'[SegmentoUC_Key] = "UC_2025")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 706a9b2e-4a2f-4dc9-b4f6-a837fd99d2ed

	measure 'Induccion Cumplimiento UC 2026' = CALCULATE([Induccion Porcentaje Cumplimiento], 'Dim_SegmentoUC'[SegmentoUC_Key] = "UC_2026")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: f389252f-923d-498e-87d8-4298d4550f77

	measure 'Induccion Variacion UC2025 vs Antes UC' = [Induccion Cumplimiento UC 2025] - [Induccion Cumplimiento Antes UC]
		formatString: 0.0 pp;-0.0 pp;0.0 pp
		displayFolder: 04 Induccion UC
		lineageTag: 9c81cf4a-cd06-468c-affc-34a53cdc1fb7

	measure 'Induccion Variacion UC2026 vs UC2025' = [Induccion Cumplimiento UC 2026] - [Induccion Cumplimiento UC 2025]
		formatString: 0.0 pp;-0.0 pp;0.0 pp
		displayFolder: 04 Induccion UC
		lineageTag: 28128333-0bfc-4b7b-aa96-fd7f89a1e03d

	measure 'KPI Indice Aprendizaje' =
			VAR _Base =
			    {
			        [Plan Porcentaje Ejecucion],
			        [Plan Cobertura Asistencia],
			        [Encuesta Favorabilidad],
			        [Induccion Porcentaje Cumplimiento]
			    }
			RETURN
			    AVERAGEX(FILTER(_Base, NOT ISBLANK([Value])), [Value])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: 20367492-6403-4ce2-9065-99d64758cb84

	measure 'KPI Actividades Totales Gestionadas' = [Plan Actividades Planificadas] + [Asistencia Total Registros] + [Encuesta Total Respuestas] + [Induccion Total Colaboradores]
		formatString: #,0
		displayFolder: 00 KPIs Gerenciales
		lineageTag: 436e3d36-7e91-45a6-8731-006381405169

	measure 'Ranking Area Cumplimiento Plan' = RANKX(ALLSELECTED('Dim_Area'[Area]), [Plan Porcentaje Ejecucion], , DESC, Dense)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: 7f6aca7f-7192-4d86-8202-b826d0067630

	measure 'Ranking Area Cumplimiento Induccion' = RANKX(ALLSELECTED('Dim_Area'[Area]), [Induccion Porcentaje Cumplimiento], , DESC, Dense)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: 838ac55b-68aa-4f9b-890c-5e93178fb5a9

	measure 'Ranking Empresa Asistencia' = RANKX(ALLSELECTED('Dim_Empresa'[Empresa]), [Asistencia Total Asistentes], , DESC, Dense)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: b108b9b7-eb2f-4f23-889d-cf61f1f6492f

	measure 'Alerta Plan Bajo Cumplimiento' = IF(NOT ISBLANK([Plan Porcentaje Ejecucion]) && [Plan Porcentaje Ejecucion] < 0.8, 1, 0)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: 60c3836c-4cfd-4e27-a23a-dd03110ade43

	measure 'Alerta Induccion Bajo Cumplimiento' = IF(NOT ISBLANK([Induccion Porcentaje Cumplimiento]) && [Induccion Porcentaje Cumplimiento] < 0.9, 1, 0)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: a0bf2452-432c-4a18-8ebe-c63f9fd5271d

	measure 'Hallazgo Plan' =
			"Plan: " & FORMAT([Plan Porcentaje Ejecucion], "0.0%") &
			" de ejecucion; brecha de " & FORMAT([Plan Brecha Actividades], "#,0") & " actividades."
		displayFolder: 06 Hallazgos
		lineageTag: c90f3e51-b848-44f7-bfe2-c044e8551ac5

	measure 'Hallazgo Asistencia' =
			"Asistencia: " & FORMAT([Asistencia Total Asistentes], "#,0") &
			" registros y " & FORMAT([% Cobertura], "0.0%") & " de cobertura registrada en el plan."
		displayFolder: 06 Hallazgos
		lineageTag: dd1611ff-cc0b-4c8b-bc5d-2eab245b0df8

	measure 'Hallazgo UC' =
			"UC: Antes " & FORMAT([Induccion Cumplimiento Antes UC], "0.0%") &
			", UC 2025 " & FORMAT([Induccion Cumplimiento UC 2025], "0.0%") &
			", UC 2026 " & FORMAT([Induccion Cumplimiento UC 2026], "0.0%") & "."
		displayFolder: 06 Hallazgos
		lineageTag: 910b7dbd-062d-48a9-8a26-9c7eda604bea

	measure 'Plan Eficacia Promedio' = DIVIDE(AVERAGE('Fct_PlanFormacion'[EFICACIA]), 100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 7c112d7e-9a2c-4aae-925e-fdecb44a6c6a

	measure 'Plan Actividades Pendientes' = [Plan Actividades Vigentes] - [Plan Actividades Ejecutadas]
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 3d4f4796-4656-460c-85ae-281be025cb69

	measure 'Plan Variacion Ejecutadas MoM' = [Plan Actividades Ejecutadas] - CALCULATE([Plan Actividades Ejecutadas], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: cb518286-cff8-4df5-b208-f5f8588f2a32

	measure 'Plan Variacion Ejecutadas MoM %' = DIVIDE([Plan Variacion Ejecutadas MoM], CALCULATE([Plan Actividades Ejecutadas], DATEADD('Dim_Calendario'[Date], -1, MONTH)))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: 85b0fc0f-6973-4584-b043-3938adc6d9a2

	measure 'Plan Variacion Ejecutadas YoY' = [Plan Actividades Ejecutadas] - CALCULATE([Plan Actividades Ejecutadas], SAMEPERIODLASTYEAR('Dim_Calendario'[Date]))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: 162123aa-1e9e-4298-ae3d-4de7e25f5fc9

	measure 'Plan Variacion Ejecutadas YoY %' = DIVIDE([Plan Variacion Ejecutadas YoY], CALCULATE([Plan Actividades Ejecutadas], SAMEPERIODLASTYEAR('Dim_Calendario'[Date])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: b47209f7-088c-491e-964e-c4454d69e423

	measure 'Asistencia Variacion MoM' = [Asistencia Total Asistentes] - CALCULATE([Asistencia Total Asistentes], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: 1461ce00-99be-433f-9bfd-fc3828401a21

	measure 'Asistencia Variacion MoM %' = DIVIDE([Asistencia Variacion MoM], CALCULATE([Asistencia Total Asistentes], DATEADD('Dim_Calendario'[Date], -1, MONTH)))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: fcd3c38b-ecb4-480e-b38d-4853b834bc87

	measure 'Asistencia Variacion YoY' = [Asistencia Total Asistentes] - CALCULATE([Asistencia Total Asistentes], SAMEPERIODLASTYEAR('Dim_Calendario'[Date]))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: 420b2312-0cd1-48a7-8dcd-756f9f52842a

	measure 'Asistencia Variacion YoY %' = DIVIDE([Asistencia Variacion YoY], CALCULATE([Asistencia Total Asistentes], SAMEPERIODLASTYEAR('Dim_Calendario'[Date])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: 9813eb66-418c-48b0-9710-677970200ba3

	measure 'Induccion Variacion Colaboradores MoM' = [Induccion Total Colaboradores] - CALCULATE([Induccion Total Colaboradores], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: fa88eb05-9b5c-4742-806b-31938463215d

	measure 'Induccion Variacion Colaboradores MoM %' = DIVIDE([Induccion Variacion Colaboradores MoM], CALCULATE([Induccion Total Colaboradores], DATEADD('Dim_Calendario'[Date], -1, MONTH)))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: a166664c-36ef-4674-8226-07abdbece4bb

	measure 'Induccion Variacion Cumplimiento MoM' = [Induccion Porcentaje Cumplimiento] - CALCULATE([Induccion Porcentaje Cumplimiento], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: 0.0 pp;-0.0 pp;0.0 pp
		displayFolder: 07 Comparativos
		lineageTag: 747a66fd-67af-4f14-8826-1e2d27022fa5

	measure 'KPI Frente Pendiente' = BLANK()
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: ad78c626-132c-4dee-addc-e2167c6375a3

	measure 'KPI Nivel Cargo Pendiente' = BLANK()
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: 26162c48-6994-43d9-8f3b-01f8af6b5a24

	measure 'Encuesta Calificacion Satisfaccion Formacion' = AVERAGE('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
		formatString: 0.00
		displayFolder: 03 Encuesta Formacion
		lineageTag: 3f212dda-cebe-415e-9990-10491b437488

	measure 'Encuesta Favorabilidad Variacion MoM' = [Encuesta Favorabilidad] - CALCULATE([Encuesta Favorabilidad], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: 8098de79-6685-468c-8a65-d28dd3425b31

	measure 'Encuesta Favorabilidad Variacion YoY' = [Encuesta Favorabilidad] - CALCULATE([Encuesta Favorabilidad], SAMEPERIODLASTYEAR('Dim_Calendario'[Date]))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: eb2d8e62-aef9-4d7d-bde2-9967ea9477d5

	measure 'HC Total Colaborador Mes' = DISTINCTCOUNT('Dim_ColaboradorHC'[Colaborador_Key])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: f38f73e4-280f-4b41-9ed2-f93ca77a7a86

	measure 'HC Total Colaboradores Unicos' = DISTINCTCOUNT('Dim_ColaboradorHC'[Numero_Documento])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: d74aff9e-857b-4aec-804e-4bb2ce4f19fd

	measure 'HC Recuento Tipo Cargo' = COUNTA('Dim_ColaboradorHC'[Tipo_Cargo])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: 9f4f8060-aa3c-4b60-ba1f-ecb70ec5c987

	measure 'HC Porcentaje Tipo Cargo' = DIVIDE([HC Recuento Tipo Cargo], CALCULATE([HC Recuento Tipo Cargo], ALLSELECTED('Dim_ColaboradorHC'[Tipo_Cargo])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 08 Headcount HC
		lineageTag: 436ae1ed-4b2c-4a64-85ac-14f785500dd6

	measure 'HC Tipos Cargo' = DISTINCTCOUNT('Dim_ColaboradorHC'[Tipo_Cargo])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: b29411ac-359e-49a8-b86a-4b21cf792b49

	measure 'Asistencia Registros HC Match' =
			VAR _KeysHC = VALUES('Dim_ColaboradorHC'[Colaborador_Key])
			RETURN
			    CALCULATE(
			        [Asistencia Total Registros],
			        TREATAS(_KeysHC, 'Fct_AsistenciaFormacion'[Colaborador_Key])
			    )
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: d21be951-d44a-4d57-a66d-dd46c9b1caa4

	measure 'Asistencia Colaborador Mes HC Match' =
			VAR _KeysHC = VALUES('Dim_ColaboradorHC'[Colaborador_Key])
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT('Fct_AsistenciaFormacion'[Colaborador_Key]),
			        TREATAS(_KeysHC, 'Fct_AsistenciaFormacion'[Colaborador_Key])
			    )
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: 0c0ebe99-e406-4e2f-81f0-21e8585c88ee

	measure 'Asistencia Distribucion Tipo Cargo %' = DIVIDE([Asistencia Registros HC Match], CALCULATE([Asistencia Registros HC Match], ALLSELECTED('Dim_ColaboradorHC'[Tipo_Cargo])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 08 Headcount HC
		lineageTag: bfafa5d7-6dd4-487e-be5a-a37de2ed377c

	measure 'Asistencia Registros Sin HC Match' =
			VAR _Total =
			    CALCULATE(
			        [Asistencia Total Registros],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			VAR _Match =
			    CALCULATE(
			        [Asistencia Registros HC Match],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			RETURN
			    _Total - _Match
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: 04f63099-e053-40aa-a2b0-d36dead67715

	measure 'Asistencia Porcentaje HC Match' =
			VAR _Total =
			    CALCULATE(
			        [Asistencia Total Registros],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			VAR _Match =
			    CALCULATE(
			        [Asistencia Registros HC Match],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			RETURN
			    DIVIDE(_Match, _Total)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 08 Headcount HC
		lineageTag: 412f9f00-b82b-4f2d-9a8a-7252d1bc77c2

	measure 'Induccion Onboarding Realizados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] IN { "APROBO", "APROBADO" })
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 06e6c60a-5132-4683-b6dc-e6feef265df3

	measure 'Induccion Onboarding Participantes' = CALCULATE(DISTINCTCOUNT('Fct_Induccion'[Colaborador_Key]), 'Fct_Induccion'[EstadoInduccion_Key] <> "RENUNCIA")
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: ea4f03a1-dda9-4f02-b869-fe33d44c4736

	measure 'Induccion Entrenamiento Realizados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[Entrenamiento] = "SI")
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 125b628c-9be2-452e-93cf-4e09cebcaacf

	measure 'Induccion Entrenamiento Base' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[Entrenamiento] = "SI" || 'Fct_Induccion'[Entrenamiento] = "PENDIENTE" || ISBLANK('Fct_Induccion'[Entrenamiento]))
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 9755415a-51b9-4f80-a07d-cbf78089cb75

	measure 'Induccion Porcentaje Entrenamiento' = DIVIDE([Induccion Entrenamiento Realizados], [Induccion Entrenamiento Base], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 58a9b4a5-e29c-4872-ac96-a80a86f57d8e

	measure 'Induccion Entrenamiento Neto Realizados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[Archivo] = 50)
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 078f9c7c-99d4-44a7-8e05-7188a861ff55

	measure 'Induccion Porcentaje Entrenamiento Neto' = DIVIDE([Induccion Entrenamiento Neto Realizados], [Induccion Entrenamiento Base], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: f65cb718-1c4d-4332-9ad3-fc3614da6098

	measure 'PDI Total' = COUNTROWS('Fct_Seguimiento_PDI')
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 5a0f5c43-7197-4b55-bdb5-78b021eb2a9e

	measure 'PDI Colaboradores Unicos' = DISTINCTCOUNT('Fct_Seguimiento_PDI'[Identificacion_Colaborador])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: b3fb1782-2f58-46f8-9745-391f13483a56

	measure 'PDI Motivos Distintos' = DISTINCTCOUNT('Dim_MotivoPDI'[MotivoPDI_Key])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 7ba1e69c-e498-4147-b910-d15c197deac1

	measure 'PDI Jefes Con PDI' = DISTINCTCOUNT('Fct_Seguimiento_PDI'[Jefe_Inmediato])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: db9526bf-b4fd-4244-a819-65b4d9b6fcc0

	measure 'PDI Cargos Con PDI' = DISTINCTCOUNT('Fct_Seguimiento_PDI'[Cargo])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 6c748cfe-5f00-4a07-8812-22f9772fc8ee

	measure 'PDI Avance Promedio' =
			VAR _Avance = AVERAGE('Fct_Seguimiento_PDI'[Avance_PDI])
			RETURN IF(_Avance > 1, DIVIDE(_Avance, 100), _Avance)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: d3c5fd73-5514-452a-9f17-7d6b4acc146f

	measure 'PDI Finalizados' =
			CALCULATE(
			    [PDI Total],
			    'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO" }
			)
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: f8448f24-385d-40ac-bd45-aaac5564f3ac

	measure 'PDI Activos' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        NOT (
			            'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			        )
			    )
			)
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 950fa908-217a-41c9-9faa-4e9652af48b9

	measure 'PDI Pendientes' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "PENDIENTE", "EN PROCESO", "ACTIVO", "" }
			            || ISBLANK('Fct_Seguimiento_PDI'[EstadoPDI_Key])
			    )
			)
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 4425b154-c390-4b36-b8e2-7db2c812e5fd

	measure 'PDI Porcentaje Activos' = DIVIDE([PDI Activos], [PDI Total], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: 15cc444a-841d-4c49-b4c0-7c3cf976c4f2

	measure 'PDI Porcentaje Por Estado' = DIVIDE([PDI Total], CALCULATE([PDI Total], ALLSELECTED('Dim_EstadoPDI'[Estado_PDI])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: 707e9860-ed38-4dc1-a671-8117f3762692

	measure 'PDI Porcentaje Por Motivo' = DIVIDE([PDI Total], CALCULATE([PDI Total], ALLSELECTED('Dim_MotivoPDI'[Motivo_PDI])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: ebfc3785-f433-4bea-818b-bb45d4c0cb4b

	measure 'PDI Avance Cero' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        COALESCE('Fct_Seguimiento_PDI'[Avance_PDI], 0) = 0
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 086d71ab-3c67-4838-b895-5970f0cb7e0c

	measure 'PDI Bajo Avance' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        VAR _Avance = IF('Fct_Seguimiento_PDI'[Avance_PDI] > 1, DIVIDE('Fct_Seguimiento_PDI'[Avance_PDI], 100), 'Fct_Seguimiento_PDI'[Avance_PDI])
			        RETURN _Avance > 0 && _Avance < 0.4
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 9e73a3c1-e8bd-42f3-97d3-cd63918c668c

	measure 'PDI Vencidos' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        NOT ISBLANK('Fct_Seguimiento_PDI'[Fecha_Fin])
			            && 'Fct_Seguimiento_PDI'[Fecha_Fin] < TODAY()
			            && NOT (
			                'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			            )
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 310e0db2-f0d1-4d70-a8b7-5b8147cfcc09

	measure 'PDI Proximos A Vencer' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        NOT ISBLANK('Fct_Seguimiento_PDI'[Fecha_Fin])
			            && 'Fct_Seguimiento_PDI'[Fecha_Fin] >= TODAY()
			            && 'Fct_Seguimiento_PDI'[Fecha_Fin] <= TODAY() + 30
			            && NOT (
			                'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			            )
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: e7d2735e-d44e-4d17-8a64-49ad6772b7ab

	measure 'PDI Acompanamientos Programados' =
			CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_1] IN { "P", "E", "PROGRAMADO", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_2] IN { "P", "E", "PROGRAMADO", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_3] IN { "P", "E", "PROGRAMADO", "EJECUTADO" })
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 2930cd49-066d-46c1-8af5-c7b11eea1c81

	measure 'PDI Acompanamientos Ejecutados' =
			CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_1] IN { "E", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_2] IN { "E", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_3] IN { "E", "EJECUTADO" })
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 7b38b540-17ee-4260-8b71-af862d8ebc4f

	measure 'PDI Cumplimiento Acompanamientos' = DIVIDE([PDI Acompanamientos Ejecutados], [PDI Acompanamientos Programados], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: c052eeff-33ed-4762-b7b8-09026516a598

	measure 'PDI Alertas Criticas' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        VAR _Avance = IF('Fct_Seguimiento_PDI'[Avance_PDI] > 1, DIVIDE('Fct_Seguimiento_PDI'[Avance_PDI], 100), 'Fct_Seguimiento_PDI'[Avance_PDI])
			        VAR _Vencido =
			            NOT ISBLANK('Fct_Seguimiento_PDI'[Fecha_Fin])
			                && 'Fct_Seguimiento_PDI'[Fecha_Fin] < TODAY()
			                && NOT (
			                    'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			                )
			        RETURN COALESCE(_Avance, 0) = 0 || (_Avance > 0 && _Avance < 0.4) || _Vencido
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 5acc123f-755e-4c25-85f0-8f26d30a6718

	measure 'PDI Ranking Area Total' = RANKX(ALLSELECTED('Dim_Area'[Area]), [PDI Total], , DESC, Dense)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: b35f3a01-d64d-475a-92b0-984816763f7b

	measure 'PDI Ranking Jefe Bajo Avance' = RANKX(ALLSELECTED('Fct_Seguimiento_PDI'[Jefe_Inmediato]), [PDI Bajo Avance], , DESC, Dense)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 4d23f49d-100d-4fcd-9bc6-af3e454183f7

	measure 'KPI Indice Desarrollo' =
			VAR _SinVencidos = 1 - DIVIDE([PDI Vencidos], [PDI Total], 0)
			VAR _Base =
			    {
			        [PDI Avance Promedio],
			        [PDI Cumplimiento Acompanamientos],
			        _SinVencidos
			    }
			RETURN
			    AVERAGEX(FILTER(_Base, NOT ISBLANK([Value])), [Value])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: e1b75bcf-3df0-489e-9ccb-f0d3d97846fb

	measure 'HTML Inicio Corporativo Propuesta 1' =
			VAR _FA = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			VAR _Horas = IF(ISBLANK([Plan Horas Formacion]), "-", FORMAT([Plan Horas Formacion], "#,0"))
			VAR _Cob = IF(ISBLANK([% Cobertura]), "-", FORMAT([% Cobertura], "0.0%"))
			VAR _Sat = IF(ISBLANK([Encuesta Favorabilidad]), "-", FORMAT([Encuesta Favorabilidad], "0.0%"))
			VAR _Onb = IF(ISBLANK([Induccion Porcentaje Cumplimiento]), "-", FORMAT([Induccion Porcentaje Cumplimiento], "0.0%"))
			VAR _Ent = IF(ISBLANK([Induccion Porcentaje Entrenamiento Neto]), "-", FORMAT([Induccion Porcentaje Entrenamiento Neto], "0.0%"))
			VAR _IApz = IF(ISBLANK([KPI Indice Aprendizaje]), "-", FORMAT([KPI Indice Aprendizaje], "0.0%"))
			VAR _PDIAct = IF(ISBLANK([PDI Activos]), "-", FORMAT([PDI Activos], "#,0"))
			VAR _PDIAvz = IF(ISBLANK([PDI Avance Promedio]), "-", FORMAT([PDI Avance Promedio], "0.0%"))
			VAR _PDIAvzBar = IF(ISBLANK([PDI Avance Promedio]), "0%", FORMAT(MIN([PDI Avance Promedio], 1), "0.0%"))
			VAR _PDIAlt = IF(ISBLANK([PDI Alertas Criticas]), "-", FORMAT([PDI Alertas Criticas], "#,0"))
			VAR _Acomp = IF(ISBLANK([PDI Cumplimiento Acompanamientos]), "-", FORMAT([PDI Cumplimiento Acompanamientos], "0.0%"))
			VAR _IDes = IF(ISBLANK([KPI Indice Desarrollo]), "-", FORMAT([KPI Indice Desarrollo], "0.0%"))
			VAR _PDIMot = COALESCE([PDI Motivo Principal], "Sin datos")
			VAR _PDIEst = COALESCE([PDI Estado Principal], "Sin datos")
			VAR _ERet = IF(ISBLANK([EntrevistaRetiro Total Validas]), "-", FORMAT([EntrevistaRetiro Total Validas], "#,0"))
			VAR _EPrev = IF(ISBLANK([EntrevistaRetiro Porcentaje Causas Prevenibles]), "-", FORMAT([EntrevistaRetiro Porcentaje Causas Prevenibles], "0.0%"))
			VAR _EVolPct = IF(ISBLANK([EntrevistaRetiro Porcentaje Voluntarios]), "-", FORMAT([EntrevistaRetiro Porcentaje Voluntarios], "0.0%"))
			VAR _BProg = IF(ISBLANK([Bienestar Programaciones Registradas Ejecucion]), "-", FORMAT([Bienestar Programaciones Registradas Ejecucion], "#,0"))
			VAR _BEjec = IF(ISBLANK([Bienestar Ejecutadas]), "-", FORMAT([Bienestar Ejecutadas], "#,0"))
			VAR _BCump = IF(ISBLANK([Bienestar Cumplimiento al Corte %]), "-", FORMAT([Bienestar Cumplimiento al Corte %], "0.0%"))
			VAR _DesCobComp = IF(ISBLANK([Competencias Cobertura %]), "-", FORMAT([Competencias Cobertura %], "0.0%"))
			VAR _DesCobObj = IF(ISBLANK([Desempeno Cobertura Objetivos %]), "-", FORMAT([Desempeno Cobertura Objetivos %], "0.0%"))
			VAR _DesPromComp = IF(ISBLANK([Competencias Promedio]), "-", FORMAT([Competencias Promedio], "0.0"))
			VAR _NivelCritico = CALCULATE([Desempeno % por Nivel], 'Fct_Desempeno_2025'[Interpretacion_Homologada] = "Crítico")
			VAR _NivelBajo = CALCULATE([Desempeno % por Nivel], 'Fct_Desempeno_2025'[Interpretacion_Homologada] = "Bajo")
			VAR _NivelIntermedio = CALCULATE([Desempeno % por Nivel], 'Fct_Desempeno_2025'[Interpretacion_Homologada] = "Intermedio")
			VAR _NivelAlto = CALCULATE([Desempeno % por Nivel], 'Fct_Desempeno_2025'[Interpretacion_Homologada] = "Alto")
			VAR _NivelAvanzado = CALCULATE([Desempeno % por Nivel], 'Fct_Desempeno_2025'[Interpretacion_Homologada] = "Avanzado")
			VAR _NivelCriticoTxt = IF(ISBLANK(_NivelCritico), "-", FORMAT(_NivelCritico, "0%"))
			VAR _NivelBajoTxt = IF(ISBLANK(_NivelBajo), "-", FORMAT(_NivelBajo, "0%"))
			VAR _NivelIntermedioTxt = IF(ISBLANK(_NivelIntermedio), "-", FORMAT(_NivelIntermedio, "0%"))
			VAR _NivelAltoTxt = IF(ISBLANK(_NivelAlto), "-", FORMAT(_NivelAlto, "0%"))
			VAR _NivelAvanzadoTxt = IF(ISBLANK(_NivelAvanzado), "-", FORMAT(_NivelAvanzado, "0%"))
			VAR _NivelCriticoBar = IF(ISBLANK(_NivelCritico), "0%", FORMAT(MIN(_NivelCritico, 1), "0%"))
			VAR _NivelBajoBar = IF(ISBLANK(_NivelBajo), "0%", FORMAT(MIN(_NivelBajo, 1), "0%"))
			VAR _NivelIntermedioBar = IF(ISBLANK(_NivelIntermedio), "0%", FORMAT(MIN(_NivelIntermedio, 1), "0%"))
			VAR _NivelAltoBar = IF(ISBLANK(_NivelAlto), "0%", FORMAT(MIN(_NivelAlto, 1), "0%"))
			VAR _NivelAvanzadoBar = IF(ISBLANK(_NivelAvanzado), "0%", FORMAT(MIN(_NivelAvanzado, 1), "0%"))
			VAR _CtaTexto =
			    SWITCH(
			        _FA,
			        "Aprendizaje", "Ver tablero completo de Aprendizaje",
			        "Desarrollo", "Ver resumen ejecutivo de Desarrollo",
			        "Bienestar y Clima", "Ver tablero completo de Bienestar y Clima",
			        "Desempeño", "Ver frente Desempe&ntilde;o",
			        "Ver tablero completo de Aprendizaje"
			    )
			VAR _LeftContent =
			    IF(_FA = "Aprendizaje",
			        "<div style='font-size:11px;color:#F7931E;font-weight:800;text-transform:uppercase;letter-spacing:1.4px;'>Frente activo</div>" &
			        "<div style='font-size:30px;font-weight:800;margin-top:4px;color:#000032;'>Aprendizaje</div>" &
			        "<div style='font-size:12px;color:#53657D;line-height:17px;margin-top:7px;'>Formaci&oacute;n, cobertura, satisfacci&oacute;n, onboarding y entrenamiento inicial.</div>" &
			        "<div style='display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:15px;'>" &
			        "<div style='border-left:4px solid #F7931E;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Horas formaci&oacute;n</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Horas & "</div></div>" &
			        "<div style='border-left:4px solid #1B487F;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Cobertura</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Cob & "</div></div>" &
			        "<div style='border-left:4px solid #1A3059;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Satisfacci&oacute;n</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Sat & "</div></div>" &
			        "<div style='border-left:4px solid #0B1C35;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Onboarding</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Onb & "</div></div>" &
			        "</div><div style='display:flex;gap:10px;margin-top:11px;'>" &
			        "<div style='flex:1;background:#0B1C35;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Entrenamiento neto</div><div style='font-size:21px;font-weight:800;'>" & _Ent & "</div></div>" &
			        "<div style='flex:1;background:#1B487F;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Indice Aprendizaje</div><div style='font-size:21px;font-weight:800;'>" & _IApz & "</div></div>" &
			        "</div><div style='position:absolute;left:22px;bottom:26px;width:548px;text-align:center;background:#F7931E;color:#fff;border-radius:8px;padding:9px;font-size:11px;font-weight:800;box-sizing:border-box;'>" & _CtaTexto & "</div>",
			    IF(_FA = "Desarrollo",
			        "<div style='font-size:11px;color:#F7931E;font-weight:800;text-transform:uppercase;letter-spacing:1.4px;'>Frente activo</div>" &
			        "<div style='font-size:30px;font-weight:800;margin-top:4px;color:#000032;'>Desarrollo</div>" &
			        "<div style='font-size:12px;color:#53657D;line-height:17px;margin-top:7px;'>PDI, movilidad, sucesi&oacute;n y cargos cr&iacute;ticos.</div>" &
			        "<div style='display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:15px;'>" &
			        "<div style='border-left:4px solid #F7931E;background:#F7F9FC;border-radius:8px;padding:11px 13px;overflow:hidden;'><div style='font-size:9px;color:#53657D;text-transform:uppercase;letter-spacing:0.9px;'>Motivo PDI</div><div style='font-size:12px;font-weight:800;color:#1B487F;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;'>" & _PDIMot & "</div><div style='margin-top:6px;display:inline-block;background:#F7931E;color:#fff;border-radius:10px;padding:2px 8px;font-size:9px;font-weight:700;'>Principal</div></div>" &
			        "<div style='border-left:4px solid #1B487F;background:#F7F9FC;border-radius:8px;padding:11px 13px;overflow:hidden;'><div style='font-size:9px;color:#53657D;text-transform:uppercase;letter-spacing:0.9px;'>Estado &middot; Avance</div><div style='display:flex;align-items:center;gap:7px;margin-top:5px;'><span style='background:#1B487F;color:#fff;border-radius:10px;padding:2px 8px;font-size:9px;font-weight:700;white-space:nowrap;overflow:hidden;max-width:110px;'>" & _PDIEst & "</span><span style='font-size:17px;font-weight:800;color:#1B487F;'>" & _PDIAvz & "</span></div><div style='margin-top:6px;height:4px;background:#D8E4F0;border-radius:2px;'><div style='width:" & _PDIAvzBar & ";height:4px;background:#1B487F;border-radius:2px;'></div></div></div>" &
			        "</div><div style='display:flex;gap:8px;margin-top:11px;'>" &
			        "<div style='flex:1;background:#F7F9FC;border:1px dashed #B0C4D8;border-radius:8px;padding:9px 11px;'><div style='font-size:10px;color:#53657D;'>Movilidad</div><div style='font-size:12px;color:#53657D;font-style:italic;font-weight:700;margin-top:3px;'>Pendiente</div></div>" &
			        "<div style='flex:1;background:#F7F9FC;border:1px dashed #B0C4D8;border-radius:8px;padding:9px 11px;'><div style='font-size:10px;color:#53657D;'>Sucesi&oacute;n</div><div style='font-size:12px;color:#53657D;font-style:italic;font-weight:700;margin-top:3px;'>Pendiente</div></div>" &
			        "<div style='flex:1;background:#F7F9FC;border:1px dashed #B0C4D8;border-radius:8px;padding:9px 11px;'><div style='font-size:10px;color:#53657D;'>Cargos cr&iacute;ticos</div><div style='font-size:12px;color:#53657D;font-style:italic;font-weight:700;margin-top:3px;'>Pendiente</div></div>" &
			        "</div><div style='position:absolute;left:22px;bottom:26px;width:548px;text-align:center;background:#F7931E;color:#fff;border-radius:8px;padding:9px;font-size:11px;font-weight:800;box-sizing:border-box;'>" & _CtaTexto & "</div>",
			    IF(_FA = "Bienestar y Clima",
			        "<div style='font-size:11px;color:#F7931E;font-weight:800;text-transform:uppercase;letter-spacing:1.4px;'>Frente activo</div>" &
			        "<div style='font-size:30px;font-weight:800;margin-top:4px;color:#000032;'>Bienestar y Clima</div>" &
			        "<div style='font-size:12px;color:#53657D;line-height:17px;margin-top:7px;'>Entrevista de Retiro y Plan de Bienestar activos. Clima laboral y eNPS en roadmap.</div>" &
			        "<div style='display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:15px;'>" &
			        "<div style='border-left:4px solid #F7931E;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Entrevistas v&aacute;lidas</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _ERet & "</div></div>" &
			        "<div style='border-left:4px solid #1B487F;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Causas prevenibles</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _EPrev & "</div></div>" &
			        "<div style='border-left:4px solid #1A3059;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Programaciones vigentes</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _BProg & "</div></div>" &
			        "<div style='border-left:4px solid #0B1C35;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Actividades ejecutadas</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _BEjec & "</div></div>" &
			        "</div><div style='display:flex;gap:10px;margin-top:11px;'>" &
			        "<div style='flex:1;background:#0B1C35;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Retiros voluntarios</div><div style='font-size:21px;font-weight:800;'>" & _EVolPct & "</div></div>" &
			        "<div style='flex:1;background:#1B487F;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Cumplimiento al corte</div><div style='font-size:21px;font-weight:800;'>" & _BCump & "</div></div>" &
			        "</div><div style='position:absolute;left:22px;bottom:26px;width:548px;text-align:center;background:#F7931E;color:#fff;border-radius:8px;padding:9px;font-size:11px;font-weight:800;box-sizing:border-box;'>" & _CtaTexto & "</div>",
			        "<div style='font-size:11px;color:#F7931E;font-weight:800;text-transform:uppercase;letter-spacing:1.4px;'>Frente activo</div>" &
			        "<div style='font-size:30px;font-weight:800;margin-top:4px;color:#000032;'>Desempe&ntilde;o</div>" &
			        "<div style='font-size:12px;color:#53657D;line-height:17px;margin-top:7px;'>Medici&oacute;n de objetivos, competencias y evoluci&oacute;n del desempe&ntilde;o organizacional.</div>" &
			        "<div style='display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:15px;'>" &
			        "<div style='border-left:4px solid #F7931E;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Cobertura competencias</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _DesCobComp & "</div></div>" &
			        "<div style='border-left:4px solid #1B487F;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Cobertura objetivos</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _DesCobObj & "</div></div>" &
			        "<div style='border-left:4px solid #1A3059;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Promedio competencias</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _DesPromComp & "</div></div>" &
			        "<div style='border-left:4px solid #0B1C35;background:#F7F9FC;border-radius:8px;padding:9px 11px;'><div style='font-size:10px;color:#53657D;'>Curva por niveles</div>" &
			        "<div style='display:grid;gap:3px;margin-top:6px;font-size:8px;color:#53657D;'>" &
			        "<div style='display:grid;grid-template-columns:52px 1fr 26px;align-items:center;gap:5px;'><span>Cr&iacute;tico</span><span style='height:5px;background:#DCE5F2;border-radius:6px;'><span style='display:block;width:" & _NivelCriticoBar & ";height:5px;background:#F7931E;border-radius:6px;'></span></span><b style='color:#1B487F;text-align:right;'>" & _NivelCriticoTxt & "</b></div>" &
			        "<div style='display:grid;grid-template-columns:52px 1fr 26px;align-items:center;gap:5px;'><span>Bajo</span><span style='height:5px;background:#DCE5F2;border-radius:6px;'><span style='display:block;width:" & _NivelBajoBar & ";height:5px;background:#1A3059;border-radius:6px;'></span></span><b style='color:#1B487F;text-align:right;'>" & _NivelBajoTxt & "</b></div>" &
			        "<div style='display:grid;grid-template-columns:52px 1fr 26px;align-items:center;gap:5px;'><span>Intermedio</span><span style='height:5px;background:#DCE5F2;border-radius:6px;'><span style='display:block;width:" & _NivelIntermedioBar & ";height:5px;background:#1B487F;border-radius:6px;'></span></span><b style='color:#1B487F;text-align:right;'>" & _NivelIntermedioTxt & "</b></div>" &
			        "<div style='display:grid;grid-template-columns:52px 1fr 26px;align-items:center;gap:5px;'><span>Alto</span><span style='height:5px;background:#DCE5F2;border-radius:6px;'><span style='display:block;width:" & _NivelAltoBar & ";height:5px;background:#1B487F;border-radius:6px;'></span></span><b style='color:#1B487F;text-align:right;'>" & _NivelAltoTxt & "</b></div>" &
			        "<div style='display:grid;grid-template-columns:52px 1fr 26px;align-items:center;gap:5px;'><span>Avanzado</span><span style='height:5px;background:#DCE5F2;border-radius:6px;'><span style='display:block;width:" & _NivelAvanzadoBar & ";height:5px;background:#0B1C35;border-radius:6px;'></span></span><b style='color:#1B487F;text-align:right;'>" & _NivelAvanzadoTxt & "</b></div>" &
			        "</div></div></div>" &
			        "<div style='position:absolute;left:22px;bottom:26px;width:548px;text-align:center;background:#F7931E;color:#fff;border-radius:8px;padding:9px;font-size:11px;font-weight:800;box-sizing:border-box;'>" & _CtaTexto & "</div>"
			    )))
			VAR _LeftBg = IF(_FA = "Aprendizaje" || _FA = "Desarrollo" || _FA = "Bienestar y Clima" || _FA = "Desempeño", "#ffffff", "#F9FAFC")
			VAR _LeftBorder = IF(_FA = "Aprendizaje" || _FA = "Desarrollo" || _FA = "Bienestar y Clima" || _FA = "Desempeño", "#F7931E", "#DCE5F2")
			VAR _Left = "<div style='position:absolute;left:34px;top:190px;width:592px;height:494px;background:" & _LeftBg & ";border:2px solid " & _LeftBorder & ";border-radius:10px;box-shadow:0 10px 28px rgba(11,28,53,.08);padding:22px;box-sizing:border-box;'>" & _LeftContent & "</div>"
			VAR _CApz = IF(_FA = "Aprendizaje", "<div style='background:#0B1C35;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(11,28,53,.18);'>", "<div style='background:#fff;border:1px solid #DCE5F2;border-radius:10px;padding:20px;'>")
			VAR _CDes = IF(_FA = "Desarrollo", "<div style='background:#1B487F;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(27,72,127,.18);'>", "<div style='background:#fff;border:1px solid #E8C99A;border-radius:10px;padding:20px;'>")
			VAR _CDep = IF(_FA = "Desempeño", "<div style='background:#1A3059;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(26,48,89,.18);'>", "<div style='background:#fff;border:1px solid #DCE5F2;border-radius:10px;padding:20px;'>")
			VAR _CByC = IF(_FA = "Bienestar y Clima", "<div style='background:#1A3059;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(26,48,89,.18);'>", "<div style='background:#fff;border:1px solid #DCE5F2;border-radius:10px;padding:20px;'>")
			VAR _Right =
			    "<div style='position:absolute;left:650px;top:190px;width:598px;height:494px;display:grid;grid-template-columns:1fr 1fr;gap:16px;'>" &
			    _CApz & "<div style='font-size:11px;color:#F7931E;font-weight:800;'>01</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Aprendizaje","color:#fff;","color:#1A3059;") & "'>Aprendizaje</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Aprendizaje","color:#cbd8e8;","color:#53657D;") & "'>MVP operativo con indicadores activos y lectura ejecutiva.</div><div style='margin-top:13px;height:4px;background:" & IF(_FA="Aprendizaje","#F7931E","#DCE5F2") & ";border-radius:4px;'></div><div style='margin-top:9px;display:grid;grid-template-columns:1fr 1fr;gap:6px;'><div style='background:#F7931E;color:#fff;border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Plan</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Cobertura</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Satisfacci&oacute;n</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Inducci&oacute;n</div><div style='grid-column:1 / span 2;background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Focos</div></div></div>" &
			    _CDep & "<div style='font-size:11px;color:" & IF(_FA="Desempeño","#F7931E","#1B487F") & ";font-weight:800;'>02</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Desempeño","color:#fff;","color:#1A3059;") & "'>Desempe&ntilde;o</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Desempeño","color:#d9e4f2;","color:#53657D;") & "'>Medici&oacute;n y seguimiento gerencial de resultados.</div><div style='margin-top:12px;display:grid;grid-template-columns:1fr 1fr;gap:6px;'><div style='background:#F7931E;color:#fff;border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Objetivos</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Desempeño","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Desempeño","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Competencias</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Desempeño","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Desempeño","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Curva niveles</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Desempeño","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Desempeño","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Detalle</div></div></div>" &
			    _CDes & "<div style='font-size:11px;color:#F7931E;font-weight:800;'>03</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Desarrollo","color:#fff;","color:#1A3059;") & "'>Desarrollo</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Desarrollo","color:#d9e4f2;","color:#53657D;") & "'>PDI activos. Avance: " & _PDIAvz & ".</div><div style='margin-top:12px;display:grid;grid-template-columns:1fr 1fr;gap:6px;'><div style='background:#F7931E;color:#fff;border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>PDI</div><div style='background:rgba(255,255,255,.08);color:" & IF(_FA="Desarrollo","#d9e4f2","#53657D") & ";border:1px dashed " & IF(_FA="Desarrollo","rgba(255,255,255,.28)","#B0C4D8") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Movilidad</div><div style='background:rgba(255,255,255,.08);color:" & IF(_FA="Desarrollo","#d9e4f2","#53657D") & ";border:1px dashed " & IF(_FA="Desarrollo","rgba(255,255,255,.28)","#B0C4D8") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Sucesi&oacute;n</div><div style='background:rgba(255,255,255,.08);color:" & IF(_FA="Desarrollo","#d9e4f2","#53657D") & ";border:1px dashed " & IF(_FA="Desarrollo","rgba(255,255,255,.28)","#B0C4D8") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Cargos cr&iacute;ticos</div></div></div>" &
			    _CByC & "<div style='font-size:11px;color:" & IF(_FA="Bienestar y Clima","#F7931E","#1B487F") & ";font-weight:800;'>04</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Bienestar y Clima","color:#fff;","color:#1A3059;") & "'>Bienestar y Clima</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Bienestar y Clima","color:#d9e4f2;","color:#53657D;") & "'>Retiro y Plan Bienestar activos. Clima y eNPS en roadmap.</div><div style='display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:12px;'><div style='background:#F7931E;color:#fff;border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Entrevista de Retiro</div><div style='background:#F7931E;color:#fff;border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Plan Bienestar</div><div style='background:rgba(255,255,255,.06);color:" & IF(_FA="Bienestar y Clima","#b8c8de","#9DB5CC") & ";border:1px dashed " & IF(_FA="Bienestar y Clima","rgba(255,255,255,.22)","#B0C4D8") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:700;text-align:center;'>Planes Clima Laboral</div><div style='background:rgba(255,255,255,.06);color:" & IF(_FA="Bienestar y Clima","#b8c8de","#9DB5CC") & ";border:1px dashed " & IF(_FA="Bienestar y Clima","rgba(255,255,255,.22)","#B0C4D8") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:700;text-align:center;'>eNPS Bienestar</div></div></div>" &
			    "</div>"
			VAR _FechaBase = MAXX(Dim_FechaActualizacion, Dim_FechaActualizacion[FechaActualizacion])
			VAR _FechaAct = IF(ISBLANK(_FechaBase), "Sin datos", FORMAT(_FechaBase, "DD MMM YYYY  h:mm AM/PM"))
			RETURN
			"<div style='width:1280px;height:720px;box-sizing:border-box;position:relative;background:#ffffff;font-family:Outfit,Segoe UI,Arial,sans-serif;color:#0B1C35;overflow:hidden;'>" &
			"<div style='height:88px;background:#0B1C35;color:#fff;padding:20px 34px;box-sizing:border-box;display:flex;justify-content:space-between;align-items:center;'>" &
			"<div><div style='font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#F7931E;font-weight:700;'>Dashboard Corporativo &middot; Grupo LEMCO</div><div style='font-size:25px;line-height:29px;font-weight:800;margin-top:5px;'>Inicio Corporativo</div></div>" &
			"<div style='text-align:right;'><div style='font-size:9px;color:#F7931E;font-weight:700;text-transform:uppercase;letter-spacing:1px;'>Actualizaci&oacute;n</div>" &
			"<div style='font-size:13px;font-weight:800;color:#FFFFFF;margin-top:3px;'>" & _FechaAct & "</div></div></div>" &
			"<div style='position:absolute;left:34px;top:104px;width:1214px;height:82px;background:#ffffff;border:1px solid #DCE5F2;border-radius:14px;box-sizing:border-box;box-shadow:0 10px 28px rgba(11,28,53,.07);overflow:hidden;'>" &
			"<div style='position:absolute;left:0;top:0;width:7px;height:82px;background:#F7931E;'></div>" &
			"<div style='position:absolute;left:22px;top:17px;width:178px;'><div style='font-size:10px;font-weight:900;color:#0B1C35;text-transform:uppercase;letter-spacing:1px;'>Contexto de an&aacute;lisis</div><div style='font-size:9px;color:#6B7D93;line-height:13px;margin-top:5px;'>Filtros activos para la lectura ejecutiva del home.</div></div>" &
			"<div style='position:absolute;left:214px;top:12px;width:244px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>A&ntilde;o</div></div>" &
			"<div style='position:absolute;left:466px;top:12px;width:244px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Mes</div></div>" &
			"<div style='position:absolute;left:718px;top:12px;width:244px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Empresa</div></div>" &
			"<div style='position:absolute;left:970px;top:12px;width:244px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Area</div></div>" &
			"</div>" &
			_Left &
			_Right &
			"</div>"
		displayFolder: 11 HTML Content
		lineageTag: 1cb83d75-76db-4da5-b3ad-558aa192e4d5

	measure 'HTML Inicio Corporativo Propuesta 2' =
			VAR _FA = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			VAR _Horas = IF(ISBLANK([Plan Horas Formacion]), "-", FORMAT([Plan Horas Formacion], "#,0"))
			VAR _Cobertura = IF(ISBLANK([% Cobertura]), "-", FORMAT([% Cobertura], "0.0%"))
			VAR _Satisfaccion = IF(ISBLANK([Encuesta Favorabilidad]), "-", FORMAT([Encuesta Favorabilidad], "0.0%"))
			VAR _Entrenamiento = IF(ISBLANK([Induccion Porcentaje Entrenamiento Neto]), "-", FORMAT([Induccion Porcentaje Entrenamiento Neto], "0.0%"))
			VAR _IndiceAprendizaje = IF(ISBLANK([KPI Indice Aprendizaje]), "-", FORMAT([KPI Indice Aprendizaje], "0.0%"))
			VAR _IndiceDesarrollo = IF(ISBLANK([KPI Indice Desarrollo]), "-", FORMAT([KPI Indice Desarrollo], "0.0%"))
			VAR _FrenteTitulo = SWITCH(_FA, "Desempeño", "Desempe&ntilde;o", "Bienestar y Clima", "Bienestar y Clima", "Desarrollo", "Desarrollo", "Aprendizaje")
			VAR _FrenteEstado = SWITCH(_FA, "Aprendizaje", "Frente activo", "Desarrollo", "En construcci&oacute;n", "Bienestar y Clima", "Frente iniciado", "Desempeño", "Pr&oacute;xima fase", "Frente activo")
			VAR _FrenteDesc = SWITCH(_FA, "Aprendizaje", "Indicadores de formaci&oacute;n, cobertura, satisfacci&oacute;n y entrenamiento.", "Desarrollo", "Seguimiento de PDI, avance, acompa&ntilde;amientos y alertas.", "Bienestar y Clima", "Entrevista de Retiro, clima laboral, eNPS y plan de bienestar.", "Desempeño", "Espacio reservado para evaluaci&oacute;n y seguimiento gerencial.", "Indicadores corporativos del frente seleccionado.")
			VAR _ValorPrincipal = SWITCH(_FA, "Aprendizaje", _IndiceAprendizaje, "Desarrollo", _IndiceDesarrollo, "Bienestar y Clima", "Activo", "Desempeño", "Roadmap", _IndiceAprendizaje)
			VAR _ValorSecundario = SWITCH(_FA, "Aprendizaje", _Entrenamiento, "Desarrollo", _IndiceDesarrollo, "Bienestar y Clima", "Retiro", "Desempeño", "2026", _Entrenamiento)
			RETURN
			"<div style='width:1280px;height:720px;box-sizing:border-box;position:relative;background:#F4F7FB;font-family:Outfit,Segoe UI,Arial,sans-serif;color:#0B1C35;overflow:hidden;'>" &
			"<div style='position:absolute;left:0;top:0;width:1280px;height:220px;background:linear-gradient(135deg,#000032 0%,#1A3059 54%,#1B487F 100%);color:#ffffff;'>" &
			"<div style='position:absolute;left:42px;top:26px;width:600px;'><div style='font-size:12px;color:#F7931E;letter-spacing:2px;text-transform:uppercase;font-weight:800;'>Grupo LEMCO | People Analytics</div><div style='font-size:35px;line-height:41px;font-weight:850;margin-top:8px;'>Dashboard Corporativo de Desarrollo Organizacional</div><div style='font-size:14px;line-height:20px;color:#dbe6f5;margin-top:12px;width:86%;'>Portada ejecutiva para monitorear frentes de gesti&oacute;n humana con lectura r&aacute;pida, comparaci&oacute;n y priorizaci&oacute;n.</div></div>" &
			"<div style='position:absolute;right:42px;top:34px;width:320px;height:138px;background:rgba(255,255,255,.11);border:1px solid rgba(255,255,255,.25);border-radius:14px;padding:18px;box-sizing:border-box;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>" & _FrenteEstado & "</div><div style='font-size:28px;font-weight:850;margin-top:4px;'>" & _FrenteTitulo & "</div><div style='display:flex;gap:10px;margin-top:18px;'><div style='flex:1;'><div style='font-size:10px;color:#bfd0e4;'>Indicador</div><div style='font-size:22px;font-weight:800;'>" & _ValorPrincipal & "</div></div><div style='flex:1;'><div style='font-size:10px;color:#bfd0e4;'>Estado</div><div style='font-size:22px;font-weight:800;'>" & _ValorSecundario & "</div></div></div></div></div>" &
			"<div style='position:absolute;left:36px;top:136px;width:1212px;height:92px;background:#ffffff;border-radius:14px;box-shadow:0 14px 38px rgba(11,28,53,.16);border:1px solid #DCE5F2;'><div style='position:absolute;left:18px;top:12px;font-size:12px;font-weight:800;color:#1A3059;text-transform:uppercase;letter-spacing:.8px;'>Explorar por</div></div>" &
			"<div style='position:absolute;left:42px;top:256px;width:1210px;height:164px;display:grid;grid-template-columns:1.2fr .8fr .8fr .8fr;gap:16px;'>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:22px;box-shadow:0 8px 24px rgba(11,28,53,.07);'><div style='font-size:13px;color:#F7931E;font-weight:800;'>" & _FrenteTitulo & "</div><div style='font-size:25px;font-weight:850;margin-top:4px;'>" & SWITCH(_FA, "Aprendizaje", "Gesti&oacute;n activa del MVP", "Desarrollo", "Desarrollo en construcci&oacute;n", "Bienestar y Clima", "Escucha y clima iniciado", "Desempeño", "Roadmap de desempe&ntilde;o", "Gesti&oacute;n corporativa") & "</div><div style='font-size:13px;color:#53657D;line-height:18px;margin-top:8px;'>" & _FrenteDesc & "</div><div style='height:7px;background:#E8EEF6;border-radius:8px;margin-top:22px;'><div style='width:" & SWITCH(_FA, "Aprendizaje", "78%", "Desarrollo", "42%", "Bienestar y Clima", "35%", "Desempeño", "18%", "78%") & ";height:7px;background:#F7931E;border-radius:8px;'></div></div></div>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:20px;'><div style='font-size:12px;color:#53657D;'>Horas</div><div style='font-size:34px;font-weight:850;color:#1B487F;'>" & _Horas & "</div><div style='font-size:12px;color:#53657D;margin-top:8px;'>Formaci&oacute;n planificada y ejecutada.</div></div>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:20px;'><div style='font-size:12px;color:#53657D;'>Cobertura</div><div style='font-size:34px;font-weight:850;color:#1B487F;'>" & _Cobertura & "</div><div style='font-size:12px;color:#53657D;margin-top:8px;'>Asistencia frente al p&uacute;blico objetivo.</div></div>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:20px;'><div style='font-size:12px;color:#53657D;'>Satisfacci&oacute;n</div><div style='font-size:34px;font-weight:850;color:#1B487F;'>" & _Satisfaccion & "</div><div style='font-size:12px;color:#53657D;margin-top:8px;'>Favorabilidad de las respuestas.</div></div></div>" &
			"<div style='position:absolute;left:42px;top:448px;width:1210px;height:164px;display:grid;grid-template-columns:repeat(4,1fr);gap:16px;'>" &
			"<div style='background:" & IF(_FA = "Aprendizaje", "#0B1C35", "#ffffff") & ";color:" & IF(_FA = "Aprendizaje", "#ffffff", "#0B1C35") & ";border:" & IF(_FA = "Aprendizaje", "2px solid #F7931E", "1px solid #DCE5F2") & ";border-radius:16px;padding:20px;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>" & IF(_FA = "Aprendizaje", "Activo", "MVP") & "</div><div style='font-size:23px;font-weight:850;margin-top:9px;'>Aprendizaje</div><div style='font-size:12px;color:" & IF(_FA = "Aprendizaje", "#cbd8e8", "#53657D") & ";line-height:17px;margin-top:8px;'>Entrenamiento neto: " & _Entrenamiento & ".</div></div>" &
			"<div style='background:" & IF(_FA = "Desempeño", "#1A3059", "#ffffff") & ";color:" & IF(_FA = "Desempeño", "#ffffff", "#0B1C35") & ";border:" & IF(_FA = "Desempeño", "2px solid #F7931E", "1px solid #DCE5F2") & ";border-radius:16px;padding:20px;'><div style='font-size:12px;color:" & IF(_FA = "Desempeño", "#F7931E", "#1B487F") & ";font-weight:800;'>Pr&oacute;xima fase</div><div style='font-size:23px;font-weight:850;margin-top:9px;'>Desempe&ntilde;o</div><div style='font-size:12px;color:" & IF(_FA = "Desempeño", "#d9e4f2", "#53657D") & ";line-height:17px;margin-top:8px;'>Espacio reservado para evaluaci&oacute;n y seguimiento.</div></div>" &
			"<div style='background:" & IF(_FA = "Desarrollo", "#1B487F", "#ffffff") & ";color:" & IF(_FA = "Desarrollo", "#ffffff", "#0B1C35") & ";border:2px solid #F7931E;border-radius:16px;padding:20px;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>En construcci&oacute;n</div><div style='font-size:23px;font-weight:850;margin-top:9px;'>Desarrollo</div><div style='font-size:12px;color:" & IF(_FA = "Desarrollo", "#d9e4f2", "#53657D") & ";line-height:17px;margin-top:8px;'>PDI y acompa&ntilde;amientos en seguimiento.</div></div>" &
			"<div style='background:" & IF(_FA = "Bienestar y Clima", "#1A3059", "#ffffff") & ";color:" & IF(_FA = "Bienestar y Clima", "#ffffff", "#0B1C35") & ";border:" & IF(_FA = "Bienestar y Clima", "2px solid #F7931E", "1px solid #DCE5F2") & ";border-radius:16px;padding:18px;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>Frente iniciado</div><div style='font-size:23px;font-weight:850;margin-top:7px;'>Bienestar y Clima</div><div style='display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px;font-size:10px;color:" & IF(_FA = "Bienestar y Clima", "#ffffff", "#1A3059") & ";'><div style='border-left:3px solid #F7931E;background:" & IF(_FA = "Bienestar y Clima", "rgba(255,255,255,.10)", "#F7F9FC") & ";border-radius:7px;padding:7px;'>Entrevista de Retiro</div><div style='background:" & IF(_FA = "Bienestar y Clima", "rgba(255,255,255,.10)", "#F7F9FC") & ";border-radius:7px;padding:7px;'>Planes Clima Laboral</div><div style='background:" & IF(_FA = "Bienestar y Clima", "rgba(255,255,255,.10)", "#F7F9FC") & ";border-radius:7px;padding:7px;'>eNPS Bienestar</div><div style='background:" & IF(_FA = "Bienestar y Clima", "rgba(255,255,255,.10)", "#F7F9FC") & ";border-radius:7px;padding:7px;'>Plan Bienestar</div></div></div></div>" &
			"<div style='position:absolute;left:42px;bottom:26px;width:1210px;height:42px;background:#ffffff;border:1px solid #E1E8F2;border-radius:12px;display:flex;align-items:center;padding:0 18px;box-sizing:border-box;color:#53657D;font-size:12px;'><span style='display:inline-block;width:8px;height:8px;background:#F7931E;border-radius:50%;margin-right:10px;'></span>Lectura sugerida: validar cobertura y satisfacci&oacute;n del frente activo antes de avanzar a focos de gesti&oacute;n.</div></div>"
		displayFolder: 11 HTML Content
		lineageTag: b0132c21-8cd4-4669-8432-92927a52be84

	measure 'HTML Inicio Corporativo Propuesta 3' =
			VAR _FA = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			VAR _Horas = IF(ISBLANK([Plan Horas Formacion]), "-", FORMAT([Plan Horas Formacion], "#,0"))
			VAR _Cobertura = IF(ISBLANK([% Cobertura]), "-", FORMAT([% Cobertura], "0.0%"))
			VAR _Satisfaccion = IF(ISBLANK([Encuesta Favorabilidad]), "-", FORMAT([Encuesta Favorabilidad], "0.0%"))
			VAR _Onboarding = IF(ISBLANK([Induccion Porcentaje Cumplimiento]), "-", FORMAT([Induccion Porcentaje Cumplimiento], "0.0%"))
			VAR _Entrenamiento = IF(ISBLANK([Induccion Porcentaje Entrenamiento Neto]), "-", FORMAT([Induccion Porcentaje Entrenamiento Neto], "0.0%"))
			VAR _PDI = IF(ISBLANK([PDI Total]), "-", FORMAT([PDI Total], "#,0"))
			VAR _AlertasPDI = IF(ISBLANK([PDI Alertas Criticas]), "-", FORMAT([PDI Alertas Criticas], "#,0"))
			VAR _FrenteTitulo = SWITCH(_FA, "Desempeño", "Desempe&ntilde;o", "Bienestar y Clima", "Bienestar y Clima", "Desarrollo", "Desarrollo", "Aprendizaje")
			VAR _FrenteDesc = SWITCH(_FA, "Aprendizaje", "Lectura integrada de formaci&oacute;n, cobertura, satisfacci&oacute;n, onboarding y entrenamiento.", "Desarrollo", "Planes de Desarrollo Individual, avance, acompa&ntilde;amientos y alertas.", "Bienestar y Clima", "Entrevista de Retiro activa, clima laboral, eNPS y plan de bienestar.", "Desempeño", "Evaluaci&oacute;n de desempe&ntilde;o, metas y seguimiento gerencial.", "Lectura integrada del frente seleccionado.")
			VAR _EstadoActual = SWITCH(_FA, "Aprendizaje", "Aprendizaje MVP", "Desarrollo", "Desarrollo en construcci&oacute;n", "Bienestar y Clima", "Bienestar iniciado", "Desempeño", "Desempe&ntilde;o roadmap", "Aprendizaje MVP")
			VAR _FocoTitulo = SWITCH(_FA, "Aprendizaje", "Priorizar brechas del frente activo", "Desarrollo", "Acelerar seguimiento PDI", "Bienestar y Clima", "Escuchar motivos de retiro y clima", "Desempeño", "Preparar modelo de seguimiento", "Priorizar brechas del frente activo")
			VAR _FocoDetalle = SWITCH(_FA, "Aprendizaje", "Entrenamiento neto " & _Entrenamiento & ", cobertura " & _Cobertura & " y satisfacci&oacute;n " & _Satisfaccion & " deben orientar la conversaci&oacute;n gerencial.", "Desarrollo", _PDI & " PDI activos y " & _AlertasPDI & " alertas requieren lectura priorizada por &aacute;rea, motivo y jefe.", "Bienestar y Clima", "La entrevista de retiro debe alimentar oportunidades de mejora, clima laboral, eNPS y plan de bienestar.", "Desempeño", "Este frente se conserva como roadmap para la siguiente fase de medici&oacute;n y seguimiento.", "Revisar indicadores del frente seleccionado.")
			RETURN
			"<div style='width:1280px;height:720px;box-sizing:border-box;position:relative;background:#ffffff;font-family:Outfit,Segoe UI,Arial,sans-serif;color:#0B1C35;overflow:hidden;'>" &
			"<div style='position:absolute;left:0;top:0;width:250px;height:720px;background:#0B1C35;color:#ffffff;padding:32px 24px;box-sizing:border-box;'><div style='font-size:11px;color:#F7931E;letter-spacing:1.7px;text-transform:uppercase;font-weight:800;'>Home estrategico</div><div style='font-size:28px;line-height:32px;font-weight:850;margin-top:12px;'>Mapa de frentes</div><div style='font-size:13px;color:#c8d6e8;line-height:19px;margin-top:16px;'>Una vista madre para navegar la evoluci&oacute;n del Dashboard Corporativo.</div><div style='position:absolute;bottom:34px;left:24px;right:24px;border-top:1px solid rgba(255,255,255,.18);padding-top:18px;font-size:12px;color:#c8d6e8;'>Estado actual<br><span style='color:#F7931E;font-size:20px;font-weight:850;'>" & _EstadoActual & "</span></div></div>" &
			"<div style='position:absolute;left:276px;top:26px;width:956px;height:76px;background:#F7F9FC;border:1px solid #DCE5F2;border-radius:14px;box-sizing:border-box;'><div style='position:absolute;left:20px;top:10px;font-size:12px;font-weight:800;color:#1A3059;text-transform:uppercase;letter-spacing:.8px;'>Filtros para lectura corporativa</div></div>" &
			"<div style='position:absolute;left:276px;top:126px;width:956px;height:168px;display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:16px;'>" &
			"<div style='background:#1A3059;color:#ffffff;border-radius:14px;padding:22px;box-shadow:0 12px 30px rgba(11,28,53,.14);'><div style='font-size:12px;color:#F7931E;font-weight:800;'>" & SWITCH(_FA, "Aprendizaje", "Frente activo", "Desarrollo", "En construcci&oacute;n", "Bienestar y Clima", "Frente iniciado", "Desempeño", "Pr&oacute;xima fase", "Frente activo") & "</div><div style='font-size:30px;font-weight:850;margin-top:6px;'>" & _FrenteTitulo & "</div><div style='font-size:12px;color:#d9e4f2;line-height:18px;margin-top:8px;'>" & _FrenteDesc & "</div></div>" &
			"<div style='background:#ffffff;border:1px solid #DCE5F2;border-radius:14px;padding:20px;'><div style='font-size:12px;color:#53657D;'>Horas de formaci&oacute;n</div><div style='font-size:34px;font-weight:850;color:#1B487F;margin-top:8px;'>" & _Horas & "</div><div style='height:5px;background:#F7931E;border-radius:8px;margin-top:18px;width:72%;'></div></div>" &
			"<div style='background:#ffffff;border:1px solid #DCE5F2;border-radius:14px;padding:20px;'><div style='font-size:12px;color:#53657D;'>Cobertura / satisfacci&oacute;n</div><div style='display:flex;gap:20px;margin-top:14px;'><div><div style='font-size:27px;font-weight:850;color:#1B487F;'>" & _Cobertura & "</div><div style='font-size:11px;color:#53657D;'>Cobertura</div></div><div><div style='font-size:27px;font-weight:850;color:#1B487F;'>" & _Satisfaccion & "</div><div style='font-size:11px;color:#53657D;'>Satisfacci&oacute;n</div></div></div></div></div>" &
			"<div style='position:absolute;left:276px;top:320px;width:956px;height:268px;display:grid;grid-template-columns:1.05fr 1fr;gap:18px;'>" &
			"<div style='background:#ffffff;border:1px solid #E1E8F2;border-radius:14px;padding:24px;box-shadow:0 10px 28px rgba(11,28,53,.06);'><div style='font-size:12px;color:#F7931E;text-transform:uppercase;font-weight:800;letter-spacing:1px;'>Ruta corporativa</div><div style='display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px;'>" &
			"<div style='background:" & IF(_FA = "Aprendizaje", "#0B1C35", "#F7F9FC") & ";color:" & IF(_FA = "Aprendizaje", "#ffffff", "#1A3059") & ";border:" & IF(_FA = "Aprendizaje", "2px solid #F7931E", "1px solid #DCE5F2") & ";border-radius:12px;padding:18px;'><div style='font-size:20px;font-weight:850;'>Aprendizaje</div><div style='font-size:11px;color:" & IF(_FA = "Aprendizaje", "#cbd8e8", "#53657D") & ";margin-top:7px;'>Activo | " & _Onboarding & " onboarding</div></div>" &
			"<div style='background:" & IF(_FA = "Desempeño", "#1A3059", "#F7F9FC") & ";color:" & IF(_FA = "Desempeño", "#ffffff", "#1A3059") & ";border:" & IF(_FA = "Desempeño", "2px solid #F7931E", "1px solid #DCE5F2") & ";border-radius:12px;padding:18px;'><div style='font-size:20px;font-weight:850;'>Desempe&ntilde;o</div><div style='font-size:11px;color:" & IF(_FA = "Desempeño", "#d9e4f2", "#53657D") & ";margin-top:7px;'>Pr&oacute;xima fase</div></div>" &
			"<div style='background:" & IF(_FA = "Desarrollo", "#1B487F", "#FFF7EE") & ";color:" & IF(_FA = "Desarrollo", "#ffffff", "#1A3059") & ";border:2px solid #F7931E;border-radius:12px;padding:18px;'><div style='font-size:20px;font-weight:850;'>Desarrollo</div><div style='font-size:11px;color:" & IF(_FA = "Desarrollo", "#d9e4f2", "#9D5600") & ";margin-top:7px;'>" & _PDI & " PDI | " & _AlertasPDI & " alertas</div></div>" &
			"<div style='background:" & IF(_FA = "Bienestar y Clima", "#1A3059", "#F7F9FC") & ";color:" & IF(_FA = "Bienestar y Clima", "#ffffff", "#1A3059") & ";border:" & IF(_FA = "Bienestar y Clima", "2px solid #F7931E", "1px solid #DCE5F2") & ";border-radius:12px;padding:16px;'><div style='font-size:20px;font-weight:850;'>Bienestar y Clima</div><div style='font-size:11px;color:#F7931E;font-weight:800;margin-top:7px;'>Entrevista de Retiro activa</div><div style='font-size:10px;color:" & IF(_FA = "Bienestar y Clima", "#d9e4f2", "#53657D") & ";line-height:14px;margin-top:8px;'>Planes Clima Laboral &bull; eNPS Bienestar &bull; Plan Bienestar</div></div></div></div>" &
			"<div style='background:#0B1C35;color:#ffffff;border-radius:14px;padding:24px;'><div style='font-size:12px;color:#F7931E;text-transform:uppercase;font-weight:800;letter-spacing:1px;'>Foco ejecutivo</div><div style='font-size:25px;line-height:30px;font-weight:850;margin-top:12px;'>" & _FocoTitulo & "</div><div style='font-size:13px;line-height:19px;color:#d9e4f2;margin-top:12px;'>" & _FocoDetalle & "</div><div style='margin-top:24px;background:#F7931E;color:#0B1C35;border-radius:22px;padding:9px 14px;display:inline-block;font-size:12px;font-weight:850;'>Ir a decisiones del bloque</div></div></div>" &
			"<div style='position:absolute;left:276px;top:616px;width:956px;height:58px;background:#F7F9FC;border:1px solid #DCE5F2;border-radius:14px;display:flex;align-items:center;gap:18px;padding:0 22px;box-sizing:border-box;'><div style='font-size:12px;color:#53657D;'>Escalabilidad futura</div><div style='height:26px;width:1px;background:#DCE5F2;'></div><div style='font-size:12px;color:#1A3059;font-weight:750;'>Los frentes pendientes se mantienen visibles como roadmap para evitar una portada aislada del programa corporativo.</div></div></div>"
		displayFolder: 11 HTML Content
		lineageTag: c9f46c0b-dd6c-4f12-bfec-4558f16abf2f

	measure 'EntrevistaRetiro Total' = COUNTROWS('Fct_EntrevistaRetiro_Unificada')
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: f807b926-f383-42b3-938f-8342e825ccef

	measure 'EntrevistaRetiro Total Validas' = CALCULATE([EntrevistaRetiro Total], 'Fct_EntrevistaRetiro_Unificada'[RegistroValido_Flag] = 1)
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 8a939516-4eec-4449-9e88-47861c581f2e

	measure 'EntrevistaRetiro Total No Validas' = CALCULATE([EntrevistaRetiro Total], 'Fct_EntrevistaRetiro_Unificada'[RegistroValido_Flag] = 0)
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 4b22d283-ed26-42b7-87fe-a0dc6dd3b7bd

	measure 'EntrevistaRetiro Porcentaje Validas' = DIVIDE([EntrevistaRetiro Total Validas], [EntrevistaRetiro Total], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 0bbfbc38-cfaa-47ba-8032-b1b0451c79e4

	measure 'EntrevistaRetiro Total Voluntarios' = CALCULATE([EntrevistaRetiro Total Validas], 'Dim_TipoRetiro'[TipoRetiro_Key] = "VOLUNTARIO")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: ce3fc002-75f7-4c88-9fa7-95a9bd46436f

	measure 'EntrevistaRetiro Total Involuntarios' = CALCULATE([EntrevistaRetiro Total Validas], 'Dim_TipoRetiro'[TipoRetiro_Key] = "INVOLUNTARIO")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 46e0a13f-bc98-4df9-a82c-96381f2b72bc

	measure 'EntrevistaRetiro Porcentaje Voluntarios' = DIVIDE([EntrevistaRetiro Total Voluntarios], [EntrevistaRetiro Total Validas], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 4b8a6985-b643-4ecd-a112-33f8cf286f2a

	measure 'EntrevistaRetiro Porcentaje Involuntarios' = DIVIDE([EntrevistaRetiro Total Involuntarios], [EntrevistaRetiro Total Validas], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 084eb376-0877-4fda-998a-b71a897fddda

	measure 'EntrevistaRetiro Total Fuentes' = DISTINCTCOUNT('Dim_FuenteEntrevistaRetiro'[FuenteEntrevista_Key])
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 23a34a57-4d5d-4154-bff4-be8b372bf40f

	measure 'EntrevistaRetiro Motivo Principal' =
			VAR _Tabla =
			    TOPN(
			        1,
			        ADDCOLUMNS(
			            ALLSELECTED('Dim_MotivoRetiro'[Motivo_Retiro]),
			            "_Total", [EntrevistaRetiro Total Validas]
			        ),
			        [_Total], DESC,
			        'Dim_MotivoRetiro'[Motivo_Retiro], ASC
			    )
			RETURN
			    COALESCE(CONCATENATEX(_Tabla, 'Dim_MotivoRetiro'[Motivo_Retiro], ", "), "Sin datos")
		displayFolder: 13 Entrevista Retiro
		lineageTag: b053a6f4-7ac9-4eb4-a1b8-c6ae55aceb5f

	measure 'EntrevistaRetiro Total Motivos Distintos' = DISTINCTCOUNT('Dim_MotivoRetiro'[MotivoRetiro_Key])
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 2dcd81c3-e651-4b14-9713-3bd0643b5604

	measure 'EntrevistaRetiro Participacion Motivo' = DIVIDE([EntrevistaRetiro Total Validas], CALCULATE([EntrevistaRetiro Total Validas], ALLSELECTED('Dim_MotivoRetiro'[Motivo_Retiro])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 0773a6dd-436f-4de5-9e6a-cc057fb0e1bf

	measure 'EntrevistaRetiro Participacion UnidadNegocio' = DIVIDE([EntrevistaRetiro Total Validas], CALCULATE([EntrevistaRetiro Total Validas], ALLSELECTED('Dim_UnidadNegocioRetiro'[Unidad_Negocio])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: a8690235-fd4a-4e27-9321-7b0fff4175ea

	measure 'EntrevistaRetiro UnidadNegocio Top' =
			VAR _Tabla =
			    TOPN(
			        1,
			        ADDCOLUMNS(
			            ALLSELECTED('Dim_UnidadNegocioRetiro'[Unidad_Negocio]),
			            "_Total", [EntrevistaRetiro Total Validas]
			        ),
			        [_Total], DESC,
			        'Dim_UnidadNegocioRetiro'[Unidad_Negocio], ASC
			    )
			RETURN
			    COALESCE(CONCATENATEX(_Tabla, 'Dim_UnidadNegocioRetiro'[Unidad_Negocio], ", "), "Sin datos")
		displayFolder: 13 Entrevista Retiro
		lineageTag: 8fe1e468-8ed6-4add-9607-40b353ed2d01

	measure 'EntrevistaRetiro Causas Prevenibles' = CALCULATE([EntrevistaRetiro Total Validas], 'Fct_EntrevistaRetiro_Unificada'[CausaPrevenible_Key] = "SI")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 9ce75590-6ec4-420f-880c-ed7f6f627042

	measure 'EntrevistaRetiro Porcentaje Causas Prevenibles' = DIVIDE([EntrevistaRetiro Causas Prevenibles], [EntrevistaRetiro Total Validas], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 340abcd8-a6e6-4b5d-9996-b6b70dedbf99

	measure 'EntrevistaRetiro Variacion Mensual' = [EntrevistaRetiro Total Validas] - CALCULATE([EntrevistaRetiro Total Validas], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 8e8763df-25ca-424c-96c2-a4052a408be1

	measure 'EntrevistaRetiro Variacion Mensual Porcentaje' = DIVIDE([EntrevistaRetiro Variacion Mensual], CALCULATE([EntrevistaRetiro Total Validas], DATEADD('Dim_Calendario'[Date], -1, MONTH)), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 6ecb0227-0552-4d0c-85aa-f4e63bb78d9d

	measure 'EntrevistaRetiro Registros Requieren Plan' = CALCULATE([EntrevistaRetiro Total Validas], 'Fct_EntrevistaRetiro_Unificada'[RequierePlanAccion] = "Si")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 2252ede9-0a9f-4428-ba44-f1e21971f379

	measure 'HTML Shell BC01 Entrevista de Retiro' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Entrevista de Retiro</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Motivos de salida, oportunidades de mejora y se&ntilde;ales para Gestion Humana.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Bienestar y Clima</div>" &
				"<div style='position:absolute;left:36px;top:108px;width:1208px;height:120px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 4px 12px rgba(11,28,53,0.05);'></div>" &
				"<div style='position:absolute;left:36px;top:108px;width:4px;height:120px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:32px;top:228px;width:1216px;height:446px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 7c2750e7-b88c-412b-ae31-489e5fab52af

	measure 'HTML Shell BC01 Resumen Ejecutivo Bienestar y Clima' =
			VAR _ERet    = IF(ISBLANK([EntrevistaRetiro Total Validas]),                  "-", FORMAT([EntrevistaRetiro Total Validas], "#,0"))
			VAR _EVolPct = IF(ISBLANK([EntrevistaRetiro Porcentaje Voluntarios]),         "-", FORMAT([EntrevistaRetiro Porcentaje Voluntarios], "0.0%"))
			VAR _EPrev   = IF(ISBLANK([EntrevistaRetiro Porcentaje Causas Prevenibles]),  "-", FORMAT([EntrevistaRetiro Porcentaje Causas Prevenibles], "0.0%"))
			VAR _EMotivo = IF(ISBLANK([EntrevistaRetiro Motivo Principal]),               "N/D", [EntrevistaRetiro Motivo Principal])
			VAR _EUnidad = IF(ISBLANK([EntrevistaRetiro UnidadNegocio Top]),              "N/D", [EntrevistaRetiro UnidadNegocio Top])
			VAR _BProg   = IF(ISBLANK([Bienestar Programaciones Registradas Ejecucion]), "-", FORMAT([Bienestar Programaciones Registradas Ejecucion], "#,0"))
			VAR _BEjec   = IF(ISBLANK([Bienestar Ejecutadas]),                           "-", FORMAT([Bienestar Ejecutadas], "#,0"))
			VAR _BCump   = IF(ISBLANK([Bienestar Cumplimiento al Corte %]),              "-", FORMAT([Bienestar Cumplimiento al Corte %], "0.0%"))
			VAR _BAvance = IF(ISBLANK([Bienestar Avance Anual %]),                       "-", FORMAT([Bienestar Avance Anual %], "0.0%"))
			VAR _BPend   = IF(ISBLANK([Bienestar Pendientes Futuros]),                   "-", FORMAT([Bienestar Pendientes Futuros], "#,0"))
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:22px;color:#F7931E;font-size:11px;font-weight:800;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:44px;color:#FFFFFF;font-size:24px;font-weight:800;'>Bienestar y Clima</div>" &
				"<div style='position:absolute;left:48px;top:75px;color:#D8E4F2;font-size:11px;'>Resumen ejecutivo del frente: Entrevista de Retiro y Plan de Bienestar.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 18px;font-size:11px;font-weight:800;'>Frente iniciado</div>" &
				"<div style='position:absolute;left:0;top:100px;width:1280px;height:76px;background:#FFFFFF;border-bottom:1px solid #DCE5F2;'></div>" &
				"<div style='position:absolute;left:32px;top:188px;width:580px;height:268px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:12px;padding:16px 18px;box-sizing:border-box;'>" &
				"<div style='font-size:11px;color:#F7931E;font-weight:800;letter-spacing:1.4px;text-transform:uppercase;'>Entrevista de Retiro</div>" &
				"<div style='display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px;margin-top:10px;'>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:9px 11px;border-left:3px solid #003A70;'><div style='font-size:9px;color:#53657D;'>Entrevistas validas</div><div style='font-size:20px;font-weight:800;color:#0B1C35;margin-top:3px;'>" & _ERet & "</div></div>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:9px 11px;border-left:3px solid #1B487F;'><div style='font-size:9px;color:#53657D;'>Retiros voluntarios</div><div style='font-size:20px;font-weight:800;color:#1B487F;margin-top:3px;'>" & _EVolPct & "</div></div>" &
				"<div style='background:#FFF8F0;border-radius:7px;padding:9px 11px;border-left:3px solid #F7931E;'><div style='font-size:9px;color:#53657D;'>Causas prevenibles</div><div style='font-size:20px;font-weight:800;color:#F7931E;margin-top:3px;'>" & _EPrev & "</div></div>" &
				"</div>" &
				"<div style='display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:7px;'>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:9px 11px;'><div style='font-size:9px;color:#53657D;'>Motivo principal</div><div style='font-size:12px;font-weight:700;color:#0B1C35;margin-top:4px;line-height:14px;'>" & _EMotivo & "</div></div>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:9px 11px;'><div style='font-size:9px;color:#53657D;'>Unidad con mas retiros</div><div style='font-size:12px;font-weight:700;color:#0B1C35;margin-top:4px;line-height:14px;'>" & _EUnidad & "</div></div>" &
				"</div>" &
				"</div>" &
				"<div style='position:absolute;left:644px;top:188px;width:604px;height:268px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:12px;padding:16px 18px;box-sizing:border-box;'>" &
				"<div style='font-size:11px;color:#F7931E;font-weight:800;letter-spacing:1.4px;text-transform:uppercase;'>Plan de Bienestar</div>" &
				"<div style='display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px;'>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:8px 11px;border-left:3px solid #003A70;'><div style='font-size:9px;color:#53657D;'>Programaciones vigentes</div><div style='font-size:18px;font-weight:800;color:#0B1C35;margin-top:3px;'>" & _BProg & "</div></div>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:8px 11px;border-left:3px solid #1B487F;'><div style='font-size:9px;color:#53657D;'>Actividades ejecutadas</div><div style='font-size:18px;font-weight:800;color:#1B487F;margin-top:3px;'>" & _BEjec & "</div></div>" &
				"<div style='background:#FFF8F0;border-radius:7px;padding:8px 11px;border-left:3px solid #F7931E;'><div style='font-size:9px;color:#53657D;'>Cumplimiento al corte</div><div style='font-size:18px;font-weight:800;color:#F7931E;margin-top:3px;'>" & _BCump & "</div></div>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:8px 11px;border-left:3px solid #1B487F;'><div style='font-size:9px;color:#53657D;'>Avance anual</div><div style='font-size:18px;font-weight:800;color:#1B487F;margin-top:3px;'>" & _BAvance & "</div></div>" &
				"</div>" &
				"<div style='background:#F7F9FC;border-radius:7px;padding:8px 11px;margin-top:7px;border-left:3px solid #53657D;'><div style='font-size:9px;color:#53657D;'>Pendientes futuros</div><div style='font-size:18px;font-weight:800;color:#53657D;margin-top:3px;'>" & _BPend & "</div></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:464px;width:1216px;height:244px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:12px;padding:22px 28px;box-sizing:border-box;'>" &
				"<div style='font-size:11px;color:#F7931E;font-weight:800;letter-spacing:1.4px;text-transform:uppercase;'>Proximos modulos</div>" &
				"<div style='font-size:12px;color:#53657D;margin-top:6px;'>Componentes en roadmap para el frente Bienestar y Clima.</div>" &
				"<div style='display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px;'>" &
				"<div style='border:1px dashed #DCE5F2;border-radius:10px;padding:20px 22px;'><div style='font-size:9px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:#53657D;'>Proxima fase</div><div style='font-size:18px;font-weight:800;color:#1A3059;margin-top:8px;'>Planes Clima Laboral</div><div style='font-size:11px;color:#8096B0;margin-top:6px;line-height:15px;'>Medicion y seguimiento del clima organizacional por unidad y dimension.</div></div>" &
				"<div style='border:1px dashed #DCE5F2;border-radius:10px;padding:20px 22px;'><div style='font-size:9px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:#53657D;'>Proxima fase</div><div style='font-size:18px;font-weight:800;color:#1A3059;margin-top:8px;'>eNPS Bienestar</div><div style='font-size:11px;color:#8096B0;margin-top:6px;line-height:15px;'>Net Promoter Score de empleados para seguimiento de bienestar organizacional.</div></div>" &
				"</div>" &
				"</div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 92537134-87d1-4c44-b4bb-14e8eb0b754d

	measure 'Home Pagina Resumen Frente' =
			VAR _Frente = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			RETURN
			    SWITCH(
			        _Frente,
			        "Aprendizaje", "A01 Resumen Ejecutivo Aprendizaje",
			        "Desarrollo", "D01 Resumen Ejecutivo Desarrollo",
			        "Bienestar y Clima", "BC01 Resumen Ejecutivo Bienestar y Clima",
			        "Desempeño", "DS01_Resumen_Desempeno",
			        "A01 Resumen Ejecutivo Aprendizaje"
			    )
		displayFolder: 00 Home Corporativo
		lineageTag: 1c4f494b-a83d-4be8-a952-9f52118d950e

	measure 'Home Tooltip Resumen Frente' =
			VAR _Frente = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			RETURN
			    "Ir a " & [Home Pagina Resumen Frente]
		displayFolder: 00 Home Corporativo
		lineageTag: 2771f7ad-7ef2-45bd-9881-9ef6aaf7f9e1

	measure 'HTML Shell A01 Resumen Ejecutivo Aprendizaje' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Resumen Ejecutivo Aprendizaje</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Lectura integral de plan, cobertura, satisfaccion, onboarding y focos de gestion.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Aprendizaje</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros activos para la lectura ejecutiva.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 0e6d34c7-b4c6-4484-a2cd-93ccab223d1b

	measure 'HTML Shell A02 Plan y Ejecucion' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Plan y Ejecuci&oacute;n</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Seguimiento del plan de formacion, cumplimiento mensual y brechas de ejecucion.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Aprendizaje</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Periodo, empresa y variables de formacion.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: b4294c5a-ba94-4a41-a0f6-0d506e4da92b

	measure 'HTML Shell A03 Cobertura y Participacion' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Cobertura y Participaci&oacute;n</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Analisis de asistencia, cobertura, participacion y comportamiento por segmentos.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Aprendizaje</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros de cobertura y participacion.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: f29b2714-cfde-47b1-90be-a445736a3ae0

	measure 'HTML Shell A04 Satisfaccion y Eficacia' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Satisfacci&oacute;n y Eficacia</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Lectura de percepcion, favorabilidad, eficacia y oportunidades de mejora.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Aprendizaje</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros de calidad y percepcion.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: ee7c5a55-bcf4-459c-9749-6f9368183eba

	measure 'HTML Shell A05 Induccion y Entrenamiento' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Inducci&oacute;n y Entrenamiento</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Seguimiento a onboarding, entrenamiento inicial y segmentos Universidad Challenger.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Aprendizaje</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Periodo, segmento UC y atributos clave.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 9bb69acb-81c5-4f49-a406-c76eb83f12a8

	measure 'HTML Shell A06 Focos de Gestion' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Focos de Gesti&oacute;n</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Alertas, rankings y prioridades ejecutivas para toma de decisiones.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Aprendizaje</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros para priorizacion gerencial.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 765d2109-f8a5-4453-8030-c59ed06403f9

	measure 'HTML Shell D01 Resumen Ejecutivo Desarrollo' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Resumen Ejecutivo Desarrollo</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Vision general de PDI, avance, acompanamientos y alertas del frente.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desarrollo</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros de PDI por periodo, empresa y estado.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: f66aaec9-4fe0-49bb-aa54-54d10d41637a

	measure 'HTML Shell D02 Estado y Avance PDI' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Estado y Avance PDI</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Seguimiento de avance, estados, vencimientos y planes criticos.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desarrollo</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros de avance, estado y motivo PDI.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 5c9de129-6d0c-4282-93d6-529ba5e2f3f4

	measure 'HTML Shell D03 Motivos y Seguimiento' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Motivos y Seguimiento</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Analisis de motivos de apertura, acompanamientos y comportamiento por area.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desarrollo</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros de seguimiento y motivo PDI.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: a790124c-6ea0-4bff-b73d-210b00cae1fe

	measure 'HTML Shell D04 Focos de Gestion Desarrollo' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Focos de Gesti&oacute;n Desarrollo</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Alertas y focos prioritarios para seguimiento de planes de desarrollo.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desarrollo</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros para alertas y focos PDI.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 6b19d692-c794-4087-a45d-467f947939a8

	measure 'HTML Shell E01 Desempeno Proxima Fase' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;'>Resumen Ejecutivo Desempe&ntilde;o</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;'>Medici&oacute;n de objetivos, competencias y evoluci&oacute;n del desempe&ntilde;o organizacional.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desempe&ntilde;o</div>" &
				"<div style='position:absolute;left:160px;top:170px;width:960px;height:360px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:16px;box-shadow:0 10px 24px rgba(11,28,53,0.08);display:flex;align-items:center;justify-content:center;text-align:center;'>" &
				"<div><div style='font-size:52px;line-height:60px;'>&#128200;</div><div style='font-size:30px;font-weight:850;margin-top:12px;color:#0B1C35;'>Desempe&ntilde;o activo</div><div style='font-size:13px;line-height:20px;color:#53657D;margin:14px auto 0;width:520px;'>P&aacute;gina base para consolidar cobertura, objetivos, competencias, curva de niveles y detalle gerencial del frente.</div><div style='margin-top:26px;background:#F7931E;color:#0B1C35;border-radius:22px;padding:10px 20px;display:inline-block;font-size:12px;font-weight:850;'>Resumen ejecutivo</div></div>" &
				"</div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: da689f66-7a5f-4a4e-97f9-8916735a7b97

	measure 'Bienestar Actividades Totales' = DISTINCTCOUNT('Dim_ActividadBienestar'[ActividadBienestar_Key])
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: f7eb6329-7a9e-4cee-b8a8-b4377148179e

	measure 'Bienestar Programaciones Anuales' = SUM('Fct_SeguimientoBienestar'[PlaneadoOriginal])
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: f6bcae4e-dbaa-466c-92ff-7d965ffc5b44

	measure 'Bienestar Programaciones Registradas Ejecucion' = SUM('Fct_SeguimientoBienestar'[PlaneadoEjecucion])
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: 0c932b3e-ff0e-4350-8a48-3c7c02aea52a

	measure 'Bienestar Ejecutadas' = SUM('Fct_SeguimientoBienestar'[EjecutadoReal])
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: d3434d37-2ed5-40a2-af09-7c605c5b44c2

	measure 'Bienestar Ejecutadas Planeadas' = CALCULATE(SUM('Fct_SeguimientoBienestar'[EjecutadoReal]), 'Fct_SeguimientoBienestar'[PlaneadoOriginal] = 1)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: 0ac953bc-6421-45e2-a449-4df9b6ac3a89

	measure 'Bienestar Programadas al Corte' =
			VAR _UltimoPeriodo =
				CALCULATE(
					MAX('Fct_SeguimientoBienestar'[FechaPeriodo]),
					REMOVEFILTERS('Dim_Calendario'),
					REMOVEFILTERS('Dim_ActividadBienestar'),
					REMOVEFILTERS('Dim_DimensionBienestar'),
					'Fct_SeguimientoBienestar'[EjecutadoReal] = 1
				)
			RETURN
				IF(
					ISBLANK(_UltimoPeriodo),
					0,
					CALCULATE(
						COUNTROWS('Fct_SeguimientoBienestar'),
						'Fct_SeguimientoBienestar'[PlaneadoEjecucion] = 1,
						'Fct_SeguimientoBienestar'[FechaPeriodo] <= _UltimoPeriodo
					)
				)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: 0a4d6c84-4a1d-4548-88f9-7fe3f223ddf4

	measure 'Bienestar Ejecutadas al Corte' =
			VAR _UltimoPeriodo =
				CALCULATE(
					MAX('Fct_SeguimientoBienestar'[FechaPeriodo]),
					REMOVEFILTERS('Dim_Calendario'),
					REMOVEFILTERS('Dim_ActividadBienestar'),
					REMOVEFILTERS('Dim_DimensionBienestar'),
					'Fct_SeguimientoBienestar'[EjecutadoReal] = 1
				)
			RETURN
				IF(
					ISBLANK(_UltimoPeriodo),
					0,
					CALCULATE(
						SUM('Fct_SeguimientoBienestar'[EjecutadoReal]),
						'Fct_SeguimientoBienestar'[PlaneadoEjecucion] = 1,
						'Fct_SeguimientoBienestar'[FechaPeriodo] <= _UltimoPeriodo
					)
				)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: fb6fe021-7a4d-4866-bc28-411fce3f10a0

	measure 'Bienestar Cumplimiento al Corte %' = DIVIDE([Bienestar Ejecutadas al Corte], [Bienestar Programadas al Corte], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 14 Plan Bienestar
		lineageTag: 2e3ad48d-198d-4d0a-bfab-d1897467907a

	measure 'Bienestar Avance Anual %' = DIVIDE([Bienestar Ejecutadas], [Bienestar Programaciones Registradas Ejecucion], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 14 Plan Bienestar
		lineageTag: 190c3cbb-c81e-4b7a-b536-be852a126c19

	measure 'Bienestar Pendientes Vencidos' =
			VAR _UltimoPeriodo =
				CALCULATE(
					MAX('Fct_SeguimientoBienestar'[FechaPeriodo]),
					REMOVEFILTERS('Dim_Calendario'),
					REMOVEFILTERS('Dim_ActividadBienestar'),
					REMOVEFILTERS('Dim_DimensionBienestar'),
					'Fct_SeguimientoBienestar'[EjecutadoReal] = 1
				)
			RETURN
				IF(
					ISBLANK(_UltimoPeriodo),
					0,
					COALESCE(
						CALCULATE(
							COUNTROWS('Fct_SeguimientoBienestar'),
							'Fct_SeguimientoBienestar'[PlaneadoEjecucion] = 1,
							'Fct_SeguimientoBienestar'[EjecutadoReal] = 0,
							'Fct_SeguimientoBienestar'[FechaPeriodo] < _UltimoPeriodo
						),
						0
					)
				)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: ee9035e4-a417-4a11-b031-6c8adb544b77

	measure 'Bienestar Pendientes Futuros' =
			VAR _UltimoPeriodo =
				CALCULATE(
					MAX('Fct_SeguimientoBienestar'[FechaPeriodo]),
					REMOVEFILTERS('Dim_Calendario'),
					REMOVEFILTERS('Dim_ActividadBienestar'),
					REMOVEFILTERS('Dim_DimensionBienestar'),
					'Fct_SeguimientoBienestar'[EjecutadoReal] = 1
				)
			RETURN
				IF(
					ISBLANK(_UltimoPeriodo),
					0,
					CALCULATE(
						COUNTROWS('Fct_SeguimientoBienestar'),
						'Fct_SeguimientoBienestar'[PlaneadoEjecucion] = 1,
						'Fct_SeguimientoBienestar'[EjecutadoReal] = 0,
						'Fct_SeguimientoBienestar'[FechaPeriodo] > _UltimoPeriodo
					)
				)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: 0d12714e-dbfa-452c-acc9-2b3877c14f67

	measure 'Bienestar Ejecutadas No Planeadas' =
			CALCULATE(
				SUM('Fct_SeguimientoBienestar'[EjecutadoReal]),
				'Fct_SeguimientoBienestar'[PlaneadoOriginal] = 0,
				'Fct_SeguimientoBienestar'[PlaneadoEjecucion] = 1
			)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: eb50ce6f-c576-4281-a415-7347635d3ca1

	measure 'Bienestar Diferencias Programacion' =
			CALCULATE(
				COUNTROWS('Fct_SeguimientoBienestar'),
				'Fct_SeguimientoBienestar'[DiferenciaProgramacion] <> 0
			)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: 624d0894-62e8-43f4-a68f-57b235a661e5

	measure 'Bienestar Ultimo Mes Reportado' =
			VAR _UltimoPeriodo =
				CALCULATE(
					MAX('Fct_SeguimientoBienestar'[FechaPeriodo]),
					REMOVEFILTERS('Dim_Calendario'),
					REMOVEFILTERS('Dim_ActividadBienestar'),
					REMOVEFILTERS('Dim_DimensionBienestar'),
					'Fct_SeguimientoBienestar'[EjecutadoReal] = 1
				)
			RETURN
				IF(
					ISBLANK(_UltimoPeriodo),
					BLANK(),
					FORMAT(_UltimoPeriodo, "mmmm yyyy")
				)
		displayFolder: 14 Plan Bienestar
		lineageTag: c4b6fd10-fd89-4852-aa8e-6fb7acd41208

	measure 'Bienestar Dimensiones Activas' =
			COUNTROWS(
				FILTER(
					VALUES('Dim_DimensionBienestar'[DimensionBienestar_Key]),
					CALCULATE([Bienestar Programaciones Anuales] + [Bienestar Programaciones Registradas Ejecucion] + [Bienestar Ejecutadas]) > 0
				)
			)
		formatString: #,0
		displayFolder: 14 Plan Bienestar
		lineageTag: d2a7aab2-3480-412e-89a8-aee181198ab9

	measure 'HTML Shell BC03 Plan de Bienestar' =
			VAR _UltimoMesReportado =
				CALCULATE(
					[Bienestar Ultimo Mes Reportado],
					REMOVEFILTERS('Dim_Calendario'),
					REMOVEFILTERS('Dim_ActividadBienestar'),
					REMOVEFILTERS('Dim_DimensionBienestar'),
					REMOVEFILTERS('Fct_SeguimientoBienestar'[EstadoAlCorte])
				)
			VAR _TextoCorte = "Ultimo mes reportado: " & COALESCE(_UltimoMesReportado, "Sin dato")
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>BC03</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>Plan de Bienestar</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Seguimiento mensual de actividades, cumplimiento y alertas del plan vigente.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Bienestar y Clima</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Anio, mes, dimension y estado operativo del plan.</div>" &
				"<div style='position:absolute;left:252px;top:121px;width:756px;height:58px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:1024px;top:121px;width:188px;height:58px;background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;padding:8px 12px;box-sizing:border-box;color:#53657D;font-size:10px;line-height:13px;'>" &
				"<div style='font-weight:850;color:#1A3059;'>Lectura de corte</div><div style='margin-top:6px;'>" & _TextoCorte & "</div></div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:1005px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN
				_Html
		displayFolder: 11 HTML Content
		lineageTag: 0ae8a12d-b52a-4db5-ac39-d0adc7b633d1

	measure 'Bienestar Actividades Retiradas Ejecucion' =
			CALCULATE(
				COUNTROWS('Fct_SeguimientoBienestar'),
				'Fct_SeguimientoBienestar'[EstadoProgramacion] = "Retirado de ejecucion"
			)
		formatString: #,0
		displayFolder: 14 Plan Bienestar\Soporte Visual
		lineageTag: 1f910f3f-1745-4f99-92b3-de85c23aa6c8

	measure 'Bienestar Calendario Estado' =
			VAR _EstadoCorte = SELECTEDVALUE('Fct_SeguimientoBienestar'[EstadoAlCorte])
			VAR _EstadoProgramacion = SELECTEDVALUE('Fct_SeguimientoBienestar'[EstadoProgramacion])
			VAR _Ejecutado = SELECTEDVALUE('Fct_SeguimientoBienestar'[EjecutadoReal], 0)
			VAR _PlaneadoOriginal = SELECTEDVALUE('Fct_SeguimientoBienestar'[PlaneadoOriginal], 0)
			RETURN
				SWITCH(
					TRUE(),
					_EstadoCorte = "Ejecutado no planeado" || (_Ejecutado = 1 && _PlaneadoOriginal = 0), "EP",
					_EstadoCorte = "Ejecutado", "OK",
					_EstadoCorte = "Retirado de ejecucion" || _EstadoProgramacion = "Retirado de ejecucion", "RET",
					_EstadoCorte = "Pendiente vencido", "PV",
					_EstadoCorte = "Pendiente en curso" || _EstadoCorte = "Pendiente sin corte", "PC",
					_EstadoCorte = "Pendiente futuro", "PF",
					BLANK()
				)
		displayFolder: 14 Plan Bienestar\Soporte Visual
		lineageTag: 01027286-db60-402a-941a-acd9ee0d18bd

	measure 'Bienestar Calendario Color Fondo' =
			VAR _Estado = [Bienestar Calendario Estado]
			RETURN
				SWITCH(
					_Estado,
					"OK", "#D8E4F2",
					"EP", "#BFD3EA",
					"RET", "#E9EDF3",
					"PV", "#F7931E",
					"PC", "#FBCB95",
					"PF", "#FFF2E2",
					"#FFFFFF"
				)
		displayFolder: 14 Plan Bienestar\Soporte Visual
		lineageTag: 5c41241d-8f7a-49dd-bff0-3fc05ac86e42

	measure 'PDI Motivo Principal' =
			VAR _Tabla = ADDCOLUMNS(VALUES('Dim_MotivoPDI'[Motivo_PDI]), "Cnt", CALCULATE([PDI Total]))
			VAR _Top = TOPN(1, _Tabla, [Cnt], DESC)
			VAR _Result = CONCATENATEX(_Top, [Motivo_PDI])
			RETURN IF(_Result = "" || ISBLANK(_Result), "Sin datos", _Result)
		displayFolder: 09 Desarrollo PDI
		lineageTag: c3a7b2e1-4f89-4d06-b523-8e7f19d4a062

	measure 'PDI Estado Principal' =
			VAR _Tabla = ADDCOLUMNS(VALUES('Dim_EstadoPDI'[Estado_PDI]), "Cnt", CALCULATE([PDI Total]))
			VAR _Top = TOPN(1, _Tabla, [Cnt], DESC)
			VAR _Result = CONCATENATEX(_Top, [Estado_PDI])
			RETURN IF(_Result = "" || ISBLANK(_Result), "Sin datos", _Result)
		displayFolder: 09 Desarrollo PDI
		lineageTag: d4b8c3f2-5a90-4e17-c634-9f8020e5b173

	measure 'Desempeno Poblacion Activa' =
			CALCULATE(
				DISTINCTCOUNT('Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key]),
				'Fct_Poblacion_Indicadores_2025'[INDICADOR ACTIVIDAD] = "ACTIVO"
			)
		formatString: #,0
		displayFolder: 15 Cobertura Desempeno
		lineageTag: 8bba6ae8-74e9-4dfb-b63c-46d8714d9585

	measure 'Desempeno Evaluados Objetivos' = DISTINCTCOUNT('Fct_Desempeno_2025'[ColaboradorDesempeno_Key])
		formatString: #,0
		displayFolder: 15 Cobertura Desempeno
		lineageTag: 76ae96f0-73c1-4246-adb2-0adbb7fb5157

	measure 'Competencias Evaluados' = DISTINCTCOUNT('Fct_Competencias_2025'[ColaboradorDesempeno_Key])
		formatString: #,0
		displayFolder: 15 Cobertura Desempeno
		lineageTag: a25df2fc-2416-458a-8a0f-29af7ba4a895

	measure 'Desempeno No Evaluados Objetivos' = COALESCE([Desempeno Poblacion Activa], 0) - COALESCE([Desempeno Evaluados Objetivos], 0)
		formatString: #,0
		displayFolder: 15 Cobertura Desempeno
		lineageTag: 21801163-2025-47dd-bf30-5b4b97d3c015

	measure 'Competencias No Evaluados' = COALESCE([Desempeno Poblacion Activa], 0) - COALESCE([Competencias Evaluados], 0)
		formatString: #,0
		displayFolder: 15 Cobertura Desempeno
		lineageTag: 81a7d371-118e-4661-8c6e-b697180f1c47

	measure 'Desempeno Cobertura Objetivos %' = DIVIDE([Desempeno Evaluados Objetivos], [Desempeno Poblacion Activa])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 15 Cobertura Desempeno
		lineageTag: eb4c8ad1-6167-4dab-aa41-5d57e2af9955

	measure 'Competencias Cobertura %' = DIVIDE([Competencias Evaluados], [Desempeno Poblacion Activa])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 15 Cobertura Desempeno
		lineageTag: 27b39cd5-6c71-43e2-85b5-2608b250d9f8

	measure 'Desempeno Promedio' = AVERAGE('Fct_Desempeno_2025'[Calificación Final])
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: 37dc9dd8-4878-44d8-ac72-4bcb64ee3998

	measure 'Desempeno Promedio 2024' = AVERAGE('Fct_Desempeno_2025'[Calificación 2024])
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: b34f23d5-1782-4405-85c3-15083361da22

	measure 'Desempeno Variacion 2025 vs 2024' = [Desempeno Promedio] - [Desempeno Promedio 2024]
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: b3f48710-2be4-4b3f-830a-d991b599fa61

	measure 'Desempeno Variacion 2025 vs 2024 %' = DIVIDE([Desempeno Variacion 2025 vs 2024], [Desempeno Promedio 2024])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 12 Desempeno
		lineageTag: 0c67b1b3-fd2e-456e-8c4f-2395d5d82c6d

	measure 'Desempeno Colaboradores por Nivel' = DISTINCTCOUNT('Fct_Desempeno_2025'[ColaboradorDesempeno_Key])
		formatString: #,0
		displayFolder: 12 Desempeno
		lineageTag: 3d1786dd-5eb1-4fd5-9064-84ff1f4df875

	measure 'Desempeno % por Nivel' =
			DIVIDE(
				[Desempeno Colaboradores por Nivel],
				CALCULATE(
					[Desempeno Colaboradores por Nivel],
					REMOVEFILTERS('Fct_Desempeno_2025'[Interpretacion_Homologada]),
					REMOVEFILTERS('Fct_Desempeno_2025'[NivelDesempeno_Key])
				)
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 12 Desempeno
		lineageTag: c0974e6d-d221-4828-af40-87b60d1ec622

	measure 'Desempeno Promedio por Empresa' = [Desempeno Promedio]
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: c27b370f-8ec9-493b-93fe-c72f3cfd951f

	measure 'Desempeno Promedio por Area' = [Desempeno Promedio]
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: 358f4221-9747-4c07-b35c-5ae79e95418f

	measure 'Desempeno Promedio por Cargo' = [Desempeno Promedio]
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: 22f68e47-d646-4553-8abf-9d9e2a629b6f

	measure 'Desempeno Promedio por Dependencia' = [Desempeno Promedio]
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: 588a4d3a-19be-4857-8739-900f72ea3f78

	measure 'Desempeno Ranking Areas Menor Promedio' =
			VAR _Promedio = [Desempeno Promedio]
			RETURN
				IF(
					ISBLANK(_Promedio),
					BLANK(),
					RANKX(
						ALLSELECTED('Fct_Desempeno_2025'[Área]),
						[Desempeno Promedio],
						,
						ASC,
						DENSE
					)
				)
		formatString: #,0
		displayFolder: 12 Desempeno
		lineageTag: 51d5d680-ff8d-4971-bd93-43c4c4386e7d

	measure 'Competencias Promedio' = AVERAGE('Fct_Competencias_2025'[Puntaje Obtenido])
		formatString: 0.00
		displayFolder: 13 Competencias
		lineageTag: 28d1694c-ee15-42c2-9c46-b31022ba28d7

	measure 'Competencias Puntaje Requerido Promedio' = AVERAGE('Fct_Competencias_2025'[Puntaje Requerido])
		formatString: 0.00
		displayFolder: 13 Competencias
		lineageTag: 79aa45e0-3fa4-4e48-9dd7-bf63f01f48b7

	measure 'Competencias Brecha Promedio' = [Competencias Puntaje Requerido Promedio] - [Competencias Promedio]
		formatString: 0.00
		displayFolder: 13 Competencias
		lineageTag: 0777f311-ef1f-468d-a441-9f2b3f407142

	measure 'Competencias Registros por Nivel' = COUNTROWS('Fct_Competencias_2025')
		formatString: #,0
		displayFolder: 13 Competencias
		lineageTag: 12c576af-2848-4b1c-970d-1021622824f3

	measure 'Competencias % por Nivel' =
			DIVIDE(
				[Competencias Registros por Nivel],
				CALCULATE(
					[Competencias Registros por Nivel],
					REMOVEFILTERS('Fct_Competencias_2025'[Interpretacion_Homologada]),
					REMOVEFILTERS('Fct_Competencias_2025'[NivelDesempeno_Key])
				)
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Competencias
		lineageTag: e6c49c98-a722-45cc-af48-4a5cd8a6c19a

	measure 'Competencias Promedio por Empresa' = [Competencias Promedio]
		formatString: 0.00
		displayFolder: 13 Competencias
		lineageTag: 8c4b3106-fb5c-4f12-b7e3-7f14a1732bd4

	measure 'Competencias Promedio por Dependencia' = [Competencias Promedio]
		formatString: 0.00
		displayFolder: 13 Competencias
		lineageTag: 5bead195-5d2c-49fd-8329-e875232767a7

	measure 'Competencias Ranking Mayor Brecha' =
			VAR _Brecha = [Competencias Brecha Promedio]
			RETURN
				IF(
					ISBLANK(_Brecha),
					BLANK(),
					RANKX(
						ALLSELECTED('Fct_Competencias_2025'[Requerimiento_Homologado]),
						[Competencias Brecha Promedio],
						,
						DESC,
						DENSE
					)
				)
		formatString: #,0
		displayFolder: 13 Competencias
		lineageTag: 62d7d99a-d9d4-4197-a95c-fb1f6895e081

	measure 'NineBox Desempeno Score' = AVERAGE('Fct_Desempeno_2025'[Calificación Final])
		formatString: 0.00
		displayFolder: 14 Nine Box
		lineageTag: 8a076910-9b3b-4a60-a689-fb292e5044b5

	measure 'NineBox Competencias Score' = AVERAGE('Fct_Competencias_2025'[Puntaje Obtenido])
		formatString: 0.00
		displayFolder: 14 Nine Box
		lineageTag: 4aa66576-b6e4-4cf8-bff2-df3e7ce42a94

	measure 'NineBox Banda Desempeno' =
			VAR _Score = [NineBox Desempeno Score]
			RETURN
				SWITCH(
					TRUE(),
					ISBLANK(_Score), BLANK(),
					_Score <= 50, "Bajo",
					_Score <= 70, "Medio",
					_Score >= 71, "Alto",
					BLANK()
				)
		displayFolder: 14 Nine Box
		lineageTag: e0567d4e-4354-4182-b85e-f67460da2a22

	measure 'NineBox Banda Competencias' =
			VAR _Score = [NineBox Competencias Score]
			RETURN
				SWITCH(
					TRUE(),
					ISBLANK(_Score), BLANK(),
					_Score <= 50, "Bajo",
					_Score <= 70, "Medio",
					_Score >= 71, "Alto",
					BLANK()
				)
		displayFolder: 14 Nine Box
		lineageTag: 8e501ad5-0b9d-4e2c-a3ee-e269d276bb2d

	measure 'NineBox Cuadrante' =
			VAR _BandaDesempeno = [NineBox Banda Desempeno]
			VAR _BandaCompetencias = [NineBox Banda Competencias]
			RETURN
				IF(
					ISBLANK(_BandaDesempeno) || ISBLANK(_BandaCompetencias),
					BLANK(),
					_BandaDesempeno & "-" & _BandaCompetencias
				)
		displayFolder: 14 Nine Box
		lineageTag: cfa4ac19-4eb1-4d9e-a9ff-078b60ae1661

	measure 'NineBox Categoria Ejecutiva' =
			SWITCH(
				[NineBox Cuadrante],
				"Alto-Alto", "Alto Potencial",
				"Alto-Medio", "Alto Potencial",
				"Medio-Medio", "Talento Sólido",
				"Medio-Alto", "Talento Sólido",
				"Bajo-Alto", "Talento Sólido",
				"Alto-Bajo", "Desarrollo Requerido",
				"Medio-Bajo", "Desarrollo Requerido",
				"Bajo-Bajo", "Riesgo",
				"Bajo-Medio", "Riesgo",
				BLANK()
			)
		displayFolder: 14 Nine Box
		lineageTag: 84444867-3181-4409-863e-2b55915d946b

	measure 'NineBox Colaboradores Evaluables' =
			VAR _Base =
				FILTER(
					CALCULATETABLE(
						VALUES('Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key]),
						KEEPFILTERS('Fct_Poblacion_Indicadores_2025'[INDICADOR ACTIVIDAD] = "ACTIVO")
					),
					NOT ISBLANK('Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key])
				)
			VAR _Scored =
				ADDCOLUMNS(
					_Base,
					"__Desempeno",
						VAR _Key = 'Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key]
						RETURN
							CALCULATE(
								AVERAGE('Fct_Desempeno_2025'[Calificación Final]),
								'Fct_Desempeno_2025'[ColaboradorDesempeno_Key] = _Key
							),
					"__Competencias",
						VAR _Key = 'Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key]
						RETURN
							CALCULATE(
								AVERAGE('Fct_Competencias_2025'[Puntaje Obtenido]),
								'Fct_Competencias_2025'[ColaboradorDesempeno_Key] = _Key
							)
				)
			VAR _Bandas =
				ADDCOLUMNS(
					_Scored,
					"__BandaDesempeno",
						VAR _Score = [__Desempeno]
						RETURN
							SWITCH(
								TRUE(),
								ISBLANK(_Score), BLANK(),
								_Score <= 50, "Bajo",
								_Score <= 70, "Medio",
								_Score >= 71, "Alto",
								BLANK()
							),
					"__BandaCompetencias",
						VAR _Score = [__Competencias]
						RETURN
							SWITCH(
								TRUE(),
								ISBLANK(_Score), BLANK(),
								_Score <= 50, "Bajo",
								_Score <= 70, "Medio",
								_Score >= 71, "Alto",
								BLANK()
							)
				)
			RETURN
				COUNTROWS(
					FILTER(
						_Bandas,
						NOT ISBLANK([__BandaDesempeno]) &&
						NOT ISBLANK([__BandaCompetencias])
					)
				)
		formatString: #,0
		displayFolder: 14 Nine Box
		lineageTag: 767e3ff6-dd91-4966-86db-fc613c070a75

	measure 'NineBox Colaboradores por Cuadrante' =
			VAR _TargetDesempeno = SELECTEDVALUE('Dim_NineBox_Cuadrante'[Banda_Desempeno])
			VAR _TargetCompetencias = SELECTEDVALUE('Dim_NineBox_Cuadrante'[Banda_Competencias])
			VAR _TargetCategoria = SELECTEDVALUE('Dim_NineBox_Cuadrante'[Categoria_Ejecutiva])
			VAR _Base =
				FILTER(
					CALCULATETABLE(
						VALUES('Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key]),
						KEEPFILTERS('Fct_Poblacion_Indicadores_2025'[INDICADOR ACTIVIDAD] = "ACTIVO")
					),
					NOT ISBLANK('Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key])
				)
			VAR _Scored =
				ADDCOLUMNS(
					_Base,
					"__Desempeno",
						VAR _Key = 'Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key]
						RETURN
							CALCULATE(
								AVERAGE('Fct_Desempeno_2025'[Calificación Final]),
								'Fct_Desempeno_2025'[ColaboradorDesempeno_Key] = _Key
							),
					"__Competencias",
						VAR _Key = 'Fct_Poblacion_Indicadores_2025'[ColaboradorDesempeno_Key]
						RETURN
							CALCULATE(
								AVERAGE('Fct_Competencias_2025'[Puntaje Obtenido]),
								'Fct_Competencias_2025'[ColaboradorDesempeno_Key] = _Key
							)
				)
			VAR _Bandas =
				ADDCOLUMNS(
					_Scored,
					"__BandaDesempeno",
						VAR _Score = [__Desempeno]
						RETURN
							SWITCH(
								TRUE(),
								ISBLANK(_Score), BLANK(),
								_Score <= 50, "Bajo",
								_Score <= 70, "Medio",
								_Score >= 71, "Alto",
								BLANK()
							),
					"__BandaCompetencias",
						VAR _Score = [__Competencias]
						RETURN
							SWITCH(
								TRUE(),
								ISBLANK(_Score), BLANK(),
								_Score <= 50, "Bajo",
								_Score <= 70, "Medio",
								_Score >= 71, "Alto",
								BLANK()
							)
				)
			VAR _Categoria =
				ADDCOLUMNS(
					_Bandas,
					"__Categoria",
						VAR _Cuadrante = [__BandaDesempeno] & "-" & [__BandaCompetencias]
						RETURN
							SWITCH(
								_Cuadrante,
								"Alto-Alto", "Alto Potencial",
								"Alto-Medio", "Alto Potencial",
								"Medio-Medio", "Talento Sólido",
								"Medio-Alto", "Talento Sólido",
								"Bajo-Alto", "Talento Sólido",
								"Alto-Bajo", "Desarrollo Requerido",
								"Medio-Bajo", "Desarrollo Requerido",
								"Bajo-Bajo", "Riesgo",
								"Bajo-Medio", "Riesgo",
								BLANK()
							)
				)
			RETURN
				COUNTROWS(
					FILTER(
						_Categoria,
						NOT ISBLANK([__BandaDesempeno]) &&
						NOT ISBLANK([__BandaCompetencias]) &&
						(ISBLANK(_TargetDesempeno) || [__BandaDesempeno] = _TargetDesempeno) &&
						(ISBLANK(_TargetCompetencias) || [__BandaCompetencias] = _TargetCompetencias) &&
						(ISBLANK(_TargetCategoria) || [__Categoria] = _TargetCategoria)
					)
				)
		formatString: #,0
		displayFolder: 14 Nine Box
		lineageTag: e6a80cb3-b3cf-4817-8170-baf02af18e12

	measure 'NineBox % por Cuadrante' = DIVIDE([NineBox Colaboradores por Cuadrante], [NineBox Colaboradores Evaluables])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 14 Nine Box
		lineageTag: b59fb85e-b654-47d9-8aa0-f45660d2468b

	measure 'NineBox Alto Potencial' =
			CALCULATE(
				[NineBox Colaboradores por Cuadrante],
				TREATAS({"Alto Potencial"}, 'Dim_NineBox_Cuadrante'[Categoria_Ejecutiva])
			)
		formatString: #,0
		displayFolder: 14 Nine Box
		lineageTag: e63ba0cf-6656-4cfb-bc52-48601465f190

	measure 'NineBox Talento Solido' =
			CALCULATE(
				[NineBox Colaboradores por Cuadrante],
				TREATAS({"Talento Sólido"}, 'Dim_NineBox_Cuadrante'[Categoria_Ejecutiva])
			)
		formatString: #,0
		displayFolder: 14 Nine Box
		lineageTag: db2fc031-19e9-472a-a2f5-b41839223494

	measure 'NineBox Desarrollo Requerido' =
			CALCULATE(
				[NineBox Colaboradores por Cuadrante],
				TREATAS({"Desarrollo Requerido"}, 'Dim_NineBox_Cuadrante'[Categoria_Ejecutiva])
			)
		formatString: #,0
		displayFolder: 14 Nine Box
		lineageTag: f89dc2f1-126a-44c9-9b45-cfd699acbd62

	measure 'NineBox Riesgo' =
			CALCULATE(
				[NineBox Colaboradores por Cuadrante],
				TREATAS({"Riesgo"}, 'Dim_NineBox_Cuadrante'[Categoria_Ejecutiva])
			)
		formatString: #,0
		displayFolder: 14 Nine Box
		lineageTag: d7251fe7-467f-4d5a-87e0-b6facf16aeaa

	measure 'NineBox % Alto Potencial' = DIVIDE([NineBox Alto Potencial], [NineBox Colaboradores Evaluables])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 14 Nine Box
		lineageTag: 2f03e325-6d49-4ad2-8909-1e3957858061

	measure 'NineBox % Talento Solido' = DIVIDE([NineBox Talento Solido], [NineBox Colaboradores Evaluables])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 14 Nine Box
		lineageTag: 5962edae-dc6c-4d61-bd5b-4809134fb88d

	measure 'NineBox % Desarrollo Requerido' = DIVIDE([NineBox Desarrollo Requerido], [NineBox Colaboradores Evaluables])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 14 Nine Box
		lineageTag: 02ed3556-cf59-4b93-a70f-c5f27f138690

	measure 'NineBox % Riesgo' = DIVIDE([NineBox Riesgo], [NineBox Colaboradores Evaluables])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 14 Nine Box
		lineageTag: aa19d736-2b68-49d1-8aeb-bdcfe300aef1

	measure 'HTML Shell DS02 Cobertura' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>DS02 Cobertura Desempe&ntilde;o</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Poblacion activa, evaluados, no evaluados y cobertura por estructura.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desempe&ntilde;o</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros activos para cobertura del frente.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:530px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN _Html
		displayFolder: 11 HTML Content
		lineageTag: db7c3359-e84e-4db8-91e0-08f4eaa0550c

	measure 'Desempeno Evaluados DS03' =
			VAR _Anios = VALUES('Dim_Anio_Desempeno'[Anio])
			VAR _FiltroAnio =
				FILTER(
					ALL('Fct_Desempeno_2025'[Fecha de Proceso]),
					YEAR('Fct_Desempeno_2025'[Fecha de Proceso]) IN _Anios
				)
			RETURN
				CALCULATE(
					[Desempeno Evaluados Objetivos],
					_FiltroAnio
				)
		formatString: #,0
		displayFolder: 12 Desempeno
		lineageTag: b16597e3-3e5a-4704-81ea-0d15fa13c404

	measure 'Desempeno Promedio DS03' =
			VAR _Anios = VALUES('Dim_Anio_Desempeno'[Anio])
			VAR _FiltroAnio =
				FILTER(
					ALL('Fct_Desempeno_2025'[Fecha de Proceso]),
					YEAR('Fct_Desempeno_2025'[Fecha de Proceso]) IN _Anios
				)
			RETURN
				CALCULATE(
					[Desempeno Promedio],
					_FiltroAnio
				)
		formatString: 0.00
		displayFolder: 12 Desempeno
		lineageTag: a4490197-731f-412f-88fc-6d17986c9922

	measure 'Desempeno Cobertura Objetivos DS03 %' = DIVIDE([Desempeno Evaluados DS03], [Desempeno Poblacion Activa])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 12 Desempeno
		lineageTag: 60e59257-762d-4575-959c-90031cbdbfde

	measure 'Desempeno Colaboradores Nivel DS03' =
			VAR _Nivel = VALUES('Dim_Nivel_Desempeno'[NivelDesempeno_Key])
			VAR _Anios = VALUES('Dim_Anio_Desempeno'[Anio])
			VAR _FiltroAnio =
				FILTER(
					ALL('Fct_Desempeno_2025'[Fecha de Proceso]),
					YEAR('Fct_Desempeno_2025'[Fecha de Proceso]) IN _Anios
				)
			RETURN
				CALCULATE(
					[Desempeno Colaboradores por Nivel],
					TREATAS(_Nivel, 'Fct_Desempeno_2025'[NivelDesempeno_Key]),
					_FiltroAnio
				)
		formatString: #,0
		displayFolder: 12 Desempeno
		lineageTag: 9802cbae-5dcb-4990-9583-98a8a9c017c8

	measure 'Desempeno % Nivel DS03' =
			DIVIDE(
				[Desempeno Colaboradores Nivel DS03],
				CALCULATE(
					[Desempeno Colaboradores Nivel DS03],
					REMOVEFILTERS('Dim_Nivel_Desempeno')
				)
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 12 Desempeno
		lineageTag: 85fe5bba-b847-4dff-9ed4-bf5124870fdb

	measure 'HTML Shell DS03 Curva Niveles' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>DS03 Curva de Niveles</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Distribucion Critico, Bajo, Intermedio, Alto y Avanzado por estructura.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desempe&ntilde;o</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros activos para curva de desempeno.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:655px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN _Html
		displayFolder: 11 HTML Content
		lineageTag: e325de5d-2128-489c-a222-12cf2982ec27

	measure 'Competencias Registros Nivel DS04' =
			VAR _Nivel = VALUES('Dim_Nivel_Desempeno'[NivelDesempeno_Key])
			RETURN
				CALCULATE(
					[Competencias Registros por Nivel],
					TREATAS(_Nivel, 'Fct_Competencias_2025'[NivelDesempeno_Key])
				)
		formatString: #,0
		displayFolder: 13 Competencias
		lineageTag: 7c9ef05e-f05d-4698-946e-b1c68494e18f

	measure 'Competencias % Nivel DS04' =
			DIVIDE(
				[Competencias Registros Nivel DS04],
				CALCULATE(
					[Competencias Registros Nivel DS04],
					REMOVEFILTERS('Dim_Nivel_Desempeno')
				)
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Competencias
		lineageTag: 2cf8956b-c491-4bed-b6ac-fedfe76549d0

	measure 'Competencias Ranking Mejor Evaluadas' =
			VAR _Puntaje = [Competencias Promedio]
			RETURN
				IF(
					ISBLANK(_Puntaje),
					BLANK(),
					RANKX(
						ALLSELECTED('Fct_Competencias_2025'[Nombre Registro]),
					[Competencias Promedio],
					,
					DESC,
					DENSE
				)
			)
		formatString: #,0
		displayFolder: 13 Competencias
		lineageTag: b84f366e-f5ec-491a-b026-f768e827f048

	measure 'Competencias Top 10 Mayor Brecha' =
			IF(
				[Competencias Ranking Mayor Brecha] <= 10,
				[Competencias Brecha Promedio]
			)
		formatString: 0.00
		displayFolder: 13 Competencias
		lineageTag: a8c077d6-cbbf-406c-9b2e-39e4f117d2de

	measure 'Competencias Top 10 Mejor Evaluadas' =
			IF(
				[Competencias Ranking Mejor Evaluadas] <= 10,
				[Competencias Promedio]
			)
		formatString: 0.00
		displayFolder: 13 Competencias
		lineageTag: 5627fe5d-7f8d-4728-bff2-118261625f4f

	measure 'HTML Shell DS04 Competencias' =
			VAR _Html =
				"<div style='font-family:Outfit,Poppins,Segoe UI,Arial,sans-serif;width:1280px;height:720px;background:#F7F9FC;color:#0B1C35;position:relative;overflow:hidden;'>" &
				"<div style='position:absolute;left:0;top:0;width:1280px;height:100px;background:#0B1C35;'></div>" &
				"<div style='position:absolute;left:48px;top:24px;color:#F7931E;font-size:11px;font-weight:850;letter-spacing:2px;text-transform:uppercase;'>DASHBOARD CORPORATIVO - GRUPO LEMCO</div>" &
				"<div style='position:absolute;left:48px;top:48px;color:#FFFFFF;font-size:25px;font-weight:850;line-height:28px;'>DS04 Competencias</div>" &
				"<div style='position:absolute;left:48px;top:78px;color:#D8E4F2;font-size:11px;line-height:14px;'>Puntaje obtenido, requerido y brechas de competencias.</div>" &
				"<div style='position:absolute;right:48px;top:32px;background:#F7931E;color:#0B1C35;border-radius:18px;padding:8px 16px;font-size:11px;font-weight:850;'>Bloque Desempe&ntilde;o</div>" &
				"<div style='position:absolute;left:48px;top:112px;width:1200px;height:76px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:14px;box-shadow:0 6px 18px rgba(11,28,53,0.06);'></div>" &
				"<div style='position:absolute;left:48px;top:112px;width:7px;height:76px;background:#F7931E;border-radius:14px 0 0 14px;'></div>" &
				"<div style='position:absolute;left:68px;top:127px;color:#0B1C35;font-size:10px;font-weight:850;letter-spacing:1.5px;text-transform:uppercase;'>Contexto de analisis</div>" &
				"<div style='position:absolute;left:68px;top:148px;width:150px;color:#6B778A;font-size:9.5px;line-height:12px;'>Filtros activos para competencias.</div>" &
				"<div style='position:absolute;left:238px;top:121px;width:1050px;height:58px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px;'>" &
				"<div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div><div style='background:#F7FAFD;border:1px solid #E6EEF7;border-radius:8px;'></div>" &
				"</div>" &
				"<div style='position:absolute;left:32px;top:198px;width:1216px;height:468px;background:#FFFFFF;border:1px solid #E1E8F2;border-radius:10px;'></div>" &
				"<div style='position:absolute;left:32px;top:674px;width:790px;height:40px;background:#FFFFFF;border:1px solid #DCE5F2;border-radius:9px;'></div>" &
				"</div>"
			RETURN _Html
		displayFolder: 11 HTML Content
		lineageTag: df3649d7-1a0f-449f-b831-99e332e6334c

	column Indice
		dataType: int64
		isHidden
		lineageTag: b2e8471f-a590-4c95-b4ad-18d6cd43dc5a
		sourceColumn: [Indice]

	partition Medidas_AD = calculated
		mode: import
		source = DATATABLE("Indice", INTEGER, {{ 0 }})

