table Medidas_AD
	isHidden
	lineageTag: c7badb4a-3661-4961-a120-1576c2314372

	measure 'Plan Actividades Planificadas' = COUNTROWS('Fct_PlanFormacion')
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 13bf49f0-4051-4e59-bc23-7d071075004c

	measure 'Plan Actividades Ejecutadas' = CALCULATE(COUNTROWS('Fct_PlanFormacion'), 'Fct_PlanFormacion'[EstadoFormacion_Key] = "EJECUTADA")
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 9616bacc-cfe9-46d8-a9c4-6718f28557b6

	measure 'Plan Actividades Canceladas' = CALCULATE(COUNTROWS('Fct_PlanFormacion'), 'Fct_PlanFormacion'[EstadoFormacion_Key] = "CANCELADA")
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: e4a58cca-fb3d-46cb-aebe-80b96f1119e2

	measure 'Plan Actividades Reprogramadas' = CALCULATE(COUNTROWS('Fct_PlanFormacion'), 'Fct_PlanFormacion'[EstadoFormacion_Key] = "REPROGRAMADA")
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: da21c0c0-be26-42e8-8110-a1f302dc16fb

	measure 'Plan Actividades Vigentes' = [Plan Actividades Planificadas] - [Plan Actividades Canceladas]
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: ed3fc386-63b2-445b-95f7-451a885e0a14

	measure 'Plan Porcentaje Ejecucion' = DIVIDE([Plan Actividades Ejecutadas], [Plan Actividades Vigentes])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 737a2c66-b4af-454f-bafc-75392baf797f

	measure 'Plan Brecha Actividades' = [Plan Actividades Ejecutadas] - [Plan Actividades Vigentes]
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 750b8677-4138-4a17-b1f5-e376f47c957c

	measure 'Plan Publico Objetivo' = SUM('Fct_PlanFormacion'[PUBLICO OBJETIVO ])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 54afa7d7-e229-4660-bdae-72111fef494e

	measure 'Plan Asistencia Registrada' = SUM('Fct_PlanFormacion'[ASISTENCIA])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: cff3cfec-31b2-4cfa-ab36-a18517303712

	measure '% Cobertura' = DIVIDE(SUM('Fct_PlanFormacion'[ASISTENCIA]), SUM('Fct_PlanFormacion'[PUBLICO OBJETIVO ]), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: ee9905d4-fe15-4bcd-9d9c-4422c880a6e7

	measure '% Brecha Cobertura' = VAR _p = [% Cobertura] RETURN IF(ISBLANK(_p), BLANK(), MAX(0, 1 - _p))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 298b0543-503c-4670-aca5-40aa2ff218b0

	measure 'Plan Cobertura Asistencia' = [% Cobertura]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 2f3af5ac-9620-4a61-a5d4-3fbc94b2db22

	measure 'Plan Horas Formacion' = SUM('Fct_PlanFormacion'[TOTAL DE HORAS DE FORMACIÓN ])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: e053ccaa-25eb-4072-9620-4571a48635ee

	measure 'Plan Total Horas Formacion' = SUM('Fct_PlanFormacion'[TOTAL DE HORAS DE FORMACIÓN ])
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: cf9e0ed7-bde3-405d-907d-af0daa4372e8

	measure 'Plan Costo' = SUM('Fct_PlanFormacion'[COSTO])
		formatString: $ #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 49cbeab6-ceb6-4613-987c-a8c3f50ecff5

	measure 'Asistencia Total Registros' = COUNTROWS('Fct_AsistenciaFormacion')
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 3d393594-40cc-41a2-8cd3-a8f9c1e0bb12

	measure 'Asistencia Total Asistentes' = [Asistencia Total Registros]
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 1872009d-5975-4079-a676-f9c0916a9862

	measure 'Asistencia Participantes Unicos' = DISTINCTCOUNT('Fct_AsistenciaFormacion'[Número de documento del participante])
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 2c935cb8-e80e-4265-8a82-945c88b62868

	measure 'Asistencia Formaciones' = DISTINCTCOUNT('Fct_AsistenciaFormacion'[TemaFormacion_Key])
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 2b7fd8ae-1e97-427e-9e8f-338bbcc3a95f

	measure 'Asistencia Total Convocados' = [Plan Publico Objetivo]
		formatString: #,0
		displayFolder: 02 Asistencia
		lineageTag: 1d864477-151b-4977-b05a-c828a4d16009

	measure 'Asistencia Porcentaje Asistencia' = DIVIDE([Asistencia Total Asistentes], [Asistencia Total Convocados])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 02 Asistencia
		lineageTag: d8f8cff2-0bc9-4438-8a9a-43b36d82ef04

	measure 'Asistencia Porcentaje Ausentismo' = VAR _p = [Asistencia Porcentaje Asistencia] RETURN IF(ISBLANK(_p), BLANK(), MAX(0, 1 - _p))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 02 Asistencia
		lineageTag: 7e98b418-ad44-44df-953f-833d88f95c91

	measure 'Asistencia Promedio Por Formacion' = DIVIDE([Asistencia Total Asistentes], [Asistencia Formaciones])
		formatString: #,0.0
		displayFolder: 02 Asistencia
		lineageTag: 2b93e2e1-8605-4a8f-badb-120a66ee5f51

	measure 'Encuesta Total Respuestas' = COUNTROWS('Fct_EncuestaFormacion')
		formatString: #,0
		displayFolder: 03 Encuesta Formacion
		lineageTag: 8f3cef95-8fb8-44b3-8e1b-657872806636

	measure 'Encuesta Participantes Estimados' = [Encuesta Total Respuestas]
		formatString: #,0
		displayFolder: 03 Encuesta Formacion
		lineageTag: 8dce703a-0eee-483d-8bf2-2bf8feb77912

	measure 'Encuesta Tasa Respuesta' = DIVIDE([Encuesta Total Respuestas], [Asistencia Total Asistentes])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Encuesta Formacion
		lineageTag: 8c5290a2-677e-40b0-8c40-f693077cfdb5

	measure 'Encuesta Calificacion Promedio' =
			VAR _Suma =
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el dominio del tema por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la habilidad para comunicarse y transmitir ideas por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con las actividades o ejercicios por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el uso de ayudas didácticas por parte del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la resolución de dudas u observaciones del facilitador?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el cumplimiento del programa propuesto?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el espacio, logística y ambiente de la formación?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan oportuna fue la información respecto a fechas, horarios y lugar?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el logro de los objetivos propuestos?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la contribución del programa para tu desarrollo personal y/o profesional?]) +
			    SUM('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el acompañamiento de la Universidad Challenger en tu desarrollo personal y/o profesional?]) +
			    SUM('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
			VAR _Conteo =
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el dominio del tema por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la habilidad para comunicarse y transmitir ideas por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con las actividades o ejercicios por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el uso de ayudas didácticas por parte del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la resolución de dudas u observaciones del facilitador?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el cumplimiento del programa propuesto?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el espacio, logística y ambiente de la formación?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan oportuna fue la información respecto a fechas, horarios y lugar?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el logro de los objetivos propuestos?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con la contribución del programa para tu desarrollo personal y/o profesional?]) +
			    COUNT('Fct_EncuestaFormacion'[¿Qué tan satisfecho te encuentras con el acompañamiento de la Universidad Challenger en tu desarrollo personal y/o profesional?]) +
			    COUNT('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
			RETURN
			    DIVIDE(_Suma, _Conteo)
		formatString: 0.00
		displayFolder: 03 Encuesta Formacion
		lineageTag: 66d4c70a-b055-4891-9abe-6d10eda690dc

	measure 'Encuesta Favorabilidad' = DIVIDE(CALCULATE(COUNTROWS('Fct_EncuestaFormacion'), 'Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?] >= 4), [Encuesta Total Respuestas])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Encuesta Formacion
		lineageTag: 4444042a-1946-4ca9-97e1-6be11e260c0e

	measure 'Encuesta NPS Equivalente' =
			VAR _Total = COUNT('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
			VAR _Promotores = CALCULATE(COUNTROWS('Fct_EncuestaFormacion'), 'Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?] >= 5)
			VAR _Detractores = CALCULATE(COUNTROWS('Fct_EncuestaFormacion'), 'Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?] <= 3)
			RETURN
			    DIVIDE(_Promotores - _Detractores, _Total) * 100
		formatString: 0.0
		displayFolder: 03 Encuesta Formacion
		lineageTag: 3124a3a4-d281-4ef4-86de-717a9d7fd907

	measure 'Induccion Total Colaboradores' = COUNTROWS('Fct_Induccion')
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 3b28d7f6-130e-4260-bfe3-d840ffa3bdbb

	measure 'Induccion Colaboradores Unicos' = DISTINCTCOUNT('Fct_Induccion'[Colaborador_Key])
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 24f1148a-539f-4465-b843-3ed95f9b4368

	measure 'Induccion Aprobados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] IN { "APROBO", "APROBADO" })
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 0ac88ffa-7bc3-45b7-909d-a74217a123d4

	measure 'Induccion No Aprobados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] = "NO_APROBO")
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: ccffef5a-a187-4ddb-bd64-5755dbebdf3e

	measure 'Induccion Retiros' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] IN { "RETIRADO", "RENUNCIA" })
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: e4a40db9-198d-4158-9ccc-1cb3261f9fd2

	measure 'Induccion Onboarding' = DIVIDE([Induccion Onboarding Realizados], [Induccion Onboarding Participantes], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 7afb6905-9eeb-4444-8d1b-1dc1550c66ab

	measure 'Induccion Minutos Entrenamiento' = SUM('Fct_Induccion'[Min_Entrenamiento])
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: bf2ee324-989a-491e-a0f2-84923ea310db

	measure 'Induccion Horas Entrenamiento' = DIVIDE([Induccion Minutos Entrenamiento], 60)
		formatString: #,0.0
		displayFolder: 04 Induccion UC
		lineageTag: 5f477709-6bd7-46fb-b89d-9dbb43b5eef0

	measure 'Induccion Porcentaje Cumplimiento' = DIVIDE([Induccion Aprobados], [Induccion Total Colaboradores])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: e5679ca3-7b9c-4927-8d60-1e2a38d37b4f

	measure 'Induccion Tiempo Promedio Finalizacion Dias' = AVERAGE('Fct_Induccion'[Tiempo_Finalizacion_Dias])
		formatString: #,0.0
		displayFolder: 04 Induccion UC
		lineageTag: 4ecf7285-b950-42c1-b6bc-1382bd7a7848

	measure 'Induccion Cumplimiento Antes UC' = CALCULATE([Induccion Porcentaje Cumplimiento], 'Dim_SegmentoUC'[SegmentoUC_Key] = "Antes_UC")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 2ba24b53-d84d-4e15-963a-370651097629

	measure 'Induccion Cumplimiento UC 2025' = CALCULATE([Induccion Porcentaje Cumplimiento], 'Dim_SegmentoUC'[SegmentoUC_Key] = "UC_2025")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 706a9b2e-4a2f-4dc9-b4f6-a837fd99d2ed

	measure 'Induccion Cumplimiento UC 2026' = CALCULATE([Induccion Porcentaje Cumplimiento], 'Dim_SegmentoUC'[SegmentoUC_Key] = "UC_2026")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: f389252f-923d-498e-87d8-4298d4550f77

	measure 'Induccion Variacion UC2025 vs Antes UC' = [Induccion Cumplimiento UC 2025] - [Induccion Cumplimiento Antes UC]
		formatString: 0.0 pp;-0.0 pp;0.0 pp
		displayFolder: 04 Induccion UC
		lineageTag: 9c81cf4a-cd06-468c-affc-34a53cdc1fb7

	measure 'Induccion Variacion UC2026 vs UC2025' = [Induccion Cumplimiento UC 2026] - [Induccion Cumplimiento UC 2025]
		formatString: 0.0 pp;-0.0 pp;0.0 pp
		displayFolder: 04 Induccion UC
		lineageTag: 28128333-0bfc-4b7b-aa96-fd7f89a1e03d

	measure 'KPI Indice Aprendizaje' =
			VAR _Base =
			    {
			        [Plan Porcentaje Ejecucion],
			        [Plan Cobertura Asistencia],
			        [Encuesta Favorabilidad],
			        [Induccion Porcentaje Cumplimiento]
			    }
			RETURN
			    AVERAGEX(FILTER(_Base, NOT ISBLANK([Value])), [Value])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: 20367492-6403-4ce2-9065-99d64758cb84

	measure 'KPI Actividades Totales Gestionadas' = [Plan Actividades Planificadas] + [Asistencia Total Registros] + [Encuesta Total Respuestas] + [Induccion Total Colaboradores]
		formatString: #,0
		displayFolder: 00 KPIs Gerenciales
		lineageTag: 436e3d36-7e91-45a6-8731-006381405169

	measure 'Ranking Area Cumplimiento Plan' = RANKX(ALLSELECTED('Dim_Area'[Area]), [Plan Porcentaje Ejecucion], , DESC, Dense)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: 7f6aca7f-7192-4d86-8202-b826d0067630

	measure 'Ranking Area Cumplimiento Induccion' = RANKX(ALLSELECTED('Dim_Area'[Area]), [Induccion Porcentaje Cumplimiento], , DESC, Dense)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: 838ac55b-68aa-4f9b-890c-5e93178fb5a9

	measure 'Ranking Empresa Asistencia' = RANKX(ALLSELECTED('Dim_Empresa'[Empresa]), [Asistencia Total Asistentes], , DESC, Dense)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: b108b9b7-eb2f-4f23-889d-cf61f1f6492f

	measure 'Alerta Plan Bajo Cumplimiento' = IF(NOT ISBLANK([Plan Porcentaje Ejecucion]) && [Plan Porcentaje Ejecucion] < 0.8, 1, 0)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: 60c3836c-4cfd-4e27-a23a-dd03110ade43

	measure 'Alerta Induccion Bajo Cumplimiento' = IF(NOT ISBLANK([Induccion Porcentaje Cumplimiento]) && [Induccion Porcentaje Cumplimiento] < 0.9, 1, 0)
		formatString: #,0
		displayFolder: 05 Rankings y Alertas
		lineageTag: a0bf2452-432c-4a18-8ebe-c63f9fd5271d

	measure 'Hallazgo Plan' =
			""Plan: "" & FORMAT([Plan Porcentaje Ejecucion], ""0.0%"") &
			"" de ejecucion; brecha de "" & FORMAT([Plan Brecha Actividades], ""#,0"") & "" actividades.""
		displayFolder: 06 Hallazgos
		lineageTag: c90f3e51-b848-44f7-bfe2-c044e8551ac5

	measure 'Hallazgo Asistencia' =
			""Asistencia: "" & FORMAT([Asistencia Total Asistentes], ""#,0"") &
			"" registros y "" & FORMAT([% Cobertura], ""0.0%"") & "" de cobertura registrada en el plan.""
		displayFolder: 06 Hallazgos
		lineageTag: dd1611ff-cc0b-4c8b-bc5d-2eab245b0df8

	measure 'Hallazgo UC' =
			""UC: Antes "" & FORMAT([Induccion Cumplimiento Antes UC], ""0.0%"") &
			"", UC 2025 "" & FORMAT([Induccion Cumplimiento UC 2025], ""0.0%"") &
			"", UC 2026 "" & FORMAT([Induccion Cumplimiento UC 2026], ""0.0%"") & "".""
		displayFolder: 06 Hallazgos
		lineageTag: 910b7dbd-062d-48a9-8a26-9c7eda604bea

	measure 'Plan Eficacia Promedio' = DIVIDE(AVERAGE('Fct_PlanFormacion'[EFICACIA]), 100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Plan Formacion
		lineageTag: 7c112d7e-9a2c-4aae-925e-fdecb44a6c6a

	measure 'Plan Actividades Pendientes' = [Plan Actividades Vigentes] - [Plan Actividades Ejecutadas]
		formatString: #,0
		displayFolder: 01 Plan Formacion
		lineageTag: 3d4f4796-4656-460c-85ae-281be025cb69

	measure 'Plan Variacion Ejecutadas MoM' = [Plan Actividades Ejecutadas] - CALCULATE([Plan Actividades Ejecutadas], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: cb518286-cff8-4df5-b208-f5f8588f2a32

	measure 'Plan Variacion Ejecutadas MoM %' = DIVIDE([Plan Variacion Ejecutadas MoM], CALCULATE([Plan Actividades Ejecutadas], DATEADD('Dim_Calendario'[Date], -1, MONTH)))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: 85b0fc0f-6973-4584-b043-3938adc6d9a2

	measure 'Plan Variacion Ejecutadas YoY' = [Plan Actividades Ejecutadas] - CALCULATE([Plan Actividades Ejecutadas], SAMEPERIODLASTYEAR('Dim_Calendario'[Date]))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: 162123aa-1e9e-4298-ae3d-4de7e25f5fc9

	measure 'Plan Variacion Ejecutadas YoY %' = DIVIDE([Plan Variacion Ejecutadas YoY], CALCULATE([Plan Actividades Ejecutadas], SAMEPERIODLASTYEAR('Dim_Calendario'[Date])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: b47209f7-088c-491e-964e-c4454d69e423

	measure 'Asistencia Variacion MoM' = [Asistencia Total Asistentes] - CALCULATE([Asistencia Total Asistentes], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: 1461ce00-99be-433f-9bfd-fc3828401a21

	measure 'Asistencia Variacion MoM %' = DIVIDE([Asistencia Variacion MoM], CALCULATE([Asistencia Total Asistentes], DATEADD('Dim_Calendario'[Date], -1, MONTH)))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: fcd3c38b-ecb4-480e-b38d-4853b834bc87

	measure 'Asistencia Variacion YoY' = [Asistencia Total Asistentes] - CALCULATE([Asistencia Total Asistentes], SAMEPERIODLASTYEAR('Dim_Calendario'[Date]))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: 420b2312-0cd1-48a7-8dcd-756f9f52842a

	measure 'Asistencia Variacion YoY %' = DIVIDE([Asistencia Variacion YoY], CALCULATE([Asistencia Total Asistentes], SAMEPERIODLASTYEAR('Dim_Calendario'[Date])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: 9813eb66-418c-48b0-9710-677970200ba3

	measure 'Induccion Variacion Colaboradores MoM' = [Induccion Total Colaboradores] - CALCULATE([Induccion Total Colaboradores], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 07 Comparativos
		lineageTag: fa88eb05-9b5c-4742-806b-31938463215d

	measure 'Induccion Variacion Colaboradores MoM %' = DIVIDE([Induccion Variacion Colaboradores MoM], CALCULATE([Induccion Total Colaboradores], DATEADD('Dim_Calendario'[Date], -1, MONTH)))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: a166664c-36ef-4674-8226-07abdbece4bb

	measure 'Induccion Variacion Cumplimiento MoM' = [Induccion Porcentaje Cumplimiento] - CALCULATE([Induccion Porcentaje Cumplimiento], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: 0.0 pp;-0.0 pp;0.0 pp
		displayFolder: 07 Comparativos
		lineageTag: 747a66fd-67af-4f14-8826-1e2d27022fa5

	measure 'KPI Frente Pendiente' = BLANK()
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: ad78c626-132c-4dee-addc-e2167c6375a3

	measure 'KPI Nivel Cargo Pendiente' = BLANK()
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: 26162c48-6994-43d9-8f3b-01f8af6b5a24

	measure 'Encuesta Calificacion Satisfaccion Formacion' = AVERAGE('Fct_EncuestaFormacion'[En general, ¿Qué tan satisfecho te encuentras con la formación recibida?])
		formatString: 0.00
		displayFolder: 03 Encuesta Formacion
		lineageTag: 3f212dda-cebe-415e-9990-10491b437488

	measure 'Encuesta Favorabilidad Variacion MoM' = [Encuesta Favorabilidad] - CALCULATE([Encuesta Favorabilidad], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: 8098de79-6685-468c-8a65-d28dd3425b31

	measure 'Encuesta Favorabilidad Variacion YoY' = [Encuesta Favorabilidad] - CALCULATE([Encuesta Favorabilidad], SAMEPERIODLASTYEAR('Dim_Calendario'[Date]))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 07 Comparativos
		lineageTag: eb2d8e62-aef9-4d7d-bde2-9967ea9477d5

	measure 'HC Total Colaborador Mes' = DISTINCTCOUNT('Dim_ColaboradorHC'[Colaborador_Key])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: f38f73e4-280f-4b41-9ed2-f93ca77a7a86

	measure 'HC Total Colaboradores Unicos' = DISTINCTCOUNT('Dim_ColaboradorHC'[Numero_Documento])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: d74aff9e-857b-4aec-804e-4bb2ce4f19fd

	measure 'HC Recuento Tipo Cargo' = COUNTA('Dim_ColaboradorHC'[Tipo_Cargo])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: 9f4f8060-aa3c-4b60-ba1f-ecb70ec5c987

	measure 'HC Porcentaje Tipo Cargo' = DIVIDE([HC Recuento Tipo Cargo], CALCULATE([HC Recuento Tipo Cargo], ALLSELECTED('Dim_ColaboradorHC'[Tipo_Cargo])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 08 Headcount HC
		lineageTag: 436ae1ed-4b2c-4a64-85ac-14f785500dd6

	measure 'HC Tipos Cargo' = DISTINCTCOUNT('Dim_ColaboradorHC'[Tipo_Cargo])
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: b29411ac-359e-49a8-b86a-4b21cf792b49

	measure 'Asistencia Registros HC Match' =
			VAR _KeysHC = VALUES('Dim_ColaboradorHC'[Colaborador_Key])
			RETURN
			    CALCULATE(
			        [Asistencia Total Registros],
			        TREATAS(_KeysHC, 'Fct_AsistenciaFormacion'[Colaborador_Key])
			    )
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: d21be951-d44a-4d57-a66d-dd46c9b1caa4

	measure 'Asistencia Colaborador Mes HC Match' =
			VAR _KeysHC = VALUES('Dim_ColaboradorHC'[Colaborador_Key])
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT('Fct_AsistenciaFormacion'[Colaborador_Key]),
			        TREATAS(_KeysHC, 'Fct_AsistenciaFormacion'[Colaborador_Key])
			    )
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: 0c0ebe99-e406-4e2f-81f0-21e8585c88ee

	measure 'Asistencia Distribucion Tipo Cargo %' = DIVIDE([Asistencia Registros HC Match], CALCULATE([Asistencia Registros HC Match], ALLSELECTED('Dim_ColaboradorHC'[Tipo_Cargo])))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 08 Headcount HC
		lineageTag: bfafa5d7-6dd4-487e-be5a-a37de2ed377c

	measure 'Asistencia Registros Sin HC Match' =
			VAR _Total =
			    CALCULATE(
			        [Asistencia Total Registros],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			VAR _Match =
			    CALCULATE(
			        [Asistencia Registros HC Match],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			RETURN
			    _Total - _Match
		formatString: #,0
		displayFolder: 08 Headcount HC
		lineageTag: 04f63099-e053-40aa-a2b0-d36dead67715

	measure 'Asistencia Porcentaje HC Match' =
			VAR _Total =
			    CALCULATE(
			        [Asistencia Total Registros],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			VAR _Match =
			    CALCULATE(
			        [Asistencia Registros HC Match],
			        REMOVEFILTERS('Dim_ColaboradorHC')
			    )
			RETURN
			    DIVIDE(_Match, _Total)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 08 Headcount HC
		lineageTag: 412f9f00-b82b-4f2d-9a8a-7252d1bc77c2

	measure 'Induccion Onboarding Realizados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[EstadoInduccion_Key] IN { "APROBO", "APROBADO" })
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 06e6c60a-5132-4683-b6dc-e6feef265df3

	measure 'Induccion Onboarding Participantes' = CALCULATE(DISTINCTCOUNT('Fct_Induccion'[Colaborador_Key]), 'Fct_Induccion'[EstadoInduccion_Key] <> "RENUNCIA")
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: ea4f03a1-dda9-4f02-b869-fe33d44c4736

	measure 'Induccion Entrenamiento Realizados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[Entrenamiento] = "SI")
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 125b628c-9be2-452e-93cf-4e09cebcaacf

	measure 'Induccion Entrenamiento Base' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[Entrenamiento] = "SI" || 'Fct_Induccion'[Entrenamiento] = "PENDIENTE" || ISBLANK('Fct_Induccion'[Entrenamiento]))
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 9755415a-51b9-4f80-a07d-cbf78089cb75

	measure 'Induccion Porcentaje Entrenamiento' = DIVIDE([Induccion Entrenamiento Realizados], [Induccion Entrenamiento Base], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: 58a9b4a5-e29c-4872-ac96-a80a86f57d8e

	measure 'Induccion Entrenamiento Neto Realizados' = CALCULATE(COUNTROWS('Fct_Induccion'), 'Fct_Induccion'[Archivo] = 50)
		formatString: #,0
		displayFolder: 04 Induccion UC
		lineageTag: 078f9c7c-99d4-44a7-8e05-7188a861ff55

	measure 'Induccion Porcentaje Entrenamiento Neto' = DIVIDE([Induccion Entrenamiento Neto Realizados], [Induccion Entrenamiento Base], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 04 Induccion UC
		lineageTag: f65cb718-1c4d-4332-9ad3-fc3614da6098

	measure 'PDI Total' = COUNTROWS('Fct_Seguimiento_PDI')
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 5a0f5c43-7197-4b55-bdb5-78b021eb2a9e

	measure 'PDI Colaboradores Unicos' = DISTINCTCOUNT('Fct_Seguimiento_PDI'[Identificacion_Colaborador])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: b3fb1782-2f58-46f8-9745-391f13483a56

	measure 'PDI Motivos Distintos' = DISTINCTCOUNT('Dim_MotivoPDI'[MotivoPDI_Key])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 7ba1e69c-e498-4147-b910-d15c197deac1

	measure 'PDI Jefes Con PDI' = DISTINCTCOUNT('Fct_Seguimiento_PDI'[Jefe_Inmediato])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: db9526bf-b4fd-4244-a819-65b4d9b6fcc0

	measure 'PDI Cargos Con PDI' = DISTINCTCOUNT('Fct_Seguimiento_PDI'[Cargo])
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 6c748cfe-5f00-4a07-8812-22f9772fc8ee

	measure 'PDI Avance Promedio' =
			VAR _Avance = AVERAGE('Fct_Seguimiento_PDI'[Avance_PDI])
			RETURN IF(_Avance > 1, DIVIDE(_Avance, 100), _Avance)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: d3c5fd73-5514-452a-9f17-7d6b4acc146f

	measure 'PDI Finalizados' =
			CALCULATE(
			    [PDI Total],
			    'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO" }
			)
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: f8448f24-385d-40ac-bd45-aaac5564f3ac

	measure 'PDI Activos' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        NOT (
			            'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			        )
			    )
			)
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 950fa908-217a-41c9-9faa-4e9652af48b9

	measure 'PDI Pendientes' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "PENDIENTE", "EN PROCESO", "ACTIVO", "" }
			            || ISBLANK('Fct_Seguimiento_PDI'[EstadoPDI_Key])
			    )
			)
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 4425b154-c390-4b36-b8e2-7db2c812e5fd

	measure 'PDI Porcentaje Activos' = DIVIDE([PDI Activos], [PDI Total], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: 15cc444a-841d-4c49-b4c0-7c3cf976c4f2

	measure 'PDI Porcentaje Por Estado' = DIVIDE([PDI Total], CALCULATE([PDI Total], ALLSELECTED('Dim_EstadoPDI'[Estado_PDI])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: 707e9860-ed38-4dc1-a671-8117f3762692

	measure 'PDI Porcentaje Por Motivo' = DIVIDE([PDI Total], CALCULATE([PDI Total], ALLSELECTED('Dim_MotivoPDI'[Motivo_PDI])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: ebfc3785-f433-4bea-818b-bb45d4c0cb4b

	measure 'PDI Avance Cero' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        COALESCE('Fct_Seguimiento_PDI'[Avance_PDI], 0) = 0
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 086d71ab-3c67-4838-b895-5970f0cb7e0c

	measure 'PDI Bajo Avance' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        VAR _Avance = IF('Fct_Seguimiento_PDI'[Avance_PDI] > 1, DIVIDE('Fct_Seguimiento_PDI'[Avance_PDI], 100), 'Fct_Seguimiento_PDI'[Avance_PDI])
			        RETURN _Avance > 0 && _Avance < 0.4
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 9e73a3c1-e8bd-42f3-97d3-cd63918c668c

	measure 'PDI Vencidos' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        NOT ISBLANK('Fct_Seguimiento_PDI'[Fecha_Fin])
			            && 'Fct_Seguimiento_PDI'[Fecha_Fin] < TODAY()
			            && NOT (
			                'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			            )
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 310e0db2-f0d1-4d70-a8b7-5b8147cfcc09

	measure 'PDI Proximos A Vencer' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        NOT ISBLANK('Fct_Seguimiento_PDI'[Fecha_Fin])
			            && 'Fct_Seguimiento_PDI'[Fecha_Fin] >= TODAY()
			            && 'Fct_Seguimiento_PDI'[Fecha_Fin] <= TODAY() + 30
			            && NOT (
			                'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			            )
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: e7d2735e-d44e-4d17-8a64-49ad6772b7ab

	measure 'PDI Acompanamientos Programados' =
			CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_1] IN { "P", "E", "PROGRAMADO", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_2] IN { "P", "E", "PROGRAMADO", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_3] IN { "P", "E", "PROGRAMADO", "EJECUTADO" })
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 2930cd49-066d-46c1-8af5-c7b11eea1c81

	measure 'PDI Acompanamientos Ejecutados' =
			CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_1] IN { "E", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_2] IN { "E", "EJECUTADO" })
			    + CALCULATE([PDI Total], 'Fct_Seguimiento_PDI'[Acompanamiento_3] IN { "E", "EJECUTADO" })
		formatString: #,0
		displayFolder: 09 Desarrollo PDI
		lineageTag: 7b38b540-17ee-4260-8b71-af862d8ebc4f

	measure 'PDI Cumplimiento Acompanamientos' = DIVIDE([PDI Acompanamientos Ejecutados], [PDI Acompanamientos Programados], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 09 Desarrollo PDI
		lineageTag: c052eeff-33ed-4762-b7b8-09026516a598

	measure 'PDI Alertas Criticas' =
			CALCULATE(
			    [PDI Total],
			    FILTER(
			        'Fct_Seguimiento_PDI',
			        VAR _Avance = IF('Fct_Seguimiento_PDI'[Avance_PDI] > 1, DIVIDE('Fct_Seguimiento_PDI'[Avance_PDI], 100), 'Fct_Seguimiento_PDI'[Avance_PDI])
			        VAR _Vencido =
			            NOT ISBLANK('Fct_Seguimiento_PDI'[Fecha_Fin])
			                && 'Fct_Seguimiento_PDI'[Fecha_Fin] < TODAY()
			                && NOT (
			                    'Fct_Seguimiento_PDI'[EstadoPDI_Key] IN { "FINALIZADO", "CERRADO", "COMPLETADO", "CANCELADO" }
			                )
			        RETURN COALESCE(_Avance, 0) = 0 || (_Avance > 0 && _Avance < 0.4) || _Vencido
			    )
			)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 5acc123f-755e-4c25-85f0-8f26d30a6718

	measure 'PDI Ranking Area Total' = RANKX(ALLSELECTED('Dim_Area'[Area]), [PDI Total], , DESC, Dense)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: b35f3a01-d64d-475a-92b0-984816763f7b

	measure 'PDI Ranking Jefe Bajo Avance' = RANKX(ALLSELECTED('Fct_Seguimiento_PDI'[Jefe_Inmediato]), [PDI Bajo Avance], , DESC, Dense)
		formatString: #,0
		displayFolder: 10 Desarrollo Alertas
		lineageTag: 4d23f49d-100d-4fcd-9bc6-af3e454183f7

	measure 'KPI Indice Desarrollo' =
			VAR _SinVencidos = 1 - DIVIDE([PDI Vencidos], [PDI Total], 0)
			VAR _Base =
			    {
			        [PDI Avance Promedio],
			        [PDI Cumplimiento Acompanamientos],
			        _SinVencidos
			    }
			RETURN
			    AVERAGEX(FILTER(_Base, NOT ISBLANK([Value])), [Value])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 00 KPIs Gerenciales
		lineageTag: e1b75bcf-3df0-489e-9ccb-f0d3d97846fb

	measure 'HTML Inicio Corporativo Propuesta 1' =
			VAR _FA = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			VAR _Horas = IF(ISBLANK([Plan Horas Formacion]), "-", FORMAT([Plan Horas Formacion], "#,0"))
			VAR _Cob = IF(ISBLANK([% Cobertura]), "-", FORMAT([% Cobertura], "0.0%"))
			VAR _Sat = IF(ISBLANK([Encuesta Favorabilidad]), "-", FORMAT([Encuesta Favorabilidad], "0.0%"))
			VAR _Onb = IF(ISBLANK([Induccion Porcentaje Cumplimiento]), "-", FORMAT([Induccion Porcentaje Cumplimiento], "0.0%"))
			VAR _Ent = IF(ISBLANK([Induccion Porcentaje Entrenamiento Neto]), "-", FORMAT([Induccion Porcentaje Entrenamiento Neto], "0.0%"))
			VAR _IApz = IF(ISBLANK([KPI Indice Aprendizaje]), "-", FORMAT([KPI Indice Aprendizaje], "0.0%"))
			VAR _PDIAct = IF(ISBLANK([PDI Activos]), "-", FORMAT([PDI Activos], "#,0"))
			VAR _PDIAvz = IF(ISBLANK([PDI Avance Promedio]), "-", FORMAT([PDI Avance Promedio], "0.0%"))
			VAR _PDIAlt = IF(ISBLANK([PDI Alertas Criticas]), "-", FORMAT([PDI Alertas Criticas], "#,0"))
			VAR _Acomp = IF(ISBLANK([PDI Cumplimiento Acompanamientos]), "-", FORMAT([PDI Cumplimiento Acompanamientos], "0.0%"))
			VAR _IDes = IF(ISBLANK([KPI Indice Desarrollo]), "-", FORMAT([KPI Indice Desarrollo], "0.0%"))
			VAR _CtaTexto =
			    SWITCH(
			        _FA,
			        "Aprendizaje", "Ver tablero completo de Aprendizaje",
			        "Desarrollo", "Ver resumen ejecutivo de Desarrollo",
			        "Bienestar y Clima", "Ver Entrevista de Retiro",
			        "Desempeno", "Ver frente Desempe&ntilde;o",
			        "Ver tablero completo de Aprendizaje"
			    )
			VAR _LeftContent =
			    IF(_FA = "Aprendizaje",
			        "<div style='font-size:11px;color:#F7931E;font-weight:800;text-transform:uppercase;letter-spacing:1.4px;'>Frente activo</div>" &
			        "<div style='font-size:30px;font-weight:800;margin-top:4px;color:#000032;'>Aprendizaje</div>" &
			        "<div style='font-size:12px;color:#53657D;line-height:17px;margin-top:7px;'>Formaci&oacute;n, cobertura, satisfacci&oacute;n, onboarding y entrenamiento inicial.</div>" &
			        "<div style='display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:15px;'>" &
			        "<div style='border-left:4px solid #F7931E;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Horas formaci&oacute;n</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Horas & "</div></div>" &
			        "<div style='border-left:4px solid #1B487F;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Cobertura</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Cob & "</div></div>" &
			        "<div style='border-left:4px solid #1A3059;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Satisfacci&oacute;n</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Sat & "</div></div>" &
			        "<div style='border-left:4px solid #0B1C35;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Onboarding</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Onb & "</div></div>" &
			        "</div><div style='display:flex;gap:10px;margin-top:11px;'>" &
			        "<div style='flex:1;background:#0B1C35;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Entrenamiento neto</div><div style='font-size:21px;font-weight:800;'>" & _Ent & "</div></div>" &
			        "<div style='flex:1;background:#1B487F;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Indice Aprendizaje</div><div style='font-size:21px;font-weight:800;'>" & _IApz & "</div></div>" &
			        "</div><div style='position:absolute;left:22px;bottom:26px;width:548px;text-align:center;background:#F7931E;color:#fff;border-radius:8px;padding:9px;font-size:11px;font-weight:800;box-sizing:border-box;'>" & _CtaTexto & "</div>",
			    IF(_FA = "Desarrollo",
			        "<div style='font-size:11px;color:#F7931E;font-weight:800;text-transform:uppercase;letter-spacing:1.4px;'>Frente activo</div>" &
			        "<div style='font-size:30px;font-weight:800;margin-top:4px;color:#000032;'>Desarrollo</div>" &
			        "<div style='font-size:12px;color:#53657D;line-height:17px;margin-top:7px;'>Planes de Desarrollo Individual, avance, acompa&ntilde;amientos y alertas.</div>" &
			        "<div style='display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:15px;'>" &
			        "<div style='border-left:4px solid #F7931E;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>PDI activos</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _PDIAct & "</div></div>" &
			        "<div style='border-left:4px solid #1B487F;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Avance promedio</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _PDIAvz & "</div></div>" &
			        "<div style='border-left:4px solid #1A3059;background:#F7F9FC;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#53657D;'>Acompa&ntilde;amientos</div><div style='font-size:25px;font-weight:800;color:#1B487F;'>" & _Acomp & "</div></div>" &
			        "<div style='border-left:4px solid #E85D24;background:#FFF4F1;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#9D3B2A;'>Alertas criticas</div><div style='font-size:25px;font-weight:800;color:#E85D24;'>" & _PDIAlt & "</div></div>" &
			        "</div><div style='display:flex;gap:10px;margin-top:11px;'>" &
			        "<div style='flex:1;background:#0B1C35;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Indice Desarrollo</div><div style='font-size:21px;font-weight:800;'>" & _IDes & "</div></div>" &
			        "<div style='flex:1;background:#1B487F;color:#fff;border-radius:8px;padding:11px 13px;'><div style='font-size:10px;color:#b8c8de;'>Avance PDI</div><div style='font-size:21px;font-weight:800;'>" & _PDIAvz & "</div></div>" &
			        "</div><div style='position:absolute;left:22px;bottom:26px;width:548px;text-align:center;background:#F7931E;color:#fff;border-radius:8px;padding:9px;font-size:11px;font-weight:800;box-sizing:border-box;'>" & _CtaTexto & "</div>",
			        "<div style='font-size:11px;color:#1B487F;font-weight:800;text-transform:uppercase;letter-spacing:1.4px;'>" & IF(_FA = "Desempeno", "Proxima fase", "Frente iniciado") & "</div>" &
			        "<div style='font-size:30px;font-weight:800;margin-top:4px;color:#1A3059;'>" & IF(_FA = "Desempeno", "Desempe&ntilde;o", "Bienestar y Clima") & "</div>" &
			        "<div style='font-size:12px;color:#53657D;line-height:17px;margin-top:7px;'>" & IF(_FA = "Desempeno", "Evaluaci&oacute;n de desempe&ntilde;o, metas y seguimiento gerencial.", "Entrevista de Retiro activa con roadmap de clima laboral, eNPS y plan de bienestar.") & "</div>" &
			        "<div style='margin-top:32px;background:#EBF0F8;border-radius:14px;padding:30px 24px;text-align:center;'>" &
			        "<div style='font-size:40px;'>" & IF(_FA = "Desempeno", "&#128200;", "&#127774;") & "</div>" &
			        "<div style='font-size:17px;font-weight:800;color:#1A3059;margin-top:12px;'>" & IF(_FA = "Desempeno", "En preparacion", "Entrevista de Retiro activa") & "</div>" &
			        "<div style='font-size:12px;color:#53657D;margin-top:9px;line-height:17px;'>" & IF(_FA = "Desempeno", "Este frente forma parte del roadmap corporativo 2026 y estara disponible en la siguiente fase de implementacion.", "Incluye Entrevista de Retiro, Planes de trabajo de Clima Laboral, eNPS de actividades de Bienestar y Cumplimiento del Plan de Bienestar.") & "</div>" &
			        "<div style='margin-top:18px;display:inline-block;border:1.5px solid #1B487F;border-radius:20px;padding:7px 20px;font-size:11px;color:#1B487F;font-weight:700;'>" & IF(_FA = "Desempeno", "Roadmap 2026", "Bienestar en construccion") & "</div></div>" &
			        "<div style='position:absolute;left:22px;bottom:26px;width:548px;text-align:center;background:#F7931E;color:#fff;border-radius:8px;padding:9px;font-size:11px;font-weight:800;box-sizing:border-box;'>" & _CtaTexto & "</div>"
			    ))
			VAR _LeftBg = IF(_FA = "Aprendizaje" || _FA = "Desarrollo" || _FA = "Bienestar y Clima", "#ffffff", "#F9FAFC")
			VAR _LeftBorder = IF(_FA = "Aprendizaje" || _FA = "Desarrollo" || _FA = "Bienestar y Clima", "#F7931E", "#DCE5F2")
			VAR _Left = "<div style='position:absolute;left:34px;top:190px;width:592px;height:494px;background:" & _LeftBg & ";border:2px solid " & _LeftBorder & ";border-radius:10px;box-shadow:0 10px 28px rgba(11,28,53,.08);padding:22px;box-sizing:border-box;'>" & _LeftContent & "</div>"
			VAR _CApz = IF(_FA = "Aprendizaje", "<div style='background:#0B1C35;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(11,28,53,.18);'>", "<div style='background:#fff;border:1px solid #DCE5F2;border-radius:10px;padding:20px;'>")
			VAR _CDes = IF(_FA = "Desarrollo", "<div style='background:#1B487F;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(27,72,127,.18);'>", "<div style='background:#fff;border:1px solid #E8C99A;border-radius:10px;padding:20px;'>")
			VAR _CDep = IF(_FA = "Desempeno", "<div style='background:#1A3059;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(26,48,89,.18);'>", "<div style='background:#fff;border:1px solid #DCE5F2;border-radius:10px;padding:20px;'>")
			VAR _CByC = IF(_FA = "Bienestar y Clima", "<div style='background:#1A3059;color:#fff;border-radius:10px;padding:20px;border:2px solid #F7931E;box-shadow:0 8px 22px rgba(26,48,89,.18);'>", "<div style='background:#fff;border:1px solid #DCE5F2;border-radius:10px;padding:20px;'>")
			VAR _Right =
			    "<div style='position:absolute;left:650px;top:190px;width:598px;height:494px;display:grid;grid-template-columns:1fr 1fr;gap:16px;'>" &
			    _CApz & "<div style='font-size:11px;color:#F7931E;font-weight:800;'>01</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Aprendizaje","color:#fff;","color:#1A3059;") & "'>Aprendizaje</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Aprendizaje","color:#cbd8e8;","color:#53657D;") & "'>MVP operativo con indicadores activos y lectura ejecutiva.</div><div style='margin-top:13px;height:4px;background:" & IF(_FA="Aprendizaje","#F7931E","#DCE5F2") & ";border-radius:4px;'></div><div style='margin-top:9px;display:grid;grid-template-columns:1fr 1fr;gap:6px;'><div style='background:#F7931E;color:#fff;border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Plan</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Cobertura</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Satisfacci&oacute;n</div><div style='background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Inducci&oacute;n</div><div style='grid-column:1 / span 2;background:rgba(255,255,255,.12);color:" & IF(_FA="Aprendizaje","#fff","#1A3059") & ";border:1px solid " & IF(_FA="Aprendizaje","rgba(255,255,255,.22)","#DCE5F2") & ";border-radius:12px;padding:5px 9px;font-size:9px;font-weight:800;text-align:center;'>Focos</div></div></div>" &
			    _CDep & "<div style='font-size:11px;color:" & IF(_FA="Desempeno","#F7931E","#1B487F") & ";font-weight:800;'>02</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Desempeno","color:#fff;","color:#1A3059;") & "'>Desempe&ntilde;o</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Desempeno","color:#d9e4f2;","color:#53657D;") & "'>Medicion y seguimiento gerencial de resultados.</div><div style='margin-top:16px;display:inline-block;border:1px solid " & IF(_FA="Desempeno","#d9e4f2","#DCE5F2") & ";border-radius:12px;padding:3px 9px;font-size:10px;color:" & IF(_FA="Desempeno","#d9e4f2","#1A3059") & ";'>Roadmap</div></div>" &
			    _CDes & "<div style='font-size:11px;color:#F7931E;font-weight:800;'>03</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Desarrollo","color:#fff;","color:#1A3059;") & "'>Desarrollo</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Desarrollo","color:#d9e4f2;","color:#53657D;") & "'>PDI activos. Avance: " & _PDIAvz & ".</div><div style='margin-top:16px;display:inline-block;background:#FFF2E5;color:#9D5600;border-radius:12px;padding:3px 9px;font-size:10px;font-weight:700;'>En construccion</div></div>" &
			    _CByC & "<div style='font-size:11px;color:" & IF(_FA="Bienestar y Clima","#F7931E","#1B487F") & ";font-weight:800;'>04</div><div style='font-size:19px;font-weight:800;margin-top:7px;" & IF(_FA="Bienestar y Clima","color:#fff;","color:#1A3059;") & "'>Bienestar y Clima</div><div style='font-size:10px;line-height:15px;margin-top:8px;" & IF(_FA="Bienestar y Clima","color:#d9e4f2;","color:#53657D;") & "'>Entrevista de Retiro, Clima Laboral, eNPS y Plan de Bienestar.</div><div style='display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:12px;'><div style='border-left:3px solid #F7931E;background:" & IF(_FA="Bienestar y Clima","rgba(255,255,255,.10)","#F7F9FC") & ";border-radius:7px;padding:6px 7px;font-size:9px;'>Entrevista de Retiro</div><div style='background:" & IF(_FA="Bienestar y Clima","rgba(255,255,255,.10)","#F7F9FC") & ";border-radius:7px;padding:6px 7px;font-size:9px;'>Planes Clima Laboral</div><div style='background:" & IF(_FA="Bienestar y Clima","rgba(255,255,255,.10)","#F7F9FC") & ";border-radius:7px;padding:6px 7px;font-size:9px;'>eNPS Bienestar</div><div style='background:" & IF(_FA="Bienestar y Clima","rgba(255,255,255,.10)","#F7F9FC") & ";border-radius:7px;padding:6px 7px;font-size:9px;'>Plan Bienestar</div></div></div>" &
			    "</div>"
			RETURN
			"<div style='width:1280px;height:720px;box-sizing:border-box;position:relative;background:#ffffff;font-family:Outfit,Segoe UI,Arial,sans-serif;color:#0B1C35;overflow:hidden;'>" &
			"<div style='height:88px;background:#0B1C35;color:#fff;padding:20px 34px;box-sizing:border-box;display:flex;justify-content:space-between;align-items:center;'>" &
			"<div><div style='font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#F7931E;font-weight:700;'>Dashboard Corporativo &middot; Grupo LEMCO</div><div style='font-size:25px;line-height:29px;font-weight:800;margin-top:5px;'>Inicio Corporativo</div></div>" &
			"<div style='font-size:10px;color:#7A9EC2;'>Selecciona un frente &rarr;</div></div>" &
			"<div style='position:absolute;left:34px;top:104px;width:1214px;height:82px;background:#ffffff;border:1px solid #DCE5F2;border-radius:14px;box-sizing:border-box;box-shadow:0 10px 28px rgba(11,28,53,.07);overflow:hidden;'>" &
			"<div style='position:absolute;left:0;top:0;width:7px;height:82px;background:#F7931E;'></div>" &
			"<div style='position:absolute;left:22px;top:17px;width:178px;'><div style='font-size:10px;font-weight:900;color:#0B1C35;text-transform:uppercase;letter-spacing:1px;'>Contexto de an&aacute;lisis</div><div style='font-size:9px;color:#6B7D93;line-height:13px;margin-top:5px;'>Filtros activos para la lectura ejecutiva del home.</div></div>" &
			"<div style='position:absolute;left:214px;top:12px;width:96px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>A&ntilde;o</div></div>" &
			"<div style='position:absolute;left:322px;top:12px;width:110px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Mes</div></div>" &
			"<div style='position:absolute;left:444px;top:12px;width:136px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Empresa</div></div>" &
			"<div style='position:absolute;left:592px;top:12px;width:136px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Area</div></div>" &
			"<div style='position:absolute;left:740px;top:12px;width:144px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Tipo formaci&oacute;n</div></div>" &
			"<div style='position:absolute;left:896px;top:12px;width:144px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Modalidad</div></div>" &
			"<div style='position:absolute;left:1052px;top:12px;width:186px;height:58px;background:#F7F9FC;border:1px solid #E6EEF5;border-radius:8px;box-sizing:border-box;padding:7px 9px;'><div style='font-size:9px;color:#1A3059;font-weight:800;'>Segmento UC</div></div>" &
			"</div>" &
			_Left &
			_Right &
			"</div>"
		displayFolder: 11 HTML Propuestas
		lineageTag: 1cb83d75-76db-4da5-b3ad-558aa192e4d5

	measure 'HTML Inicio Corporativo Propuesta 2' =
			VAR _Horas = IF(ISBLANK([Plan Horas Formacion]), "-", FORMAT([Plan Horas Formacion], "#,0"))
			VAR _Cobertura = IF(ISBLANK([% Cobertura]), "-", FORMAT([% Cobertura], "0.0%"))
			VAR _Satisfaccion = IF(ISBLANK([Encuesta Favorabilidad]), "-", FORMAT([Encuesta Favorabilidad], "0.0%"))
			VAR _Entrenamiento = IF(ISBLANK([Induccion Porcentaje Entrenamiento Neto]), "-", FORMAT([Induccion Porcentaje Entrenamiento Neto], "0.0%"))
			VAR _IndiceAprendizaje = IF(ISBLANK([KPI Indice Aprendizaje]), "-", FORMAT([KPI Indice Aprendizaje], "0.0%"))
			VAR _IndiceDesarrollo = IF(ISBLANK([KPI Indice Desarrollo]), "-", FORMAT([KPI Indice Desarrollo], "0.0%"))
			RETURN
			"<div style='width:1280px;height:720px;box-sizing:border-box;position:relative;background:#F4F7FB;font-family:Outfit,Segoe UI,Arial,sans-serif;color:#0B1C35;overflow:hidden;'>" &
			"<div style='position:absolute;left:0;top:0;width:1280px;height:220px;background:linear-gradient(135deg,#000032 0%,#1A3059 54%,#1B487F 100%);color:#ffffff;'>" &
			"<div style='position:absolute;left:42px;top:26px;width:600px;'><div style='font-size:12px;color:#F7931E;letter-spacing:2px;text-transform:uppercase;font-weight:800;'>Grupo LEMCO | People Analytics</div><div style='font-size:35px;line-height:41px;font-weight:850;margin-top:8px;'>Dashboard Corporativo de Desarrollo Organizacional</div><div style='font-size:14px;line-height:20px;color:#dbe6f5;margin-top:12px;width:86%;'>Portada ejecutiva para monitorear frentes de gesti&oacute;n humana con lectura r&aacute;pida, comparaci&oacute;n y priorizaci&oacute;n.</div></div>" &
			"<div style='position:absolute;right:42px;top:34px;width:320px;height:138px;background:rgba(255,255,255,.11);border:1px solid rgba(255,255,255,.25);border-radius:14px;padding:18px;box-sizing:border-box;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>Frente activo</div><div style='font-size:28px;font-weight:850;margin-top:4px;'>Aprendizaje</div><div style='display:flex;gap:10px;margin-top:18px;'><div style='flex:1;'><div style='font-size:10px;color:#bfd0e4;'>Indice</div><div style='font-size:22px;font-weight:800;'>" & _IndiceAprendizaje & "</div></div><div style='flex:1;'><div style='font-size:10px;color:#bfd0e4;'>Desarrollo</div><div style='font-size:22px;font-weight:800;'>" & _IndiceDesarrollo & "</div></div></div></div></div>" &
			"<div style='position:absolute;left:36px;top:136px;width:1212px;height:92px;background:#ffffff;border-radius:14px;box-shadow:0 14px 38px rgba(11,28,53,.16);border:1px solid #DCE5F2;'><div style='position:absolute;left:18px;top:12px;font-size:12px;font-weight:800;color:#1A3059;text-transform:uppercase;letter-spacing:.8px;'>Explorar por</div></div>" &
			"<div style='position:absolute;left:42px;top:256px;width:1210px;height:164px;display:grid;grid-template-columns:1.2fr .8fr .8fr .8fr;gap:16px;'>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:22px;box-shadow:0 8px 24px rgba(11,28,53,.07);'><div style='font-size:13px;color:#F7931E;font-weight:800;'>Aprendizaje</div><div style='font-size:25px;font-weight:850;margin-top:4px;'>Gestion activa del MVP</div><div style='font-size:13px;color:#53657D;line-height:18px;margin-top:8px;'>Indicadores de formaci&oacute;n, cobertura, satisfacci&oacute;n y entrenamiento.</div><div style='height:7px;background:#E8EEF6;border-radius:8px;margin-top:22px;'><div style='width:78%;height:7px;background:#F7931E;border-radius:8px;'></div></div></div>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:20px;'><div style='font-size:12px;color:#53657D;'>Horas</div><div style='font-size:34px;font-weight:850;color:#1B487F;'>" & _Horas & "</div><div style='font-size:12px;color:#53657D;margin-top:8px;'>Formaci&oacute;n planificada y ejecutada.</div></div>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:20px;'><div style='font-size:12px;color:#53657D;'>Cobertura</div><div style='font-size:34px;font-weight:850;color:#1B487F;'>" & _Cobertura & "</div><div style='font-size:12px;color:#53657D;margin-top:8px;'>Asistencia frente al p&uacute;blico objetivo.</div></div>" &
			"<div style='background:#ffffff;border-radius:14px;border:1px solid #E1E8F2;padding:20px;'><div style='font-size:12px;color:#53657D;'>Satisfacci&oacute;n</div><div style='font-size:34px;font-weight:850;color:#1B487F;'>" & _Satisfaccion & "</div><div style='font-size:12px;color:#53657D;margin-top:8px;'>Favorabilidad de las respuestas.</div></div></div>" &
			"<div style='position:absolute;left:42px;top:448px;width:1210px;height:164px;display:grid;grid-template-columns:repeat(4,1fr);gap:16px;'>" &
			"<div style='background:#0B1C35;color:#ffffff;border-radius:16px;padding:20px;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>Activo</div><div style='font-size:23px;font-weight:850;margin-top:9px;'>Aprendizaje</div><div style='font-size:12px;color:#cbd8e8;line-height:17px;margin-top:8px;'>Entrenamiento neto: " & _Entrenamiento & ".</div></div>" &
			"<div style='background:#ffffff;border:1px solid #DCE5F2;border-radius:16px;padding:20px;'><div style='font-size:12px;color:#1B487F;font-weight:800;'>Pr&oacute;xima fase</div><div style='font-size:23px;font-weight:850;margin-top:9px;'>Desempe&ntilde;o</div><div style='font-size:12px;color:#53657D;line-height:17px;margin-top:8px;'>Espacio reservado para evaluaci&oacute;n y seguimiento.</div></div>" &
			"<div style='background:#ffffff;border:1px solid #F7931E;border-radius:16px;padding:20px;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>En construcci&oacute;n</div><div style='font-size:23px;font-weight:850;margin-top:9px;'>Desarrollo</div><div style='font-size:12px;color:#53657D;line-height:17px;margin-top:8px;'>PDI y acompa&ntilde;amientos en seguimiento.</div></div>" &
			"<div style='background:#ffffff;border:1px solid #DCE5F2;border-radius:16px;padding:18px;'><div style='font-size:12px;color:#F7931E;font-weight:800;'>Frente iniciado</div><div style='font-size:23px;font-weight:850;margin-top:7px;'>Bienestar y Clima</div><div style='display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px;font-size:10px;color:#1A3059;'><div style='border-left:3px solid #F7931E;background:#F7F9FC;border-radius:7px;padding:7px;'>Entrevista de Retiro</div><div style='background:#F7F9FC;border-radius:7px;padding:7px;'>Planes Clima Laboral</div><div style='background:#F7F9FC;border-radius:7px;padding:7px;'>eNPS Bienestar</div><div style='background:#F7F9FC;border-radius:7px;padding:7px;'>Plan Bienestar</div></div></div></div>" &
			"<div style='position:absolute;left:42px;bottom:26px;width:1210px;height:42px;background:#ffffff;border:1px solid #E1E8F2;border-radius:12px;display:flex;align-items:center;padding:0 18px;box-sizing:border-box;color:#53657D;font-size:12px;'><span style='display:inline-block;width:8px;height:8px;background:#F7931E;border-radius:50%;margin-right:10px;'></span>Lectura sugerida: validar cobertura y satisfacci&oacute;n del frente activo antes de avanzar a focos de gesti&oacute;n.</div></div>"
		displayFolder: 11 HTML Propuestas
		lineageTag: b0132c21-8cd4-4669-8432-92927a52be84

	measure 'HTML Inicio Corporativo Propuesta 3' =
			VAR _Horas = IF(ISBLANK([Plan Horas Formacion]), "-", FORMAT([Plan Horas Formacion], "#,0"))
			VAR _Cobertura = IF(ISBLANK([% Cobertura]), "-", FORMAT([% Cobertura], "0.0%"))
			VAR _Satisfaccion = IF(ISBLANK([Encuesta Favorabilidad]), "-", FORMAT([Encuesta Favorabilidad], "0.0%"))
			VAR _Onboarding = IF(ISBLANK([Induccion Porcentaje Cumplimiento]), "-", FORMAT([Induccion Porcentaje Cumplimiento], "0.0%"))
			VAR _Entrenamiento = IF(ISBLANK([Induccion Porcentaje Entrenamiento Neto]), "-", FORMAT([Induccion Porcentaje Entrenamiento Neto], "0.0%"))
			VAR _PDI = IF(ISBLANK([PDI Total]), "-", FORMAT([PDI Total], "#,0"))
			VAR _AlertasPDI = IF(ISBLANK([PDI Alertas Criticas]), "-", FORMAT([PDI Alertas Criticas], "#,0"))
			RETURN
			"<div style='width:1280px;height:720px;box-sizing:border-box;position:relative;background:#ffffff;font-family:Outfit,Segoe UI,Arial,sans-serif;color:#0B1C35;overflow:hidden;'>" &
			"<div style='position:absolute;left:0;top:0;width:250px;height:720px;background:#0B1C35;color:#ffffff;padding:32px 24px;box-sizing:border-box;'><div style='font-size:11px;color:#F7931E;letter-spacing:1.7px;text-transform:uppercase;font-weight:800;'>Home estrategico</div><div style='font-size:28px;line-height:32px;font-weight:850;margin-top:12px;'>Mapa de frentes</div><div style='font-size:13px;color:#c8d6e8;line-height:19px;margin-top:16px;'>Una vista madre para navegar la evoluci&oacute;n del Dashboard Corporativo.</div><div style='position:absolute;bottom:34px;left:24px;right:24px;border-top:1px solid rgba(255,255,255,.18);padding-top:18px;font-size:12px;color:#c8d6e8;'>Estado actual<br><span style='color:#F7931E;font-size:20px;font-weight:850;'>Aprendizaje MVP</span></div></div>" &
			"<div style='position:absolute;left:276px;top:26px;width:956px;height:76px;background:#F7F9FC;border:1px solid #DCE5F2;border-radius:14px;box-sizing:border-box;'><div style='position:absolute;left:20px;top:10px;font-size:12px;font-weight:800;color:#1A3059;text-transform:uppercase;letter-spacing:.8px;'>Filtros para lectura corporativa</div></div>" &
			"<div style='position:absolute;left:276px;top:126px;width:956px;height:168px;display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:16px;'>" &
			"<div style='background:#1A3059;color:#ffffff;border-radius:14px;padding:22px;box-shadow:0 12px 30px rgba(11,28,53,.14);'><div style='font-size:12px;color:#F7931E;font-weight:800;'>Frente activo</div><div style='font-size:30px;font-weight:850;margin-top:6px;'>Aprendizaje</div><div style='font-size:12px;color:#d9e4f2;line-height:18px;margin-top:8px;'>Lectura integrada de formaci&oacute;n, cobertura, satisfacci&oacute;n, onboarding y entrenamiento.</div></div>" &
			"<div style='background:#ffffff;border:1px solid #DCE5F2;border-radius:14px;padding:20px;'><div style='font-size:12px;color:#53657D;'>Horas de formaci&oacute;n</div><div style='font-size:34px;font-weight:850;color:#1B487F;margin-top:8px;'>" & _Horas & "</div><div style='height:5px;background:#F7931E;border-radius:8px;margin-top:18px;width:72%;'></div></div>" &
			"<div style='background:#ffffff;border:1px solid #DCE5F2;border-radius:14px;padding:20px;'><div style='font-size:12px;color:#53657D;'>Cobertura / satisfacci&oacute;n</div><div style='display:flex;gap:20px;margin-top:14px;'><div><div style='font-size:27px;font-weight:850;color:#1B487F;'>" & _Cobertura & "</div><div style='font-size:11px;color:#53657D;'>Cobertura</div></div><div><div style='font-size:27px;font-weight:850;color:#1B487F;'>" & _Satisfaccion & "</div><div style='font-size:11px;color:#53657D;'>Satisfacci&oacute;n</div></div></div></div></div>" &
			"<div style='position:absolute;left:276px;top:320px;width:956px;height:268px;display:grid;grid-template-columns:1.05fr 1fr;gap:18px;'>" &
			"<div style='background:#ffffff;border:1px solid #E1E8F2;border-radius:14px;padding:24px;box-shadow:0 10px 28px rgba(11,28,53,.06);'><div style='font-size:12px;color:#F7931E;text-transform:uppercase;font-weight:800;letter-spacing:1px;'>Ruta corporativa</div><div style='display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px;'>" &
			"<div style='background:#0B1C35;color:#ffffff;border-radius:12px;padding:18px;'><div style='font-size:20px;font-weight:850;'>Aprendizaje</div><div style='font-size:11px;color:#cbd8e8;margin-top:7px;'>Activo | " & _Onboarding & " onboarding</div></div>" &
			"<div style='background:#F7F9FC;border:1px solid #DCE5F2;border-radius:12px;padding:18px;'><div style='font-size:20px;font-weight:850;color:#1A3059;'>Desempe&ntilde;o</div><div style='font-size:11px;color:#53657D;margin-top:7px;'>Pr&oacute;xima fase</div></div>" &
			"<div style='background:#FFF7EE;border:1px solid #F7931E;border-radius:12px;padding:18px;'><div style='font-size:20px;font-weight:850;color:#1A3059;'>Desarrollo</div><div style='font-size:11px;color:#9D5600;margin-top:7px;'>" & _PDI & " PDI | " & _AlertasPDI & " alertas</div></div>" &
			"<div style='background:#F7F9FC;border:1px solid #DCE5F2;border-radius:12px;padding:16px;'><div style='font-size:20px;font-weight:850;color:#1A3059;'>Bienestar y Clima</div><div style='font-size:11px;color:#F7931E;font-weight:800;margin-top:7px;'>Entrevista de Retiro activa</div><div style='font-size:10px;color:#53657D;line-height:14px;margin-top:8px;'>Planes Clima Laboral &bull; eNPS Bienestar &bull; Plan Bienestar</div></div></div></div>" &
			"<div style='background:#0B1C35;color:#ffffff;border-radius:14px;padding:24px;'><div style='font-size:12px;color:#F7931E;text-transform:uppercase;font-weight:800;letter-spacing:1px;'>Foco ejecutivo</div><div style='font-size:25px;line-height:30px;font-weight:850;margin-top:12px;'>Priorizar brechas del frente activo</div><div style='font-size:13px;line-height:19px;color:#d9e4f2;margin-top:12px;'>Entrenamiento neto " & _Entrenamiento & ", cobertura " & _Cobertura & " y satisfacci&oacute;n " & _Satisfaccion & " deben orientar la conversaci&oacute;n gerencial.</div><div style='margin-top:24px;background:#F7931E;color:#0B1C35;border-radius:22px;padding:9px 14px;display:inline-block;font-size:12px;font-weight:850;'>Ir a decisiones del bloque</div></div></div>" &
			"<div style='position:absolute;left:276px;top:616px;width:956px;height:58px;background:#F7F9FC;border:1px solid #DCE5F2;border-radius:14px;display:flex;align-items:center;gap:18px;padding:0 22px;box-sizing:border-box;'><div style='font-size:12px;color:#53657D;'>Escalabilidad futura</div><div style='height:26px;width:1px;background:#DCE5F2;'></div><div style='font-size:12px;color:#1A3059;font-weight:750;'>Los frentes pendientes se mantienen visibles como roadmap para evitar una portada aislada del programa corporativo.</div></div></div>"
		displayFolder: 11 HTML Propuestas
		lineageTag: c9f46c0b-dd6c-4f12-bfec-4558f16abf2f

	measure 'EntrevistaRetiro Total' = COUNTROWS('Fct_EntrevistaRetiro_Unificada')
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: f807b926-f383-42b3-938f-8342e825ccef

	measure 'EntrevistaRetiro Total Validas' = CALCULATE([EntrevistaRetiro Total], 'Fct_EntrevistaRetiro_Unificada'[RegistroValido_Flag] = 1)
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 8a939516-4eec-4449-9e88-47861c581f2e

	measure 'EntrevistaRetiro Total No Validas' = CALCULATE([EntrevistaRetiro Total], 'Fct_EntrevistaRetiro_Unificada'[RegistroValido_Flag] = 0)
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 4b22d283-ed26-42b7-87fe-a0dc6dd3b7bd

	measure 'EntrevistaRetiro Porcentaje Validas' = DIVIDE([EntrevistaRetiro Total Validas], [EntrevistaRetiro Total], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 0bbfbc38-cfaa-47ba-8032-b1b0451c79e4

	measure 'EntrevistaRetiro Total Voluntarios' = CALCULATE([EntrevistaRetiro Total Validas], 'Dim_TipoRetiro'[TipoRetiro_Key] = "VOLUNTARIO")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: ce3fc002-75f7-4c88-9fa7-95a9bd46436f

	measure 'EntrevistaRetiro Total Involuntarios' = CALCULATE([EntrevistaRetiro Total Validas], 'Dim_TipoRetiro'[TipoRetiro_Key] = "INVOLUNTARIO")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 46e0a13f-bc98-4df9-a82c-96381f2b72bc

	measure 'EntrevistaRetiro Porcentaje Voluntarios' = DIVIDE([EntrevistaRetiro Total Voluntarios], [EntrevistaRetiro Total Validas], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 4b8a6985-b643-4ecd-a112-33f8cf286f2a

	measure 'EntrevistaRetiro Porcentaje Involuntarios' = DIVIDE([EntrevistaRetiro Total Involuntarios], [EntrevistaRetiro Total Validas], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 084eb376-0877-4fda-998a-b71a897fddda

	measure 'EntrevistaRetiro Total Fuentes' = DISTINCTCOUNT('Dim_FuenteEntrevistaRetiro'[FuenteEntrevista_Key])
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 23a34a57-4d5d-4154-bff4-be8b372bf40f

	measure 'EntrevistaRetiro Motivo Principal' =
			VAR _Tabla =
			    TOPN(
			        1,
			        ADDCOLUMNS(
			            ALLSELECTED('Dim_MotivoRetiro'[Motivo_Retiro]),
			            "_Total", [EntrevistaRetiro Total Validas]
			        ),
			        [_Total], DESC,
			        'Dim_MotivoRetiro'[Motivo_Retiro], ASC
			    )
			RETURN
			    COALESCE(CONCATENATEX(_Tabla, 'Dim_MotivoRetiro'[Motivo_Retiro], ", "), "Sin datos")
		displayFolder: 13 Entrevista Retiro
		lineageTag: b053a6f4-7ac9-4eb4-a1b8-c6ae55aceb5f

	measure 'EntrevistaRetiro Total Motivos Distintos' = DISTINCTCOUNT('Dim_MotivoRetiro'[MotivoRetiro_Key])
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 2dcd81c3-e651-4b14-9713-3bd0643b5604

	measure 'EntrevistaRetiro Participacion Motivo' = DIVIDE([EntrevistaRetiro Total Validas], CALCULATE([EntrevistaRetiro Total Validas], ALLSELECTED('Dim_MotivoRetiro'[Motivo_Retiro])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 0773a6dd-436f-4de5-9e6a-cc057fb0e1bf

	measure 'EntrevistaRetiro Participacion UnidadNegocio' = DIVIDE([EntrevistaRetiro Total Validas], CALCULATE([EntrevistaRetiro Total Validas], ALLSELECTED('Dim_UnidadNegocioRetiro'[Unidad_Negocio])), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: a8690235-fd4a-4e27-9321-7b0fff4175ea

	measure 'EntrevistaRetiro UnidadNegocio Top' =
			VAR _Tabla =
			    TOPN(
			        1,
			        ADDCOLUMNS(
			            ALLSELECTED('Dim_UnidadNegocioRetiro'[Unidad_Negocio]),
			            "_Total", [EntrevistaRetiro Total Validas]
			        ),
			        [_Total], DESC,
			        'Dim_UnidadNegocioRetiro'[Unidad_Negocio], ASC
			    )
			RETURN
			    COALESCE(CONCATENATEX(_Tabla, 'Dim_UnidadNegocioRetiro'[Unidad_Negocio], ", "), "Sin datos")
		displayFolder: 13 Entrevista Retiro
		lineageTag: 8fe1e468-8ed6-4add-9607-40b353ed2d01

	measure 'EntrevistaRetiro Causas Prevenibles' = CALCULATE([EntrevistaRetiro Total Validas], 'Fct_EntrevistaRetiro_Unificada'[CausaPrevenible_Key] = "SI")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 9ce75590-6ec4-420f-880c-ed7f6f627042

	measure 'EntrevistaRetiro Porcentaje Causas Prevenibles' = DIVIDE([EntrevistaRetiro Causas Prevenibles], [EntrevistaRetiro Total Validas], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 340abcd8-a6e6-4b5d-9996-b6b70dedbf99

	measure 'EntrevistaRetiro Variacion Mensual' = [EntrevistaRetiro Total Validas] - CALCULATE([EntrevistaRetiro Total Validas], DATEADD('Dim_Calendario'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 8e8763df-25ca-424c-96c2-a4052a408be1

	measure 'EntrevistaRetiro Variacion Mensual Porcentaje' = DIVIDE([EntrevistaRetiro Variacion Mensual], CALCULATE([EntrevistaRetiro Total Validas], DATEADD('Dim_Calendario'[Date], -1, MONTH)), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13 Entrevista Retiro
		lineageTag: 6ecb0227-0552-4d0c-85aa-f4e63bb78d9d

	measure 'EntrevistaRetiro Registros Requieren Plan' = CALCULATE([EntrevistaRetiro Total Validas], 'Fct_EntrevistaRetiro_Unificada'[RequierePlanAccion] = "Si")
		formatString: #,0
		displayFolder: 13 Entrevista Retiro
		lineageTag: 2252ede9-0a9f-4428-ba44-f1e21971f379

	measure 'HTML Entrevista Retiro Shell' =
			"<div style='font-family: Outfit, Poppins, Segoe UI, Arial; width:1280px; height:720px; background:#F7F9FC; color:#0B1C35; position:relative; overflow:hidden;'>" &
			"<div style='position:absolute; left:0; top:0; width:1280px; height:92px; background:#1B487F;'></div>" &
			"<div style='position:absolute; left:34px; top:20px; color:#F7931E; font-size:11px; font-weight:800; letter-spacing:2px;'>BIENESTAR Y CLIMA</div>" &
			"<div style='position:absolute; left:34px; top:39px; color:#FFFFFF; font-size:28px; font-weight:800;'>Entrevista de Retiro</div>" &
			"<div style='position:absolute; left:34px; top:68px; color:#D8E4F2; font-size:11px;'>Motivos de salida, oportunidades de mejora y senales para Gestion Humana</div>" &
			"<div style='position:absolute; right:36px; top:24px; padding:9px 15px; background:#F7931E; color:#0B1C35; border-radius:18px; font-size:11px; font-weight:800;'>Bloque Bienestar y Clima</div>" &
			"<div style='position:absolute; left:28px; top:106px; width:1224px; height:58px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:34px; top:174px; width:1220px; height:77px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:34px; top:265px; width:390px; height:218px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:444px; top:265px; width:390px; height:218px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:854px; top:265px; width:398px; height:218px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:34px; top:500px; width:390px; height:166px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:444px; top:500px; width:390px; height:166px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:854px; top:500px; width:398px; height:166px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:7px;'></div>" &
			"<div style='position:absolute; left:34px; top:683px; color:#5E6B7A; font-size:10px;'>Analisis agregado. La pagina evita exponer datos personales y usa registros validos con autorizacion aceptada.</div>" &
			"</div>"
		displayFolder: 11 HTML Propuestas
		lineageTag: 941825c0-80a2-4d05-ad36-af2d02475fca

	measure 'HTML BC00 Resumen Bienestar y Clima' =
			"<div style='font-family:Outfit,Poppins,Segoe UI,Arial; width:1280px; height:720px; background:#F7F9FC; color:#0B1C35; position:relative; overflow:hidden;'>" &
			"<div style='position:absolute; left:0; top:0; width:1280px; height:92px; background:linear-gradient(135deg,#1A3059,#1B487F);'></div>" &
			"<div style='position:absolute; left:34px; top:18px; color:#F7931E; font-size:11px; font-weight:800; letter-spacing:2px;'>BIENESTAR Y CLIMA</div>" &
			"<div style='position:absolute; left:34px; top:37px; color:#FFFFFF; font-size:26px; font-weight:800;'>Resumen Ejecutivo</div>" &
			"<div style='position:absolute; left:34px; top:68px; color:#D8E4F2; font-size:11px;'>Frentes de gestion disponibles en el bloque Bienestar y Clima</div>" &
			"<div style='position:absolute; right:36px; top:24px; padding:9px 16px; background:#F7931E; color:#0B1C35; border-radius:18px; font-size:11px; font-weight:800;'>Inicio Corporativo</div>" &
			"<div style='position:absolute; left:34px; top:106px; right:34px; height:24px; color:#5E6B7A; font-size:11px; line-height:24px;'>Selecciona un frente para explorar los analisis disponibles.</div>" &
			"<div style='position:absolute; left:34px; top:144px; width:592px; height:230px; background:#0B1C35; border:2px solid #F7931E; border-radius:10px; padding:22px 24px;'>" &
			"<div style='display:flex; align-items:center; margin-bottom:10px;'><span style='background:#F7931E; color:#fff; font-size:10px; font-weight:700; padding:3px 10px; border-radius:20px; letter-spacing:1px; margin-right:10px;'>ACTIVO</span><span style='color:#94A3B8; font-size:10px;'>Modulo 01</span></div>" &
			"<div style='color:#FFFFFF; font-size:17px; font-weight:700; margin-bottom:8px;'>Entrevista de Retiro</div>" &
			"<div style='color:#94A3B8; font-size:12px; line-height:1.55;'>Analisis de causas de desvinculacion, tendencias por unidad y tipologia de salida. Datos anonimizados con autorizacion valida.</div>" &
			"<div style='position:absolute; bottom:18px; left:24px; color:#F7931E; font-size:11px; font-weight:600;'>Ver analisis →</div>" &
			"</div>" &
			"<div style='position:absolute; left:654px; top:144px; width:592px; height:230px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:10px; padding:22px 24px;'>" &
			"<div style='display:flex; align-items:center; margin-bottom:10px;'><span style='background:#F59E0B; color:#fff; font-size:10px; font-weight:700; padding:3px 10px; border-radius:20px; letter-spacing:1px; margin-right:10px;'>EN CONSTRUCCION</span><span style='color:#94A3B8; font-size:10px;'>Modulo 02</span></div>" &
			"<div style='color:#1A3059; font-size:17px; font-weight:700; margin-bottom:8px;'>Planes Clima Laboral</div>" &
			"<div style='color:#6B7280; font-size:12px; line-height:1.55;'>Seguimiento a planes de trabajo de clima organizacional, indicadores de ambiente laboral y acciones correctivas en curso.</div>" &
			"<div style='position:absolute; bottom:18px; left:24px; color:#9CA3AF; font-size:11px; font-style:italic;'>Disponible proxima fase</div>" &
			"</div>" &
			"<div style='position:absolute; left:34px; top:394px; width:592px; height:218px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:10px; padding:22px 24px;'>" &
			"<div style='display:flex; align-items:center; margin-bottom:10px;'><span style='background:#F59E0B; color:#fff; font-size:10px; font-weight:700; padding:3px 10px; border-radius:20px; letter-spacing:1px; margin-right:10px;'>EN CONSTRUCCION</span><span style='color:#94A3B8; font-size:10px;'>Modulo 03</span></div>" &
			"<div style='color:#1A3059; font-size:17px; font-weight:700; margin-bottom:8px;'>eNPS Actividades Bienestar</div>" &
			"<div style='color:#6B7280; font-size:12px; line-height:1.55;'>Net Promoter Score de actividades de bienestar, participacion y cobertura de programas corporativos.</div>" &
			"<div style='position:absolute; bottom:18px; left:24px; color:#9CA3AF; font-size:11px; font-style:italic;'>Disponible proxima fase</div>" &
			"</div>" &
			"<div style='position:absolute; left:654px; top:394px; width:592px; height:218px; background:#FFFFFF; border:1px solid #DDE7F1; border-radius:10px; padding:22px 24px;'>" &
			"<div style='display:flex; align-items:center; margin-bottom:10px;'><span style='background:#F59E0B; color:#fff; font-size:10px; font-weight:700; padding:3px 10px; border-radius:20px; letter-spacing:1px; margin-right:10px;'>EN CONSTRUCCION</span><span style='color:#94A3B8; font-size:10px;'>Modulo 04</span></div>" &
			"<div style='color:#1A3059; font-size:17px; font-weight:700; margin-bottom:8px;'>Cumplimiento Plan Bienestar</div>" &
			"<div style='color:#6B7280; font-size:12px; line-height:1.55;'>Avance frente al plan anual de bienestar, porcentaje de cumplimiento y actividades pendientes.</div>" &
			"<div style='position:absolute; bottom:18px; left:24px; color:#9CA3AF; font-size:11px; font-style:italic;'>Disponible proxima fase</div>" &
			"</div>" &
			"<div style='position:absolute; left:34px; top:630px; color:#9CA3AF; font-size:10px;'>Dashboard Corporativo Grupo LEMCO — Bienestar y Clima</div>" &
			"</div>"
		displayFolder: 12 HTML Bienestar
		lineageTag: bc001234-5678-90ab-cdef-bc0012345678

	measure 'Home Pagina Resumen Frente' =
			VAR _Frente = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			RETURN
			    SWITCH(
			        _Frente,
			        "Aprendizaje", "A01 Resumen Ejecutivo Aprendizaje",
			        "Desarrollo", "D01 Resumen Ejecutivo Desarrollo",
			        "Bienestar y Clima", "BC00 Resumen Ejecutivo Bienestar y Clima",
			        "Desempeno", "E01 Desempeno - Proxima Fase",
			        "A01 Resumen Ejecutivo Aprendizaje"
			    )
		displayFolder: 00 Home Corporativo
		lineageTag: 1c4f494b-a83d-4be8-a952-9f52118d950e

	measure 'Home Tooltip Resumen Frente' =
			VAR _Frente = SELECTEDVALUE('Dim_Frente_Home'[Frente], "Aprendizaje")
			RETURN
			    "Ir a " & [Home Pagina Resumen Frente]
		displayFolder: 00 Home Corporativo
		lineageTag: 2771f7ad-7ef2-45bd-9881-9ef6aaf7f9e1

	column Indice
		dataType: int64
		isHidden
		lineageTag: b2e8471f-a590-4c95-b4ad-18d6cd43dc5a
		sourceColumn: [Indice]

	partition Medidas_AD = calculated
		mode: import
		source = DATATABLE("Indice", INTEGER, {{ 0 }})

